INHERIT: ../../mkdocs.base.yml
site_name: توثيق Dinoapp
site_url: https://gnucoop.github.io/dino/ar/
docs_dir: ../../docs/ar
site_dir: ../../site/ar
theme:
  name: material
  language: ar
  direction: rtl
nav:
  - الرئيسية: index.md
  - البدء:
    - تسجيل الدخول: getting-started/login.md
    - إعادة تعيين كلمة المرور: getting-started/reset-password.md
  - الواجهة والتنقل: interface/index.md
  - لوحة المعلومات: dashboard/index.md
  - النماذج:
    - نظرة عامة: forms/index.md
    - تحرير مخطط النموذج: forms/edit-form-schema.md
    - تحرير إرسال نموذج: forms/edit-form.md
    - استيراد البيانات: forms/import.md
    - خريطة النماذج: forms/forms-map.md
    - Datachat: forms/datachat.md
  - التقارير:
    - نظرة عامة: reports/index.md
    - تحرير مخطط التقرير: reports/edit-report-schema.md
    - تعديل التقرير: reports/edit-report.md
  - المقاييس:
    - نظرة عامة: metrics/index.md
    - المجالات الموضوعية: metrics/areas.md
    - الحالات: metrics/cases.md
    - المواقع: metrics/locations.md
    - المنظمات: metrics/organizations.md
    - المشاريع: metrics/projects.md
  - التجميع: aggregation/index.md
  - الإشعارات: notifications/index.md
  - النماذج العامة: public-forms/index.md
  - الإدارة:
    - إدارة المستخدمين والمجموعات: administration/users.md
    - إدارة اللغات: administration/languages.md
    - قائمة المستخدمين: administration/users-list.md
    - قائمة المجموعات: administration/groups-list.md
