export const reportDatas = [
  {
    id: 'b0170e25-5e0b-42a1-a8c1-938fb65bd102',
    user_data_ref_id: 'user_a',
    report_schema_ref_id: 'generic_report',
    metadata: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    area_ref_id: null,
    case_ref_id: null,
    location_ref_id: null,
    organization_ref_id: null,
    project_ref_id: null,
    date_start: null,
    date_end: null,
  },
  {
    id: '709cebb5-7ea0-4e59-969a-7b095d7fec3e',
    user_data_ref_id: 'user_a',
    report_schema_ref_id: 'generic_report',
    metadata: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    area_ref_id: null,
    case_ref_id: null,
    location_ref_id: null,
    organization_ref_id: null,
    project_ref_id: null,
    date_start: null,
    date_end: null,
  },
] as any[];
