import {projects} from './test-projects';

const ajfSourceReportFormDatas = [
  {
    'age': 31,
    'poc': 'opd',
    'cf_od': null,
    'cf_os': null,
    'hm_od': null,
    'hm_os': null,
    'lp_od': null,
    'lp_os': null,
    'va_od': null,
    'va_os': '6_9',
    'gender': 'f',
    'iop_os': '21',
    'parish': 'aa',
    'lens_od': null,
    'lens_os': 'lens_clear',
    'district': 'arua',
    'pupil_od': null,
    'pupil_os': 'pupil_crrl',
    'cornea_od': null,
    'cornea_os': 'opaque',
    'fundus_od': null,
    'fundus_os': 'fundus_normal',
    'pregnancy': 'y',
    'eye_lid_od': null,
    'eye_lid_os': 'normal',
    'patient_id': '8989',
    'settlement': 'aa',
    'sub_county': 'vurra',
    'nationality': 'ugandans',
    'diagnosis_od': null,
    'diagnosis_os': ['ec03', 'ec08'],
    'disabilities': null,
    'eyes_checked': ['os'],
    'treatment_od': null,
    'treatment_os': ['spectacle'],
    'conjunctiva_od': null,
    'conjunctiva_os': 'normal',
    'chief_complaint': 'doc',
    'disability_status': 'n',
    'pupil_os_irregular': null,
    'anterior_chamber_od': null,
    'anterior_chamber_os': 'anterior_chamber_normal',
  },
  {
    'age': 56,
    'poc': 'pnc',
    'cf_od': null,
    'cf_os': null,
    'hm_od': null,
    'hm_os': null,
    'lp_od': null,
    'lp_os': null,
    'va_od': '6_24',
    'va_os': null,
    'gender': 'm',
    'iop_od': 14,
    'parish': 'A',
    'lens_od': 'lens_aphakic',
    'lens_os': null,
    'village': 'A',
    'district': 'lamwo',
    'pupil_od': 'pupil_crrl',
    'pupil_os': null,
    'cornea_od': 'clear',
    'cornea_os': null,
    'fundus_od': 'fundus_normal',
    'fundus_os': null,
    'pregnancy': null,
    'eye_lid_od': 'normal',
    'eye_lid_os': null,
    'patient_id': '6677',
    'settlement': 'A',
    'sub_county': 'padibe',
    'nationality': 'ugandans',
    'diagnosis_od': ['ec01'],
    'diagnosis_os': null,
    'disabilities': ['ds01'],
    'eyes_checked': ['od'],
    'treatment_od': ['other'],
    'treatment_os': null,
    'conjunctiva_od': 'inflamed',
    'conjunctiva_os': null,
    'chief_complaint': 'Doc',
    'disability_status': 'y',
    'treatment_other_od': 'antibiotics',
    'anterior_chamber_od': 'anterior_chamber_normal',
    'anterior_chamber_os': null,
  },
  {
    'age': 56,
    'poc': null,
    'cf_od': null,
    'cf_os': null,
    'hm_od': null,
    'hm_os': null,
    'lp_od': null,
    'lp_os': null,
    'va_od': null,
    'va_os': null,
    'gender': 'm',
    'parish': 'Par',
    'lens_od': null,
    'lens_os': null,
    'district': 'agago',
    'pupil_od': null,
    'pupil_os': null,
    'cornea_od': null,
    'cornea_os': null,
    'fundus_od': null,
    'fundus_os': null,
    'pregnancy': null,
    'eye_lid_od': null,
    'eye_lid_os': null,
    'patient_id': '1234',
    'settlement': 'Sett',
    'sub_county': 'adilang',
    'nationality': 'ugandans',
    'diagnosis_od': null,
    'diagnosis_os': null,
    'disabilities': null,
    'eyes_checked': null,
    'treatment_od': null,
    'treatment_os': null,
    'conjunctiva_od': null,
    'conjunctiva_os': null,
    'disability_status': 'n',
    'anterior_chamber_od': null,
    'anterior_chamber_os': null,
  },
  {
    'age': 19,
    'poc': 'pnc',
    'cf_od': null,
    'cf_os': null,
    'hm_od': null,
    'hm_os': null,
    'lp_od': null,
    'lp_os': null,
    'va_od': null,
    'va_os': null,
    'gender': 'f',
    'parish': 'Par',
    'lens_od': null,
    'lens_os': null,
    'village': 'Vil',
    'district': 'arua',
    'pupil_od': null,
    'pupil_os': null,
    'cornea_od': null,
    'cornea_os': null,
    'fundus_od': null,
    'fundus_os': null,
    'pregnancy': 'n',
    'eye_lid_od': null,
    'eye_lid_os': null,
    'patient_id': '3456',
    'settlement': 'Ar',
    'sub_county': 'omugo_hciv',
    'nationality': 'refugees',
    'diagnosis_od': null,
    'diagnosis_os': null,
    'disabilities': null,
    'eyes_checked': null,
    'treatment_od': null,
    'treatment_os': null,
    'conjunctiva_od': null,
    'conjunctiva_os': null,
    'disability_status': 'n',
    'anterior_chamber_od': null,
    'anterior_chamber_os': null,
  },
];

export const formDatas = [
  {
    id: '3a627515-bd5f-4599-b0c6-5a5ad4c42bba',
    user_data_ref_id: null,
    form_schema_ref_id: 'prova',
    data: ajfSourceReportFormDatas[0],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    area_ref_id: null,
    case_ref_id: null,
    location_ref_id: null,
    organization_ref_id: null,
    project_ref_id: projects[0].id,
    form_status_ref_id: null,
  },
  {
    id: '5c98aa0d-ded0-4cce-a8a1-f5be18c12433',
    user_data_ref_id: null,
    form_schema_ref_id: 'prova',
    data: ajfSourceReportFormDatas[1],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    area_ref_id: null,
    case_ref_id: null,
    location_ref_id: null,
    organization_ref_id: null,
    project_ref_id: null,
    form_status_ref_id: null,
  },
  {
    id: '1a95052e-8068-4456-8e70-357109970a83',
    user_data_ref_id: null,
    form_schema_ref_id: 'prova',
    data: ajfSourceReportFormDatas[2],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    area_ref_id: null,
    case_ref_id: null,
    location_ref_id: null,
    organization_ref_id: null,
    project_ref_id: null,
    form_status_ref_id: null,
  },
  {
    id: 'aa6fa67a-a8ad-46bd-92ad-69d8549c03d6',
    user_data_ref_id: null,
    form_schema_ref_id: 'prova',
    data: ajfSourceReportFormDatas[3],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    area_ref_id: null,
    case_ref_id: null,
    location_ref_id: null,
    organization_ref_id: null,
    project_ref_id: null,
    form_status_ref_id: null,
  },
] as any[];
