INHERIT: ../../mkdocs.base.yml
site_name: Dino Documentation
site_url: https://gnucoop.github.io/dino/en/
docs_dir: ../../docs/en
site_dir: ../../site/en
theme:
  name: material
  language: en
nav:
  - Home: index.md
  - Getting Started:
    - Login: getting-started/login.md
    - Reset Password: getting-started/reset-password.md
  - Interface & Navigation: interface/index.md
  - Dashboard: dashboard/index.md
  - Forms:
    - Overview: forms/index.md
    - Edit Form Schema: forms/edit-form-schema.md
    - Edit Form: forms/edit-form.md
    - Forms Map: forms/forms-map.md
    - Datachat: forms/datachat.md
  - Reports:
    - Overview: reports/index.md
    - Edit Report Schema: reports/edit-report-schema.md
    - Edit Report: reports/edit-report.md
  - Metrics:
    - Overview: metrics/index.md
    - Thematic Areas: metrics/areas.md
    - Cases: metrics/cases.md
    - Locations: metrics/locations.md
    - Organizations: metrics/organizations.md
    - Projects: metrics/projects.md
  - Aggregation: aggregation/index.md
  - Notifications: notifications/index.md
  - Public Forms: public-forms/index.md
  - Administration:
    - Users: administration/users.md
    - Languages: administration/languages.md
    - Users List: administration/users-list.md
    - Groups List: administration/groups-list.md
