load(
    "//tools:defaults.bzl",
    "markdown_to_html",
    "ng_module",
    "ng_test_library",
    "ng_web_test_suite",
    "sass_library",
)

package(default_visibility = ["//visibility:public"])

ng_module(
    name = "list-datasource",
    srcs = glob(
        ["**/*.ts"],
        exclude = ["**/*.spec.ts"],
    ),
    assets = [],
    module_name = "@dewco/material/list-datasource",
    deps = [
        "//src/core/list",
        "@npm//@angular/material",
        "@npm//@types/uuid",
        "@npm//rxdb",
        "@npm//rxjs",
    ],
)

sass_library(
    name = "list_datasource_scss_lib",
    srcs = glob(["**/_*.scss"]),
)

ng_test_library(
    name = "unit_test_sources",
    srcs = glob(
        ["**/*.spec.ts"],
        exclude = ["**/*.e2e.spec.ts"],
    ),
    deps = [
        ":list-datasource",
        "//src/core/auth",
        "//src/core/data",
        "//src/core/error-handler",
        "//src/core/forms",
        "//src/core/list",
        "@npm//@angular/common",
        "@npm//@angular/router",
        "@npm//rxdb",
        "@npm//rxjs",
    ],
)

ng_web_test_suite(
    name = "unit_tests",
    deps = [":unit_test_sources"],
)

markdown_to_html(
    name = "overview",
    srcs = ["list-datasource.md"],
)

filegroup(
    name = "source-files",
    srcs = glob(["**/*.ts"]),
)
