image: devgnucoop/dinobitbucketpipeline:20.11.1
definitions:
  caches:
    nodecustom: ./node_modules
    yarn: /usr/local/share/.cache/yarn
pipelines:
  branches:
    master:
      - step:
          name: Setup Packages, Lint and Build
          caches:
            - nodecustom
            - yarn
          script:
            - rm -rf dist
            - yarn install --frozen-lockfile --non-interactive --network-timeout 600000
            - yarn -s lint
            - ./scripts/build.mjs
      - step:
          name: Model schema, Unit and E2E tests
          size: 2x
          script:
            - yarn install --frozen-lockfile --non-interactive --network-timeout 600000
            - ./scripts/e2e-ci.mjs
            - yarn -s model-schema-test
            - yarn -s test:ci
      - step:
          name: Build release, docs, Create Artifacts and Publish on Bytesafe
          script:
            - rm -rf dist
            - yarn install --frozen-lockfile --non-interactive --network-timeout 600000
            - ./scripts/release.mjs
            - ./scripts/build-docs.mjs
            - ./scripts/jenkins/create-build-artifacts.mjs
            - ./scripts/publish.mjs
          artifacts:
            - dist/artifacts/**/*.tgz
