import {ComponentFixture, TestBed} from '@angular/core/testing';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import {DataModelManager} from '@dino/core/data';
import {ErrorHandlerMessageService} from '@dino/core/error-handler';
import {UserGroupManager} from '@dino/core/users';
import {TranslocoModule} from '@ngneat/transloco';
import {Observable, of} from 'rxjs';

import {MetricImport} from './metric-import';
import {MetricImportModule} from './metric-import.module';

/**
 * A project-like schema: name and code are mandatory, the parent properties are
 * required but nullable, and code_auto is generated by Dino.
 */
const projectSchema = {
  properties: {
    id: {type: 'string'},
    created_at: {type: 'string'},
    updated_at: {type: 'string'},
    is_deleted: {type: 'boolean'},
    _deleted: {type: 'boolean'},
    name: {type: 'string'},
    parent_id: {type: ['string', 'null']},
    parent_name: {type: ['string', 'null']},
    code: {type: 'string'},
    code_auto: {type: 'number'},
  },
  required: ['id', 'created_at', 'updated_at', 'name', 'parent_id', 'parent_name', 'code'],
};

let bulkCalls: {[key: string]: any}[][] = [];

const managerMock = {
  collectionSchema: projectSchema,
  query: (_: any) => of([]),
  bulkCreate: (docs: {[key: string]: any}[]) => {
    bulkCalls.push([...docs]);
    const level = bulkCalls.length;
    return of({success: docs.map((d, i) => ({...d, id: `p-${level}-${i}`})), error: []});
  },
} as unknown as DataModelManager<any>;

const userGroupManagerMock = {
  isActiveUserAdmin: (_roles: string[] = ['admin']): Observable<boolean> => of(true),
} as unknown as UserGroupManager;

const errorHandlerMock = {
  captureErrorMessage: (_msg: string, _level?: string) => {},
} as unknown as ErrorHandlerMessageService;

describe('Metric Import', () => {
  let fixture: ComponentFixture<MetricImport>;
  let metricImport: MetricImport;

  beforeEach(() => {
    bulkCalls = [];
    TestBed.configureTestingModule({
      imports: [BrowserAnimationsModule, MetricImportModule, TranslocoModule],
      providers: [
        {provide: UserGroupManager, useValue: userGroupManagerMock},
        {provide: ErrorHandlerMessageService, useValue: errorHandlerMock},
      ],
    }).compileComponents();
    fixture = TestBed.createComponent(MetricImport);
    metricImport = fixture.componentInstance;
    metricImport.metricName = 'project';
    metricImport.metricManager = managerMock;
  });

  it('should offer one field per importable property, named as the export writes it', () => {
    const names = metricImport.fields.map(f => f.name);
    // The columns of a Dino export, so that a re-import maps itself
    expect(names).toEqual([
      'project_name',
      'project_parent_id',
      'project_parent_name',
      'project_code',
    ]);
    // The generated properties are not mappable: code_auto used to slip through
    expect(names).not.toContain('project_code_auto');
    expect(names).not.toContain('project_id');
    expect(names).not.toContain('project_created_at');
    // A metric with no name cannot be created
    expect(metricImport.fields.filter(f => f.essential).map(f => f.name)).toEqual(['project_name']);
  });

  it('should not mutate the shared collection schema', () => {
    (metricImport as any)._getMetricsToBeCreated([{name: 'Alpha', code: 'c1'}]);
    expect(Object.keys(projectSchema.properties)).toContain('id');
    expect(Object.keys(projectSchema.properties)).toContain('code_auto');
  });

  it('should split the mapped rows by parent and collect the parent references', () => {
    const info = (metricImport as any)._getMetricsToBeCreated([
      {name: 'Root', code: 'c1'},
      {name: 'Child', parent_name: 'Root', code: 'c2'},
      {name: 'Other', parent_id: 'p-existing', code: 'c3'},
    ]);
    expect(info.newMetrics.map((m: any) => m.name)).toEqual(['Root']);
    expect(info.newMetricsWithParent.map((m: any) => m.name)).toEqual(['Child', 'Other']);
    expect(info.requiredMetricParentNames).toEqual(['Root']);
    expect(info.requiredMetricParentIds).toEqual(['p-existing']);
    expect(info.invalidRows).toEqual([]);
  });

  it('should report a row missing a required field with its file row number', () => {
    // No dictionary is loaded in the tests: interpolate the params by hand, so
    // the assertion can check which fields were reported
    spyOn((metricImport as any)._ts, 'translate').and.callFake(
      (key: string, params?: {[k: string]: any}) =>
        params ? key.replace(/{{(\w+)}}/g, (_m: string, p: string) => `${params[p]}`) : key,
    );
    const info = (metricImport as any)._getMetricsToBeCreated([
      {name: 'Root', code: 'c1'},
      {name: 'NoCode'},
    ]);
    expect(info.newMetrics.map((m: any) => m.name)).toEqual(['Root']);
    // The header is the first row of the file, so the second data row is row 3
    expect(info.invalidRows.length).toBe(1);
    expect(info.invalidRows[0].row).toBe(3);
    expect(info.invalidRows[0].text).toContain('NoCode');
    expect(info.invalidRows[0].text).toContain('code');
  });

  it('should create a parent defined by a later row of the same file', () => {
    metricImport.onApply({
      rows: [
        {project_name: 'Child', project_parent_name: 'Root', project_code: 'c2'},
        {project_name: 'Root', project_code: 'c1'},
      ],
      mappings: [
        {column: 'project_name', field: 'project_name'},
        {column: 'project_parent_name', field: 'project_parent_name'},
        {column: 'project_code', field: 'project_code'},
      ],
    });

    // One bulk creation per tree level: the parent first, then the child
    expect(bulkCalls.length).toBe(2);
    expect(bulkCalls[0].map(m => m['name'])).toEqual(['Root']);
    expect(bulkCalls[1].map(m => m['name'])).toEqual(['Child']);
    expect(bulkCalls[1][0]['parent_id']).toBe('p-1-0');
    expect(metricImport.outcome!.status).toBe('success');
    expect(metricImport.outcome!.counts[0].value).toBe(2);
  });
});
