load(
    "//tools:defaults.bzl",
    "markdown_to_html",
    "ng_module",
)
load("//tools/third-party-libs:index.bzl", "DATA_DEPS")

package(default_visibility = ["//visibility:public"])

ng_module(
    name = "reports",
    srcs = glob(
        ["**/*.ts"],
        exclude = ["**/*.spec.ts"],
    ),
    deps = [
        "//src/core/data",
        "//src/core/list",
        "@npm//@ajf/core",
    ],
)

markdown_to_html(
    name = "overview",
    srcs = ["reports.md"],
)

filegroup(
    name = "source-files",
    srcs = glob(["**/*.ts"]),
)
