load(
    "//tools:defaults.bzl",
    "markdown_to_html",
    "ng_module",
    "ng_test_library",
    "ng_web_test_suite",
)

package(default_visibility = ["//visibility:public"])

ng_module(
    name = "data",
    srcs = glob(
        ["**/*.ts"],
        exclude = ["**/*.spec.ts"],
    ),
    assets = [],
    module_name = "@dewco/core/data",
    deps = [
        "//src/core/auth",
        "//src/core/config",
        "@npm//@types/pouchdb-adapter-idb",
        "@npm//@types/pouchdb-adapter-memory",
        "@npm//@types/uuid",
        "@npm//rxdb",
        "@npm//rxjs",
        "@npm//subscriptions-transport-ws",
        "@npm//uuid",
    ],
)

ng_test_library(
    name = "unit_test_sources",
    srcs = glob(
        ["**/*.spec.ts"],
        exclude = ["**/*.e2e.spec.ts"],
    ),
    deps = [
        ":data",
        "//src/core/auth",
        "//src/core/config",
        "@npm//@angular/common",
        "@npm//mock-socket",
        "@npm//rxdb",
        "@npm//rxjs",
    ],
)

ng_web_test_suite(
    name = "unit_tests",
    deps = [":unit_test_sources"],
)

markdown_to_html(
    name = "overview",
    srcs = ["data.md"],
)

filegroup(
    name = "source-files",
    srcs = glob(["**/*.ts"]),
)
