load("//src/material:config.bzl", "MATERIAL_SCSS_LIBS")
load("//tools:defaults.bzl", "sass_binary", "sass_library")

package(default_visibility = ["//visibility:public"])

ALL_THEMING_FILES = [
    "_core.scss",
]

sass_library(
    name = "theming_scss_lib",
    srcs = ALL_THEMING_FILES,
    deps = MATERIAL_SCSS_LIBS,
)

sass_binary(
    name = "dino_theme_prebuilt",
    src = "theming/prebuilt/dino-theme.scss",
    deps = [":theming_scss_lib"],
)
