load("//tools:defaults.bzl", "ng_module", "sass_binary")

package(default_visibility = ["//visibility:public"])

ng_module(
    name = "auth",
    srcs = glob(["**/*.ts"]),
    assets = [
        "auth-demo.html",
        ":auth_demo_scss",
    ],
    deps = [
        "//src/core/auth",
        "@npm//@angular/forms",
        "@npm//@angular/material",
        "@npm//@angular/router",
    ],
)

sass_binary(
    name = "auth_demo_scss",
    src = "auth-demo.scss",
)
