/**
 * docs-screenshots.cy.js
 *
 * Cypress spec that visits each route from the route map and captures
 * screenshots for documentation. Screenshots are saved to docs/imgs/.
 *
 * The route map is generated by scripts/docs-route-scanner.mjs and stored
 * at scripts/docs-route-map.json.
 *
 * Routes with `resolveFrom` need a dynamic schema ID that only exists at
 * runtime (generated by RxDB in-memory).  For those, Cypress visits the
 * list page, clicks the first grid tile, extracts the ID from the URL,
 * and then navigates to the target via pushState + popstate (NOT cy.visit)
 * to avoid a full page reload that would regenerate all IDs.
 *
 * Routes with `resolveAction` (e.g. "visibility") need two-step resolution:
 * after clicking a grid tile to reach the data list, Cypress clicks the
 * matching row action icon to navigate to the actual data entry view
 * (e.g. /forms/{schemaId}/view/{dataId}).
 *
 * Viewport is set globally in cypress.config.ts (1440x900).  Individual
 * screenshots can override this via a `viewport` field (e.g. tablet size
 * for the sidenav-expanded screenshot).
 *
 * Run manually:
 *   yarn cypress run --spec "cypress/e2e/docs-screenshots.cy.js" --headless --browser chrome
 */

import routes from '../../scripts/docs-route-map.json';

describe('Documentation Screenshots', () => {
  const PAGE_LOAD_WAIT = 3000;
  const SCREENSHOT_WAIT = 600;

  /** Common visit options: accept GPT/datachat terms before Angular boots. */
  const visitOptions = {
    failOnStatusCode: false,
    onBeforeLoad(win) {
      win.localStorage.setItem('pandas_dino_api_key_accept_terms', 'true');
    },
  };

  /** Dismiss any open Material dialog (tutorial, welcome, etc.) */
  function dismissDialogs() {
    cy.get('body').then(($body) => {
      if ($body.find('mat-dialog-container').length) {
        cy.get('mat-dialog-container button').last().click();
        cy.wait(500);
      }
    });
  }

  /**
   * Navigate within the Angular SPA without a full page reload.
   * Uses pushState + popstate so Angular's router picks up the new URL
   * while keeping RxDB in-memory data (and its generated IDs) intact.
   */
  function navigateInApp(path) {
    cy.window().then((win) => {
      win.history.pushState({}, '', path);
      win.dispatchEvent(new PopStateEvent('popstate', { state: {} }));
    });
    cy.wait(PAGE_LOAD_WAIT);
  }

  /**
   * Reset all scroll containers to the top.
   * Covers: window, documentElement, body, and Angular Material's
   * mat-sidenav-content (the real scrollable container).
   * Also removes the CDK scroll-block class that Material dialogs add
   * (it sets position:fixed + top:-Npx on <html>, which shifts the viewport).
   */
  function scrollToTop() {
    cy.window().then((win) => {
      win.scrollTo(0, 0);
      win.document.documentElement.scrollTop = 0;
      win.document.body.scrollTop = 0;
      // Remove CDK dialog scroll-block that offsets the viewport
      win.document.documentElement.classList.remove('cdk-global-scrollblock');
      win.document.documentElement.style.top = '';
      const content = win.document.querySelector('mat-sidenav-content');
      if (content) content.scrollTop = 0;
    });
  }

  /** Handle setup-guard + screenshot capture for a single entry. */
  function captureScreenshot(name, setup, selector) {
    // Scroll to top before any setup action
    scrollToTop();

    if (setup && selector) {
      cy.get('body').then(($body) => {
        if ($body.find(selector).filter(':visible').length === 0) {
          cy.log(`SKIP: "${selector}" not visible — skipping ${name}`);
          return;
        }
        new Function('cy', setup)(cy);
        cy.wait(500);
        // Scroll to top AGAIN after setup — clicks can shift the viewport
        scrollToTop();
        cy.wait(SCREENSHOT_WAIT);
        cy.screenshot(name, { capture: 'viewport', overwrite: true });
      });
    } else if (setup) {
      new Function('cy', setup)(cy);
      cy.wait(500);
      // Scroll to top AGAIN after setup
      scrollToTop();
      cy.wait(SCREENSHOT_WAIT);
      cy.screenshot(name, { capture: 'viewport', overwrite: true });
    } else {
      cy.wait(SCREENSHOT_WAIT);
      cy.screenshot(name, { capture: 'viewport', overwrite: true });
    }
  }

  routes.forEach(({ url, dir, screenshots, resolveFrom, resolveAction }) => {
    screenshots.forEach(({ name, setup, selector, viewport }) => {
      it(`captures ${name}`, () => {
        // Apply per-screenshot viewport override (e.g. tablet for sidenav)
        if (viewport) {
          cy.viewport(viewport.width, viewport.height);
          cy.wait(300);
        }

        if (resolveFrom) {
          // Dynamic resolution: visit list page → click first item → extract ID
          // then navigate IN-APP (no reload) to the target URL.
          cy.visit(`http://localhost:4200${resolveFrom}`, visitOptions);
          cy.wait(PAGE_LOAD_WAIT);
          dismissDialogs();

          cy.get('body').then(($body) => {
            if ($body.find('mat-grid-tile.dino-grid-tile').length === 0) {
              cy.log(`SKIP: No list items on ${resolveFrom} — skipping ${name}`);
              return;
            }

            // Click first tile — Angular router navigates to /forms/{id} or /reports/{id}
            cy.get('mat-grid-tile.dino-grid-tile').first().click();
            cy.wait(1000);

            // Extract the dynamic schema ID from the new URL.
            // Generic: compare navigated URL with resolveFrom prefix to find the ID.
            cy.url().then((navUrl) => {
              const navPath = new URL(navUrl).pathname;
              const afterPrefix = navPath.substring(resolveFrom.length + 1);
              const schemaId = afterPrefix.split('/')[0];
              if (!schemaId) {
                cy.log(`SKIP: Could not extract schema ID from ${navUrl} — skipping ${name}`);
                return;
              }

              if (resolveAction) {
                // Two-step resolution: we're on the data list page (e.g. /forms/{schemaId}).
                // Click a row to select/expand it (reveals action icons on some lists),
                // then click the matching action icon to navigate to the data entry
                // (e.g. /forms/{schemaId}/view/{dataId}).
                cy.get('body').then(($listBody) => {
                  // Check that data rows exist
                  if ($listBody.find('mat-row').length === 0) {
                    cy.log(`SKIP: No data rows on ${navPath} — skipping ${name}`);
                    return;
                  }

                  // Click first row to select/expand — some lists only reveal
                  // action icons after a row is selected (e.g. reports).
                  cy.get('mat-row').first().click();
                  cy.wait(1000);

                  // Click the matching action icon on the first row
                  cy.get('mat-row').first().find('mat-icon.dino-action-icon').then(($icons) => {
                    const target = $icons.filter((_, el) => el.textContent.trim() === resolveAction);
                    if (target.length === 0) {
                      cy.log(`SKIP: No "${resolveAction}" action icon found — skipping ${name}`);
                      return;
                    }
                    cy.wrap(target.first()).click({ force: true });
                    cy.wait(PAGE_LOAD_WAIT);
                    dismissDialogs();
                    captureScreenshot(name, setup, selector);
                  });
                });
              } else {
                const resolvedUrl = url.replace('{schemaId}', schemaId);

                // Only navigate if the resolved URL differs from where we are now.
                // After clicking a tile we may already be at the target (e.g. /forms/{id}).
                // Pushing the same URL via popstate disrupts Angular async pipelines.
                if (navPath !== resolvedUrl) {
                  navigateInApp(resolvedUrl);
                } else {
                  cy.wait(PAGE_LOAD_WAIT);
                }
                dismissDialogs();
                captureScreenshot(name, setup, selector);
              }
            });
          });
        } else {
          // Direct navigation — URL is complete
          cy.visit(`http://localhost:4200${url}`, visitOptions);
          cy.wait(PAGE_LOAD_WAIT);
          dismissDialogs();
          captureScreenshot(name, setup, selector);
        }
      });
    });
  });
});
