load(
    "//tools:defaults.bzl",
    "markdown_to_html",
    "sass_library",
)

package(default_visibility = ["//visibility:public"])

sass_library(
    name = "button_scss_lib",
    srcs = glob(["**/_*.scss"]),
)

markdown_to_html(
    name = "overview",
    srcs = ["button.md"],
)

filegroup(
    name = "source-files",
    srcs = glob(["**/*.ts"]),
)
