export const reportDatas = [
  {
    id: 'b0170e25-5e0b-42a1-a8c1-938fb65bd102',
    user_data_ref_id: 'user_a',
    report_schema_ref_id: 'generic_report',
    name: 'Report',
    metadata: {},
    data: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    area_ref_id: null,
    case_ref_id: null,
    location_ref_id: null,
    organization_ref_id: null,
    project_ref_id: null,
    form_status_ref_id: null,
    is_deleted: false,
    date_start: null,
    date_end: null,
  },
] as any[];
