import {projects} from './test-projects';

const ajfSourceReportFormDatas = [
  {
    age: 31,
    poc: 'opd',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_12',
    va_os: '6_9',
    gender: 'f',
    iop_od: 15,
    iop_os: 18,
    parish: 'Oluvu',
    village: 'Oluvu Central',
    lens_od: 'lens_clear',
    lens_os: 'lens_clear',
    district: 'arua',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: 'n',
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '1001',
    settlement: 'Arua Hill',
    sub_county: 'vurra',
    nationality: 'ugandans',
    diagnosis_od: ['ec08'],
    diagnosis_os: ['ec08'],
    disabilities: null,
    eyes_checked: ['od', 'os'],
    treatment_od: ['spectacle'],
    treatment_os: ['spectacle'],
    conjunctiva_od: 'normal',
    conjunctiva_os: 'normal',
    chief_complaint: 'Blurred vision at distance',
    disability_status: 'n',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  {
    age: 67,
    poc: 'outreach',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_60',
    va_os: '6_36',
    gender: 'm',
    iop_od: 16,
    iop_os: 17,
    parish: 'Pajulu',
    village: 'Pajulu East',
    lens_od: 'lens_cataractous',
    lens_os: 'lens_cataractous',
    district: 'arua',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: null,
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '1002',
    settlement: 'Rhino Camp',
    sub_county: 'omugo_hciv',
    nationality: 'refugees',
    diagnosis_od: ['ec07'],
    diagnosis_os: ['ec06'],
    disabilities: ['ds01'],
    eyes_checked: ['od', 'os'],
    treatment_od: ['other'],
    treatment_os: ['other'],
    conjunctiva_od: 'normal',
    conjunctiva_os: 'normal',
    chief_complaint: 'Progressive loss of vision both eyes',
    disability_status: 'y',
    treatment_other_od: 'Referral for cataract surgery',
    treatment_other_os: 'Referral for cataract surgery',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  {
    age: 8,
    poc: 'ycc',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_6',
    va_os: '6_9',
    gender: 'm',
    iop_od: 12,
    iop_os: 13,
    parish: 'Logiri',
    village: 'Logiri Town',
    lens_od: 'lens_clear',
    lens_os: 'lens_clear',
    district: 'arua',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: null,
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '1003',
    settlement: 'Logiri',
    sub_county: 'logiri',
    nationality: 'ugandans',
    diagnosis_od: ['ec00'],
    diagnosis_os: ['ec08'],
    disabilities: null,
    eyes_checked: ['od', 'os'],
    treatment_od: null,
    treatment_os: ['spectacle'],
    conjunctiva_od: 'normal',
    conjunctiva_os: 'normal',
    chief_complaint: 'Difficulty reading at school',
    disability_status: 'n',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  {
    age: 45,
    poc: 'opd',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_18',
    va_os: '6_12',
    gender: 'f',
    iop_od: 26,
    iop_os: 24,
    parish: 'Manibe',
    village: 'Manibe Central',
    lens_od: 'lens_clear',
    lens_os: 'lens_clear',
    district: 'arua',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: 'n',
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '1004',
    settlement: 'Arua Town',
    sub_county: 'manibe',
    nationality: 'ugandans',
    diagnosis_od: ['ec09'],
    diagnosis_os: ['ec09'],
    disabilities: null,
    eyes_checked: ['od', 'os'],
    treatment_od: ['other'],
    treatment_os: ['other'],
    conjunctiva_od: 'normal',
    conjunctiva_os: 'normal',
    chief_complaint: 'Gradual peripheral vision loss',
    disability_status: 'n',
    treatment_other_od: 'Timolol eye drops',
    treatment_other_os: 'Timolol eye drops',
    anterior_chamber_od: 'anterior_chamber_swallow',
    anterior_chamber_os: 'anterior_chamber_swallow',
  },
  {
    age: 22,
    poc: 'anc',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: null,
    va_os: '6_18',
    gender: 'f',
    iop_os: 14,
    parish: 'Omugo',
    village: 'Omugo Zone 3',
    lens_os: 'lens_clear',
    district: 'arua',
    pupil_os: 'pupil_crrl',
    cornea_os: 'clear',
    fundus_os: 'fundus_normal',
    pregnancy: 'y',
    eye_lid_os: 'normal',
    patient_id: '1005',
    settlement: 'Omugo Extension',
    sub_county: 'omugo_extension',
    nationality: 'refugees',
    diagnosis_os: ['ec01'],
    disabilities: null,
    eyes_checked: ['os'],
    treatment_os: ['other'],
    conjunctiva_os: 'inflamed',
    chief_complaint: 'Red itchy left eye',
    disability_status: 'n',
    treatment_other_os: 'Antihistamine drops',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  {
    age: 55,
    poc: 'outreach',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_24',
    va_os: '6_18',
    gender: 'm',
    iop_od: 19,
    iop_os: 20,
    parish: 'Dadamu',
    village: 'Dadamu West',
    lens_od: 'lens_cataractous',
    lens_os: 'lens_clear',
    district: 'arua',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: null,
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '1006',
    settlement: 'Imvepi',
    sub_county: 'imvepi_settlement',
    nationality: 'refugees',
    diagnosis_od: ['ec06'],
    diagnosis_os: ['ec00'],
    disabilities: null,
    eyes_checked: ['od', 'os'],
    treatment_od: ['spectacle'],
    treatment_os: null,
    conjunctiva_od: 'normal',
    conjunctiva_os: 'normal',
    chief_complaint: 'Difficulty seeing with right eye',
    disability_status: 'n',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  {
    age: 19,
    poc: 'pnc',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_6',
    va_os: '6_6',
    gender: 'f',
    iop_od: 14,
    iop_os: 13,
    parish: 'Arivu',
    village: 'Arivu South',
    lens_od: 'lens_clear',
    lens_os: 'lens_clear',
    district: 'arua',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: 'n',
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '1007',
    settlement: 'Arivu',
    sub_county: 'arivu',
    nationality: 'ugandans',
    diagnosis_od: ['ec00'],
    diagnosis_os: ['ec00'],
    disabilities: null,
    eyes_checked: ['od', 'os'],
    treatment_od: null,
    treatment_os: null,
    conjunctiva_od: 'normal',
    conjunctiva_os: 'normal',
    chief_complaint: 'Routine postnatal eye check',
    disability_status: 'n',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  // --- LAMWO district (6 records) ---
  {
    age: 56,
    poc: 'pnc',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_24',
    va_os: null,
    gender: 'm',
    iop_od: 14,
    parish: 'Padibe Town',
    village: 'Padibe Centre',
    lens_od: 'lens_aphakic',
    district: 'lamwo',
    pupil_od: 'pupil_crrl',
    cornea_od: 'clear',
    fundus_od: 'fundus_normal',
    pregnancy: null,
    eye_lid_od: 'normal',
    patient_id: '2001',
    settlement: 'Padibe',
    sub_county: 'padibe',
    nationality: 'ugandans',
    diagnosis_od: ['ec01'],
    disabilities: ['ds01'],
    eyes_checked: ['od'],
    treatment_od: ['other'],
    conjunctiva_od: 'inflamed',
    chief_complaint: 'Red itchy right eye after surgery',
    disability_status: 'y',
    treatment_other_od: 'Antibiotics',
    anterior_chamber_od: 'anterior_chamber_normal',
  },
  {
    age: 72,
    poc: 'outreach',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_36',
    va_os: '6_60',
    gender: 'f',
    iop_od: 20,
    iop_os: 22,
    parish: 'Palabek',
    village: 'Palabek West',
    lens_od: 'lens_cataractous',
    lens_os: 'lens_cataractous',
    district: 'lamwo',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'opaque',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: null,
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '2002',
    settlement: 'Palabek Settlement',
    sub_county: 'palabek_kal',
    nationality: 'refugees',
    diagnosis_od: ['ec07', 'ec17'],
    diagnosis_os: ['ec07'],
    disabilities: ['ds01'],
    eyes_checked: ['od', 'os'],
    treatment_od: ['other'],
    treatment_os: ['other'],
    conjunctiva_od: 'normal',
    conjunctiva_os: 'normal',
    chief_complaint: 'Cannot see faces clearly',
    disability_status: 'y',
    treatment_other_od: 'Referral for cataract surgery',
    treatment_other_os: 'Referral for cataract surgery',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  {
    age: 35,
    poc: 'opd',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_9',
    va_os: '6_6',
    gender: 'm',
    iop_od: 13,
    iop_os: 14,
    parish: 'Agoro',
    village: 'Agoro Trading Centre',
    lens_od: 'lens_clear',
    lens_os: 'lens_clear',
    district: 'lamwo',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: null,
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '2003',
    settlement: 'Agoro',
    sub_county: 'agoro',
    nationality: 'ugandans',
    diagnosis_od: ['ec12'],
    diagnosis_os: ['ec00'],
    disabilities: null,
    eyes_checked: ['od', 'os'],
    treatment_od: ['other'],
    treatment_os: null,
    conjunctiva_od: 'inflamed',
    conjunctiva_os: 'normal',
    chief_complaint: 'Right eye injured during farming',
    disability_status: 'n',
    treatment_other_od: 'Eye patching and antibiotics',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  {
    age: 28,
    poc: 'mat',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_12',
    va_os: '6_12',
    gender: 'f',
    iop_od: 15,
    iop_os: 16,
    parish: 'Madi Opei',
    village: 'Madi Opei Centre',
    lens_od: 'lens_clear',
    lens_os: 'lens_clear',
    district: 'lamwo',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: 'y',
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '2004',
    settlement: 'Madi Opei',
    sub_county: 'madi_opei',
    nationality: 'ugandans',
    diagnosis_od: ['ec08'],
    diagnosis_os: ['ec08'],
    disabilities: null,
    eyes_checked: ['od', 'os'],
    treatment_od: ['spectacle'],
    treatment_os: ['spectacle'],
    conjunctiva_od: 'normal',
    conjunctiva_os: 'normal',
    chief_complaint: 'Headaches when reading',
    disability_status: 'n',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  {
    age: 63,
    poc: 'opd',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_18',
    va_os: '6_24',
    gender: 'm',
    iop_od: 28,
    iop_os: 30,
    parish: 'Lokung',
    village: 'Lokung East',
    lens_od: 'lens_clear',
    lens_os: 'lens_clear',
    district: 'lamwo',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_bleeding',
    fundus_os: 'fundus_bleeding',
    pregnancy: null,
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '2005',
    settlement: 'Lokung',
    sub_county: 'lokung',
    nationality: 'ugandans',
    diagnosis_od: ['ec09', 'ec13'],
    diagnosis_os: ['ec09', 'ec13'],
    disabilities: ['ds01'],
    eyes_checked: ['od', 'os'],
    treatment_od: ['other'],
    treatment_os: ['other'],
    conjunctiva_od: 'normal',
    conjunctiva_os: 'normal',
    chief_complaint: 'Tunnel vision and diabetes',
    disability_status: 'y',
    treatment_other_od: 'Referral to ophthalmologist',
    treatment_other_os: 'Referral to ophthalmologist',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  {
    age: 40,
    poc: 'outreach',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_9',
    va_os: '6_9',
    gender: 'f',
    iop_od: 14,
    iop_os: 15,
    parish: 'Potika',
    village: 'Potika South',
    lens_od: 'lens_clear',
    lens_os: 'lens_clear',
    district: 'lamwo',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: 'n',
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '2006',
    settlement: 'Potika',
    sub_county: 'potika',
    nationality: 'refugees',
    diagnosis_od: ['ec10'],
    diagnosis_os: ['ec10'],
    disabilities: null,
    eyes_checked: ['od', 'os'],
    treatment_od: ['other'],
    treatment_os: ['other'],
    conjunctiva_od: 'inflamed',
    conjunctiva_os: 'inflamed',
    chief_complaint: 'Recurring eye irritation and discharge',
    disability_status: 'n',
    treatment_other_od: 'Azithromycin',
    treatment_other_os: 'Azithromycin',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  // --- KITGUM district (6 records) ---
  {
    age: 48,
    poc: 'opd',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_12',
    va_os: '6_18',
    gender: 'm',
    iop_od: 16,
    iop_os: 17,
    parish: 'Orom',
    village: 'Orom Centre',
    lens_od: 'lens_clear',
    lens_os: 'lens_cataractous',
    district: 'kitgum',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: null,
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '3001',
    settlement: 'Orom',
    sub_county: 'orom',
    nationality: 'ugandans',
    diagnosis_od: ['ec00'],
    diagnosis_os: ['ec06'],
    disabilities: null,
    eyes_checked: ['od', 'os'],
    treatment_od: null,
    treatment_os: ['other'],
    conjunctiva_od: 'normal',
    conjunctiva_os: 'normal',
    chief_complaint: 'Left eye getting cloudy',
    disability_status: 'n',
    treatment_other_os: 'Monitoring cataract progression',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  {
    age: 12,
    poc: 'ycc',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_6',
    va_os: '6_6',
    gender: 'f',
    iop_od: 12,
    iop_os: 12,
    parish: 'Namokora',
    village: 'Namokora Town',
    lens_od: 'lens_clear',
    lens_os: 'lens_clear',
    district: 'kitgum',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: null,
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '3002',
    settlement: 'Namokora',
    sub_county: 'namokora',
    nationality: 'ugandans',
    diagnosis_od: ['ec02'],
    diagnosis_os: ['ec02'],
    disabilities: null,
    eyes_checked: ['od', 'os'],
    treatment_od: ['other'],
    treatment_os: ['other'],
    conjunctiva_od: 'inflamed',
    conjunctiva_os: 'inflamed',
    chief_complaint: 'Both eyes red with discharge',
    disability_status: 'n',
    treatment_other_od: 'Chloramphenicol drops',
    treatment_other_os: 'Chloramphenicol drops',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  {
    age: 38,
    poc: 'opd',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_6',
    va_os: null,
    gender: 'm',
    iop_od: 14,
    parish: 'Mucwini',
    village: 'Mucwini East',
    lens_od: 'lens_clear',
    district: 'kitgum',
    pupil_od: 'pupil_crrl',
    cornea_od: 'clear',
    fundus_od: 'fundus_normal',
    pregnancy: null,
    eye_lid_od: 'abnormal',
    abnormal_details_eyelid_od: 'Mild ptosis',
    patient_id: '3003',
    settlement: 'Mucwini',
    sub_county: 'mucwini',
    nationality: 'ugandans',
    diagnosis_od: ['ec20'],
    disabilities: null,
    eyes_checked: ['od'],
    treatment_od: ['other'],
    conjunctiva_od: 'normal',
    chief_complaint: 'Drooping right eyelid',
    disability_status: 'n',
    treatment_other_od: 'Referral for ptosis evaluation',
    anterior_chamber_od: 'anterior_chamber_normal',
  },
  {
    age: 75,
    poc: 'outreach',
    cf_od: 'y',
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_60-',
    va_os: '6_36',
    gender: 'f',
    iop_od: 18,
    iop_os: 19,
    parish: 'Lagoro',
    village: 'Lagoro North',
    lens_od: 'lens_cataractous',
    lens_os: 'lens_cataractous',
    district: 'kitgum',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'opaque',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: null,
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '3004',
    settlement: 'Lagoro',
    sub_county: 'lagoro',
    nationality: 'ugandans',
    diagnosis_od: ['ec07', 'ec17'],
    diagnosis_os: ['ec06'],
    disabilities: ['ds01'],
    eyes_checked: ['od', 'os'],
    treatment_od: ['other'],
    treatment_os: ['other'],
    conjunctiva_od: 'normal',
    conjunctiva_os: 'normal',
    chief_complaint: 'Nearly blind in right eye',
    disability_status: 'y',
    treatment_other_od: 'Urgent cataract surgery referral',
    treatment_other_os: 'Follow-up in 6 months',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  {
    age: 60,
    poc: 'opd',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_18',
    va_os: '6_18',
    gender: 'm',
    iop_od: 15,
    iop_os: 16,
    parish: 'Amida',
    village: 'Amida West',
    lens_od: 'lens_phseudophakic',
    lens_os: 'lens_cataractous',
    district: 'kitgum',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: null,
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '3005',
    settlement: 'Kitgum Town',
    sub_county: 'amida',
    nationality: 'ugandans',
    diagnosis_od: ['ec00'],
    diagnosis_os: ['ec07'],
    disabilities: null,
    eyes_checked: ['od', 'os'],
    treatment_od: null,
    treatment_os: ['other'],
    conjunctiva_od: 'normal',
    conjunctiva_os: 'normal',
    chief_complaint: 'Follow-up after right eye cataract surgery, left eye still cloudy',
    disability_status: 'n',
    treatment_other_os: 'Schedule left eye cataract surgery',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  {
    age: 5,
    poc: 'ycc',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_12',
    va_os: '6_12',
    gender: 'm',
    iop_od: 11,
    iop_os: 11,
    parish: 'Kitgum Central',
    village: 'Kitgum Town',
    lens_od: 'lens_clear',
    lens_os: 'lens_clear',
    district: 'kitgum',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: null,
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '3006',
    settlement: 'Kitgum Town',
    sub_county: 'central_division',
    nationality: 'foreigners',
    diagnosis_od: ['ec11'],
    diagnosis_os: ['ec11'],
    disabilities: null,
    eyes_checked: ['od', 'os'],
    treatment_od: ['other'],
    treatment_os: ['other'],
    conjunctiva_od: 'normal',
    conjunctiva_os: 'normal',
    chief_complaint: 'Dry eyes and night blindness',
    disability_status: 'n',
    treatment_other_od: 'Vitamin A supplementation',
    treatment_other_os: 'Vitamin A supplementation',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  // --- AGAGO district (6 records) ---
  {
    age: 50,
    poc: 'opd',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_9',
    va_os: '6_9',
    gender: 'f',
    iop_od: 15,
    iop_os: 14,
    parish: 'Kalongo',
    village: 'Kalongo Town',
    lens_od: 'lens_clear',
    lens_os: 'lens_clear',
    district: 'agago',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_dr',
    fundus_os: 'fundus_dr',
    pregnancy: null,
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '4001',
    settlement: 'Kalongo',
    sub_county: 'kalongo',
    nationality: 'ugandans',
    diagnosis_od: ['ec13'],
    diagnosis_os: ['ec13'],
    disabilities: null,
    eyes_checked: ['od', 'os'],
    treatment_od: ['other'],
    treatment_os: ['other'],
    conjunctiva_od: 'normal',
    conjunctiva_os: 'normal',
    chief_complaint: 'Diabetic patient, routine eye screening',
    disability_status: 'n',
    treatment_other_od: 'Retinal laser referral',
    treatment_other_os: 'Retinal laser referral',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  {
    age: 33,
    poc: 'opd',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: null,
    va_os: '6_24',
    gender: 'm',
    iop_os: 15,
    parish: 'Adilang',
    village: 'Adilang North',
    lens_os: 'lens_clear',
    district: 'agago',
    pupil_os: 'pupil_crrl',
    cornea_os: 'clear',
    fundus_os: 'fundus_normal',
    pregnancy: null,
    eye_lid_os: 'normal',
    patient_id: '4002',
    settlement: 'Adilang',
    sub_county: 'adilang',
    nationality: 'ugandans',
    diagnosis_os: ['ec05'],
    disabilities: null,
    eyes_checked: ['os'],
    treatment_os: ['other'],
    conjunctiva_os: 'inflamed',
    chief_complaint: 'Pain and redness in left eye',
    disability_status: 'n',
    treatment_other_os: 'Antifungal drops and follow-up',
    anterior_chamber_os: 'anterior_chamber_kps',
  },
  {
    age: 42,
    poc: 'outreach',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_12',
    va_os: '6_9',
    gender: 'f',
    iop_od: 14,
    iop_os: 13,
    parish: 'Patongo',
    village: 'Patongo Trading Centre',
    lens_od: 'lens_clear',
    lens_os: 'lens_clear',
    district: 'agago',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: 'n',
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '4003',
    settlement: 'Patongo',
    sub_county: 'patongo',
    nationality: 'ugandans',
    diagnosis_od: ['ec08'],
    diagnosis_os: ['ec08'],
    disabilities: null,
    eyes_checked: ['od', 'os'],
    treatment_od: ['spectacle'],
    treatment_os: ['spectacle'],
    conjunctiva_od: 'normal',
    conjunctiva_os: 'normal',
    chief_complaint: 'Difficulty reading small text',
    disability_status: 'n',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  // Sparse record for realism
  {
    age: 56,
    poc: null,
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: null,
    va_os: null,
    gender: 'm',
    parish: 'Omot',
    district: 'agago',
    pregnancy: null,
    patient_id: '4004',
    settlement: 'Omot',
    sub_county: 'omot',
    nationality: 'ugandans',
    diagnosis_od: null,
    diagnosis_os: null,
    disabilities: null,
    eyes_checked: null,
    treatment_od: null,
    treatment_os: null,
    disability_status: 'n',
  },
  {
    age: 25,
    poc: 'opd',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_6',
    va_os: '6_6',
    gender: 'm',
    iop_od: 13,
    iop_os: 13,
    parish: 'Paimol',
    village: 'Paimol Centre',
    lens_od: 'lens_clear',
    lens_os: 'lens_clear',
    district: 'agago',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_irregular',
    pupil_os_irregular: 'Posterior synechiae',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: null,
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '4005',
    settlement: 'Paimol',
    sub_county: 'paimol',
    nationality: 'ugandans',
    diagnosis_od: ['ec00'],
    diagnosis_os: ['ec15'],
    disabilities: null,
    eyes_checked: ['od', 'os'],
    treatment_od: null,
    treatment_os: ['other'],
    conjunctiva_od: 'normal',
    conjunctiva_os: 'inflamed',
    chief_complaint: 'Left eye pain and sensitivity to light',
    disability_status: 'n',
    treatment_other_os: 'Steroid drops and cycloplegic',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_cell_flare',
  },
  {
    age: 70,
    poc: 'outreach',
    cf_od: null,
    cf_os: 'y',
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_24',
    va_os: '6_60-',
    gender: 'f',
    iop_od: 16,
    iop_os: 17,
    parish: 'Wol',
    village: 'Wol Village',
    lens_od: 'lens_cataractous',
    lens_os: 'lens_cataractous',
    district: 'agago',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'opaque',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: null,
    eye_lid_od: 'normal',
    eye_lid_os: 'abnormal',
    abnormal_details_eyelid_os: 'Entropion with trichiasis',
    patient_id: '4006',
    settlement: 'Wol',
    sub_county: 'wol',
    nationality: 'ugandans',
    diagnosis_od: ['ec06'],
    diagnosis_os: ['ec07', 'ec10'],
    disabilities: ['ds01'],
    eyes_checked: ['od', 'os'],
    treatment_od: ['spectacle'],
    treatment_os: ['other'],
    conjunctiva_od: 'normal',
    conjunctiva_os: 'inflamed',
    chief_complaint: 'Left eye very poor vision with eyelash irritation',
    disability_status: 'y',
    treatment_other_os: 'Surgery referral for trichiasis and cataract',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  // --- PADER district (5 records) ---
  {
    age: 29,
    poc: 'anc',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_9',
    va_os: '6_9',
    gender: 'f',
    iop_od: 14,
    iop_os: 14,
    parish: 'Pajule',
    village: 'Pajule Town',
    lens_od: 'lens_clear',
    lens_os: 'lens_clear',
    district: 'pader',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: 'y',
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '5001',
    settlement: 'Pajule',
    sub_county: 'pajule',
    nationality: 'ugandans',
    diagnosis_od: ['ec01'],
    diagnosis_os: ['ec01'],
    disabilities: null,
    eyes_checked: ['od', 'os'],
    treatment_od: ['other'],
    treatment_os: ['other'],
    conjunctiva_od: 'inflamed',
    conjunctiva_os: 'inflamed',
    chief_complaint: 'Itchy watery eyes during pregnancy',
    disability_status: 'n',
    treatment_other_od: 'Pregnancy-safe antihistamine drops',
    treatment_other_os: 'Pregnancy-safe antihistamine drops',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  {
    age: 80,
    poc: 'outreach',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_60',
    va_os: '6_60',
    gender: 'm',
    iop_od: 17,
    iop_os: 18,
    parish: 'Acholibur',
    village: 'Acholibur Centre',
    lens_od: 'lens_cataractous',
    lens_os: 'lens_cataractous',
    district: 'pader',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: null,
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '5002',
    settlement: 'Pader Town',
    sub_county: 'acholibur',
    nationality: 'ugandans',
    diagnosis_od: ['ec07'],
    diagnosis_os: ['ec07'],
    disabilities: ['ds01', 'ds05'],
    eyes_checked: ['od', 'os'],
    treatment_od: ['other'],
    treatment_os: ['other'],
    conjunctiva_od: 'normal',
    conjunctiva_os: 'normal',
    chief_complaint: 'Very poor vision in both eyes for years',
    disability_status: 'y',
    treatment_other_od: 'Urgent cataract surgery referral',
    treatment_other_os: 'Urgent cataract surgery referral',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  {
    age: 15,
    poc: 'opd',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_12',
    va_os: '6_9',
    gender: 'f',
    iop_od: 13,
    iop_os: 12,
    parish: 'Atanga',
    village: 'Atanga Village',
    lens_od: 'lens_clear',
    lens_os: 'lens_clear',
    district: 'pader',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: null,
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '5003',
    settlement: 'Atanga',
    sub_county: 'atanga',
    nationality: 'refugees',
    diagnosis_od: ['ec08'],
    diagnosis_os: ['ec08'],
    disabilities: null,
    eyes_checked: ['od', 'os'],
    treatment_od: ['spectacle'],
    treatment_os: ['spectacle'],
    conjunctiva_od: 'normal',
    conjunctiva_os: 'normal',
    chief_complaint: 'Cannot see the blackboard at school',
    disability_status: 'n',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
  // Another sparse record
  {
    age: 44,
    poc: 'opd',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: null,
    va_os: null,
    gender: 'f',
    parish: 'Laguti',
    district: 'pader',
    pregnancy: 'n',
    patient_id: '5004',
    settlement: 'Pader',
    sub_county: 'laguti',
    nationality: 'ugandans',
    diagnosis_od: null,
    diagnosis_os: null,
    disabilities: null,
    eyes_checked: null,
    treatment_od: null,
    treatment_os: null,
    chief_complaint: 'General eye check',
    disability_status: 'n',
  },
  {
    age: 58,
    poc: 'opd',
    cf_od: null,
    cf_os: null,
    hm_od: null,
    hm_os: null,
    lp_od: null,
    lp_os: null,
    va_od: '6_18',
    va_os: '6_12',
    gender: 'm',
    iop_od: 16,
    iop_os: 15,
    parish: 'Awere',
    village: 'Awere South',
    lens_od: 'lens_clear',
    lens_os: 'lens_clear',
    district: 'pader',
    pupil_od: 'pupil_crrl',
    pupil_os: 'pupil_crrl',
    cornea_od: 'clear',
    cornea_os: 'clear',
    fundus_od: 'fundus_normal',
    fundus_os: 'fundus_normal',
    pregnancy: null,
    eye_lid_od: 'normal',
    eye_lid_os: 'normal',
    patient_id: '5005',
    settlement: 'Awere',
    sub_county: 'awere',
    nationality: 'ugandans',
    diagnosis_od: ['ec04', 'ec25'],
    diagnosis_os: ['ec00'],
    disabilities: null,
    eyes_checked: ['od', 'os'],
    treatment_od: ['other'],
    treatment_os: null,
    conjunctiva_od: 'inflamed',
    conjunctiva_os: 'normal',
    chief_complaint: 'Right eye red and irritated for two weeks',
    disability_status: 'n',
    treatment_other_od: 'Lubricant drops and review',
    anterior_chamber_od: 'anterior_chamber_normal',
    anterior_chamber_os: 'anterior_chamber_normal',
  },
];


export const formDatas = ajfSourceReportFormDatas.map(data => ({
  user_data_ref_id: null,
  form_schema_ref_id: '2268d23a-af59-4410-bc7e-a110badd4cd4',
  data,
  area_ref_id: null,
  case_ref_id: null,
  location_ref_id: null,
  organization_ref_id: null,
  project_ref_id: projects[0].id,
  form_status_ref_id: null,
  is_deleted: false,
})) as any[];
