import {UserGroup} from '@dino/core/users';
import {InsertModel} from '@dino/core/data';

export const userGroups: InsertModel<UserGroup>[] = [
  {
    created_at: '2025-06-01T08:00:00.000Z',
    groupName: 'admin',
    user_role_ref_id: 'admin',
    area_ref_id: ['all'],
    case_ref_id: ['all'],
    location_ref_id: ['all'],
    organization_ref_id: ['all'],
    project_ref_id: ['all'],
    form_status_ref_id: ['all'],
    groupFormSchemaIds: ['all'],
    groupReportSchemaIds: ['all'],
  },
  {
    created_at: '2025-07-15T10:30:00.000Z',
    groupName: 'metric_location-group',
    user_role_ref_id: 'editor',
    area_ref_id: ['all'],
    case_ref_id: [],
    location_ref_id: ['all'],
    organization_ref_id: [],
    project_ref_id: ['all'],
    form_status_ref_id: ['all'],
    groupFormSchemaIds: ['all'],
    groupReportSchemaIds: ['all'],
  },
  {
    created_at: '2025-08-10T14:00:00.000Z',
    groupName: 'field-data-collectors',
    user_role_ref_id: 'editor',
    area_ref_id: [],
    case_ref_id: [],
    location_ref_id: ['all'],
    organization_ref_id: [],
    project_ref_id: ['all'],
    form_status_ref_id: ['draft', 'submitted'],
    groupFormSchemaIds: ['all'],
    groupReportSchemaIds: [],
  },
  {
    created_at: '2025-09-20T09:45:00.000Z',
    groupName: 'report-viewers',
    user_role_ref_id: 'viewer',
    area_ref_id: ['all'],
    case_ref_id: ['all'],
    location_ref_id: ['all'],
    organization_ref_id: ['all'],
    project_ref_id: ['all'],
    form_status_ref_id: ['all'],
    groupFormSchemaIds: [],
    groupReportSchemaIds: ['all'],
  },
];
