/**
 * Represents the type of the data generated by method 'generateEmptyExampleData'
 * in FormSchemaManager
 */
export type FormSchemaExampleData = {
  /**
   * The example data output, with field name and field type
   */
  fieldTypes: {[key: string]: string};
  /**
   * The fields Labels
   */
  fieldLabels: {[key: string]: string};
  /**
   * The field description, with field name and field description
   */
  fieldDescriptions: {[key: string]: string | null | undefined};
};
