INHERIT: ../../mkdocs.base.yml
site_name: Documentation Dinoapp
site_url: https://gnucoop.github.io/docs.dinoapp.io/fr/
docs_dir: ../../docs/fr
site_dir: ../../site/fr
theme:
  name: material
  language: fr
nav:
  - Accueil: index.md
  - Démarrage:
    - Connexion: getting-started/login.md
    - Réinitialiser le Mot de Passe: getting-started/reset-password.md
  - Interface et Navigation: interface/index.md
  - Tableau de Bord: dashboard/index.md
  - Formulaires:
    - Aperçu: forms/index.md
    - Modifier le schéma du formulaire: forms/edit-form-schema.md
    - Modifier une formulaire: forms/edit-form.md
    - Carte des formulaires: forms/forms-map.md
    - Datachat: forms/datachat.md
  - Rapports:
    - Aperçu: reports/index.md
    - Modifier le schéma de rapport: reports/edit-report-schema.md
    - Modifier un rapport: reports/edit-report.md
  - Métriques:
    - Aperçu: metrics/index.md
    - Domaines thématiques: metrics/areas.md
  - Agrégation: aggregation/index.md
  - Notifications: notifications/index.md
  - Formulaires Publics: public-forms/index.md
  - Administration:
    - Gérer les Utilisateurs et Groupes: administration/users.md
    - Gérer les Langues: administration/languages.md
    - Liste des Utilisateurs: administration/users-list.md
    - Liste des groupes: administration/groups-list.md
