/**
 * docs-screenshots.cy.js
 *
 * Cypress spec that visits each route from the route map and captures
 * screenshots for documentation. Screenshots are saved to docs/imgs/.
 *
 * The route map is generated by scripts/docs-route-scanner.mjs and stored
 * at scripts/docs-route-map.json.
 *
 * Run manually:
 *   yarn cypress run --spec "cypress/e2e/docs-screenshots.cy.js" --headless --browser chrome
 */

import routes from '../../scripts/docs-route-map.json';

describe('Documentation Screenshots', () => {
  // Increase timeout for app loading
  const PAGE_LOAD_WAIT = 3000;
  const SCREENSHOT_WAIT = 600;

  routes.forEach(({ url, dir, screenshots }) => {
    screenshots.forEach(({ name, setup }) => {
      it(`captures ${name}`, () => {
        cy.visit(`http://localhost:4200${url}`, { failOnStatusCode: false });
        cy.wait(PAGE_LOAD_WAIT);

        // Dismiss any tutorial or welcome dialogs
        cy.get('body').then(($body) => {
          if ($body.find('mat-dialog-container').length) {
            cy.get('mat-dialog-container button').last().click();
            cy.wait(500);
          }
        });

        // Execute any custom setup steps (e.g. clicking UI elements)
        if (setup) {
          // setup is a string like "cy.get('[expandable]').first().click()"
          // evaluated in the Cypress context
          new Function('cy', setup)(cy);
          cy.wait(500);
        }

        cy.wait(SCREENSHOT_WAIT);
        cy.screenshot(name, {
          capture: 'viewport',
          overwrite: true,
        });
      });
    });
  });
});
