load(
    "//tools:defaults.bzl",
    "markdown_to_html",
    "ng_module",
)

package(default_visibility = ["//visibility:public"])

ng_module(
    name = "breakpoint-observer",
    srcs = glob(
        ["**/*.ts"],
        exclude = ["**/*.spec.ts"],
    ),
    assets = [],
    module_name = "@dewco/material/breakpoint-observer",
    deps = [
        "@npm//@angular/cdk",
        "@npm//@angular/common",
        "@npm//@angular/core",
        "@npm//rxjs",
    ],
)

markdown_to_html(
    name = "overview",
    srcs = ["breakpoint-observer.md"],
)

filegroup(
    name = "source-files",
    srcs = glob(["**/*.ts"]),
)
