load("//src/e2e-app:test_suite.bzl", "e2e_test_suite")
load(
    "//tools:defaults.bzl",
    "markdown_to_html",
    "ng_e2e_test_library",
    "ng_module",
    "ng_test_library",
    "sass_binary",
    "sass_library",
)

package(default_visibility = ["//visibility:public"])

ng_module(
    name = "login",
    srcs = glob(
        ["**/*.ts"],
        exclude = ["**/*.spec.ts"],
    ),
    assets = [":login.css"] + glob(["**/*.html"]),
    module_name = "@dewco/material/login",
    deps = [
        "//src/core/auth",
        "@npm//@angular/common",
        "@npm//@angular/forms",
        "@npm//@angular/material",
        "@npm//@angular/router",
    ],
)

sass_library(
    name = "login_scss_lib",
    srcs = glob(["**/_*.scss"]),
)

sass_binary(
    name = "login_scss",
    src = "login.scss",
    deps = [],
)

ng_test_library(
    name = "unit_test_sources",
    srcs = glob(
        ["**/*.spec.ts"],
        exclude = ["**/*.e2e.spec.ts"],
    ),
    deps = [
        ":login",
    ],
)

ng_e2e_test_library(
    name = "e2e_test_sources",
    srcs = glob(["**/*.e2e.spec.ts"]),
)

e2e_test_suite(
    name = "e2e_tests",
    deps = [
        ":e2e_test_sources",
    ],
)

markdown_to_html(
    name = "overview",
    srcs = ["login.md"],
)

filegroup(
    name = "source-files",
    srcs = glob(["**/*.ts"]),
)
