INHERIT: ../../mkdocs.base.yml
site_name: Documentación Dinoapp
site_url: https://gnucoop.github.io/dino/es/
docs_dir: ../../docs/es
site_dir: ../../site/es
theme:
  name: material
  language: es
nav:
  - Inicio: index.md
  - Primeros Pasos:
    - Iniciar Sesión: getting-started/login.md
    - Restablecer la Contraseña: getting-started/reset-password.md
  - Interfaz y Navegación: interface/index.md
  - Panel: dashboard/index.md
  - Formularios:
    - Descripción General: forms/index.md
    - Editar esquema de formulario: forms/edit-form-schema.md
    - Editar un formulario: forms/edit-form.md
    - Importar datos: forms/import.md
    - Mapa de Formularios: forms/forms-map.md
    - Datachat: forms/datachat.md
  - Informes:
    - Descripción General: reports/index.md
    - Editar Esquema de Informe: reports/edit-report-schema.md
    - Editar Informe: reports/edit-report.md
  - Métricas:
    - Descripción General: metrics/index.md
    - Áreas temáticas: metrics/areas.md
    - Casos: metrics/cases.md
    - Ubicaciones: metrics/locations.md
    - Organizaciones: metrics/organizations.md
    - Proyectos: metrics/projects.md
  - Agregación: aggregation/index.md
  - Notificaciones: notifications/index.md
  - Formularios Públicos: public-forms/index.md
  - Administración:
    - Gestionar Usuarios y Grupos: administration/users.md
    - Gestionar Idiomas: administration/languages.md
    - Lista de Usuarios: administration/users-list.md
    - Lista de grupos: administration/groups-list.md
