/**
 * @license
 * Copyright (C) Gnucoop soc. coop.
 *
 * This file is part of the Dino (dino).
 *
 * Dino (dino) is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Dino (dino) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
 * General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Dino (dino).
 * If not, see http://www.gnu.org/licenses/.
 *
 */

import {
  AjfChoicesOrigin,
  AjfFieldType,
  AjfForm,
  AjfFormRenderer as AjfCoreFormRenderer,
  AjfFormRendererService,
  AjfFormSerializer,
  AjfNode,
  AjfNodeType,
  AjfSlide,
} from '@ajf/core/forms';
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  EventEmitter,
  Input,
  OnDestroy,
  OnInit,
  Output,
  ViewEncapsulation,
} from '@angular/core';
import {MatButtonToggleChange} from '@angular/material/button-toggle';
import {
  CHOICES_CONDITION_OPERATORS,
  DEFAULT_OPERATORS,
  FilterItem,
  FiltersService,
  NUMBER_CONDITION_OPERATORS,
  Operator,
  TEXT_CONDITION_OPERATORS,
  WidgetData,
} from '@dino/core/list';
import {format} from 'date-fns';
import {BehaviorSubject, combineLatest, Observable, of as obsOf, Subscription} from 'rxjs';
import {debounceTime, map, switchMap, take, tap, withLatestFrom} from 'rxjs/operators';

/**
 * Widget component containing a single filter, generated by a _WidgetData object.
 * Renders an AjfForm with a field and updates the filters list with the field value
 * via FiltersService.
 *
 * It can be displayed or hidden, depending on the state of its visibility conditions.
 * (eg. It could be hidden if another widget's field value doesn't match its visibility conditions)
 */
@Component({
  selector: 'dino-search-filters-widget',
  templateUrl: 'search-filters-widget.html',
  styleUrls: ['search-filters-widget.scss'],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [AjfFormRendererService],
})
export class SearchFiltersWidget extends AjfCoreFormRenderer implements OnInit, OnDestroy {
  /**
   * The filterItem used to generate the AjfForm, and the widgetData
   */
  @Input() filterItemData?: FilterItem;

  /**
   * Event emitted when the the widget filterItem must be added to the temporary filters
   */
  @Output() readonly addFilter: EventEmitter<FilterItem> = new EventEmitter<FilterItem>();

  /**
   * Event emitted when the "create filter" button is clicked
   */
  private _createFilter: EventEmitter<void> = new EventEmitter<void>();

  /**
   * If true, the "create filter" button is disabled
   */
  isCreateFilterButtonDisabled: Observable<boolean> = obsOf(true);

  /**
   * A _widgetData object containing all data relative to the widget.
   */
  private _widgetData?: WidgetData;

  get widgetData(): WidgetData | undefined {
    return this._widgetData;
  }

  /**
   * The value changes of the widget's AjfForm
   */
  private _formValueChanges: Observable<{[key: string]: any}> = obsOf({});

  /**
   * Subscribes to the widget's value and operator changes
   * to create a filter, after validating it via
   * the FiltersService.
   */
  private _createFilterSub: Subscription = Subscription.EMPTY;

  /**
   * State of the filter validation
   */
  private _validation: Observable<boolean> = obsOf(false);
  get validation(): Observable<boolean> {
    return this._validation;
  }

  /**
   * Widget Name identifier
   */
  private _widgetName: string = '';
  get widgetName(): string {
    return this._widgetName;
  }

  /**
   * Label displayed on the Widget
   */
  private _widgetLabel: string = '';
  get widgetLabel(): string {
    return this._widgetLabel;
  }

  /**
   * Operator value of the widget
   */
  private _operatorValue: BehaviorSubject<Operator> = new BehaviorSubject<Operator>({
    label: 'Includes',
    value: '$regex',
  });
  get operatorValue(): BehaviorSubject<Operator> {
    return this._operatorValue;
  }

  constructor(
    public rendererService: AjfFormRendererService,
    changeDetectorRef: ChangeDetectorRef,
    private _fs: FiltersService,
  ) {
    super(rendererService, changeDetectorRef);
  }

  ngOnInit() {
    if (this.filterItemData != null) {
      this._widgetData = this._setupWidget(this.filterItemData);
      this._operatorValue.next(this._widgetData.operator);
    }

    this._formValueChanges = this.formGroup.pipe(
      switchMap(fg => (fg ? fg.valueChanges : obsOf(null))),
    );

    this._validation = combineLatest([this._formValueChanges, this.operatorValue]).pipe(
      map(([formValue, operatorValue]) => {
        if (!formValue) {
          return false;
        }
        delete formValue['$value'];
        delete formValue['$nodesInitialised'];
        if (this.filterItemData == null || this.widgetData == null) {
          return false;
        }
        let isValid = true;
        if (this.widgetData.validationConditions) {
          const fid = this.filterItemData;
          const formKeys = Object.keys(formValue);
          for (let key of formKeys) {
            fid.value = formValue[key];
            fid.operator = operatorValue;
            if (!this._fs.checkValidation(fid, this.widgetData?.validationConditions)) {
              isValid = false;
              break;
            }
          }
        }
        return isValid;
      }),
    );

    this.isCreateFilterButtonDisabled = this._validation.pipe(
      map(validation => {
        if (!validation) {
          return true;
        }
        const formValue = this.getWidgetFormValue();
        let isDisabled = true;
        if (!Object.keys(formValue).length) {
          return isDisabled;
        }
        for (let key in formValue) {
          if (formValue[key] !== null && formValue[key] !== '') {
            isDisabled = false;
            break;
          }
        }
        return isDisabled;
      }),
    );

    this._createFilterSub = this._createFilter
      .pipe(debounceTime(300), withLatestFrom(this._formValueChanges))
      .subscribe(([_, formValue]) => {
        if (!formValue) {
          return;
        }
        delete formValue['$value'];
        delete formValue['$nodesInitialised'];
        const {filterItemData, widgetData} = this;
        if (filterItemData == null || widgetData == null) {
          return;
        }
        Object.keys(formValue).forEach(key => {
          if (
            formValue[key] &&
            typeof formValue[key] === 'object' &&
            filterItemData.fieldType === AjfFieldType.DateInput
          ) {
            filterItemData.value = format(new Date(formValue[key]), 'yyyy-MM-dd');
          } else {
            filterItemData.value = formValue[key];
          }
          filterItemData.operator = this._operatorValue.getValue();
          filterItemData.isValid = true;
        });
        if (filterItemData.value != null) {
          widgetData.active = true;
          this.addFilter.emit({...filterItemData});
          this._resetWidgetValue();
        }
      });
  }

  /**
   * Emits the event that creates a new filter.
   */
  createFilter(): void {
    this._createFilter.emit();
  }

  /**
   * Transforms a FilterItem into a WidgetData object.
   * It creates an AjfForm from the passed FilterItem, then
   * assigns it to the _WidgetData object.
   * @param filterItem The filter item to transform
   * @returns The _WidgetData object
   */
  private _setupWidget(filterItem: FilterItem): WidgetData {
    filterItem.editable = true;
    let isFormulaField = false;
    if (filterItem.fieldType == AjfFieldType.Formula) {
      filterItem.fieldType = AjfFieldType.Number;
      isFormulaField = true;
    }
    const fieldChoices: AjfChoicesOrigin<any>[] = filterItem.choicesOrigin
      ? [filterItem.choicesOrigin]
      : [];
    filterItem.operator = DEFAULT_OPERATORS[filterItem.fieldType ?? AjfFieldType.String];
    const formSchema: Partial<AjfForm> = {
      choicesOrigins: fieldChoices,
      nodes: [
        {
          parent: 0,
          parentNode: 0,
          id: 1,
          name: filterItem.name,
          label: filterItem.label,
          nodeType: AjfNodeType.AjfSlide,
          nodes: [filterItem as Partial<AjfNode>],
        } as AjfSlide,
      ],
    };
    const ctx = Object.create({});
    const form = AjfFormSerializer.fromJson(formSchema, ctx);

    this.form = form;
    this._widgetName = filterItem.name;
    this._widgetLabel = filterItem.label ?? '';

    return {
      form: form,
      operator: filterItem.operator,
      active: false,
      validationConditions: undefined,
      isFormula: isFormulaField,
    };
  }

  /**
   * Sets the filter operator value to the one chosen in the MatButtonToggleGroup of the operators
   * @param operator The filter operator value
   */
  changeOperator(operator: MatButtonToggleChange) {
    this.operatorValue.next(operator.value as Operator);
  }

  /**
   * Returns the right array of operators associated with the filter type
   * @param type The type of the AjfField
   * @returns The operators
   */
  conditionOperatorByFieldType(type: AjfFieldType): Operator[] {
    switch (type) {
      case AjfFieldType.Number:
      case AjfFieldType.Date:
      case AjfFieldType.DateInput:
        return NUMBER_CONDITION_OPERATORS;
      case AjfFieldType.MultipleChoice:
        return CHOICES_CONDITION_OPERATORS;
      case AjfFieldType.String:
      case AjfFieldType.Text:
        return TEXT_CONDITION_OPERATORS;
      default:
        return [];
    }
  }

  /**
   * Retrieves the widget ajfform value
   * @returns The widget form value
   */
  getWidgetFormValue(): {[key: string]: unknown} {
    return this.rendererService.getFormValue();
  }

  /**
   * Resets the widget value and operator to default
   */
  private _resetWidgetValue(): void {
    this.formGroup
      .pipe(
        tap(fg => {
          if (fg) {
            for (let key in fg.controls) {
              fg.controls[key].setValue(null);
            }
          }
          this._operatorValue.next(
            DEFAULT_OPERATORS[this.filterItemData?.fieldType ?? AjfFieldType.String],
          );
        }),
        take(1),
      )
      .subscribe();
  }

  override ngOnDestroy() {
    super.ngOnDestroy();
    this._createFilterSub.unsubscribe();

    this.addFilter.complete();
    this._operatorValue.complete();
  }
}
