/**
 * @license
 * Copyright (C) Gnucoop soc. coop.
 *
 * This file is part of the Dewco (dewco).
 *
 * Dewco (dewco) is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Dewco (dewco) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
 * General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Dewco (dewco).
 * If not, see http://www.gnu.org/licenses/.
 *
 */

import {
  AjfFieldType,
  AjfFormRenderer as AjfCoreFormRenderer,
  AjfFormRendererService,
} from '@ajf/core/forms';
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  EventEmitter,
  Input,
  OnDestroy,
  OnInit,
  Output,
  ViewChild,
  ViewEncapsulation,
} from '@angular/core';
import {MatButtonToggleChange} from '@angular/material/button-toggle';
import {MatSlideToggle, MatSlideToggleChange} from '@angular/material/slide-toggle';
import {
  CHOICES_CONDITION_OPERATORS,
  FilterItem,
  FiltersService,
  NUMBER_CONDITION_OPERATORS,
  Operator,
  WidgetData,
} from '@dewco/core/list';
import {
  BehaviorSubject,
  combineLatest,
  Observable,
  of as obsOf,
  Subscription,
} from 'rxjs';
import {debounceTime, switchMap, tap} from 'rxjs/operators';

/**
 * Widget component containing a single filter, generated by a WidgetData object
 */
@Component({
  selector: 'dewco-mat-searchfilters-widget',
  templateUrl: 'search-filters-widget.html',
  styleUrls: ['search-filters-widget.scss'],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [AjfFormRendererService],
})
export class SearchFiltersWidget extends AjfCoreFormRenderer implements AfterViewInit, OnInit,
                                                                        OnDestroy {
  @Input() widgetData: WidgetData;

  @Output() includeFilter: EventEmitter<FilterItem> = new EventEmitter<FilterItem>();
  @Output() excludeFilter: EventEmitter<FilterItem> = new EventEmitter<FilterItem>();

  /**
   * Slide toggle to include/exclude filter
   */
  @ViewChild('toggleFilter') toggleButton: MatSlideToggle;

  /**
   * AjfForm value changes
   */
  private _formValueChanges: Observable<{[key: string]: any}>;
  /**
   * State of the matSlideToggle
   */
  private _matToggleValue: BehaviorSubject<boolean>;
  private _toggleSub: Subscription = Subscription.EMPTY;
  private _changeFiltersSub: Subscription = Subscription.EMPTY;
  private _widgetVisibilitySub: Subscription = Subscription.EMPTY;
  /**
   * State of the filter validation
   */
  private _validation: boolean;

  /**
   * State of the Widget visibility
   */
  private _widgetVisibility: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(true);
  get widgetVisibility(): BehaviorSubject<boolean> {
    return this._widgetVisibility;
  }

  /**
   * Widget Name identifier
   */
  private _widgetName: string;
  get widgetName(): string {
    return this._widgetName;
  }

  /**
   * Label displayed on the Widget
   */
  private _widgetLabel: string;
  get widgetLabel(): string {
    return this._widgetLabel;
  }

  /**
   * Operator value of the widget
   */
  private _operatorValue: BehaviorSubject<Operator>;
  get operatorValue(): BehaviorSubject<Operator> {
    return this._operatorValue;
  }

  constructor(
      public rendererService: AjfFormRendererService,
      changeDetectorRef: ChangeDetectorRef,
      private _fs: FiltersService,
  ) {
    super(rendererService, changeDetectorRef);
  }


  ngOnInit() {
    this.form = this.widgetData.form;
    this._widgetName = this.widgetData.form.nodes[0].name;
    this._widgetLabel = this.widgetData.form.nodes[0].label;
    this._operatorValue = new BehaviorSubject<Operator>(this.widgetData.operator);
    this._matToggleValue = new BehaviorSubject<boolean>(this.widgetData.active);

    /**
     * Determines the state of the widget's visibility
     */
    const visibilityCondition = this.widgetData.form.nodes[0].visibility;
    if (visibilityCondition != null && visibilityCondition.condition != 'true') {
      this._widgetVisibilitySub = this._fs.temporaryFilters.subscribe(_ => {
        const conditionVerified = this._fs.checkCondition(visibilityCondition);
        if (conditionVerified !== this._widgetVisibility.value) {
          this._widgetVisibility.next(conditionVerified);
        }
      });
    }

    this._formValueChanges = this.formGroup.pipe(
        switchMap(fg => fg ? fg.valueChanges : obsOf(null)),
    );

    /**
     * Listens to the widget's value, toggle and operator changes, to include or exclude filters
     */
    this._changeFiltersSub =
        combineLatest([
          this._formValueChanges, this._matToggleValue.asObservable(),
          this.operatorValue.asObservable(), this._widgetVisibility
        ])
            .pipe(
                debounceTime(300),
                )
            .subscribe(([formValue, toggleValue, operatorValue, visibility]) => {
              if (!formValue) {
                return;
              }
              const filterItem: FilterItem = {name: ''};
              delete formValue.$value;
              Object.keys(formValue).forEach(key => {
                filterItem.name = key;
                filterItem.value = formValue[key];
                filterItem.operator = operatorValue;
                filterItem.label = this._widgetLabel;
                filterItem.isFormData = this.widgetData.isFormData;
                this._validation = this._fs.checkValidation(filterItem, this.widgetData.validation);
                filterItem.isValid = this._validation;
              });
              if (toggleValue && filterItem.value != null && visibility) {
                this.widgetData.active = true;
                this.includeFilter.emit(filterItem);
              } else if ((!toggleValue || !visibility) && this.widgetData.active) {
                this.widgetData.active = false;
                this.excludeFilter.emit(filterItem);
              }
            });
  }

  ngAfterViewInit() {
    super.ngAfterViewInit();
    this._toggleSub = this._formValueChanges.subscribe(formValue => {
      if (this.toggleButton && formValue != null && !this.toggleButton.checked) {
        this.toggleButton.toggle();
        this._matToggleValue.next(true);
      }
    });
  }

  /**
   * Sets the checked state of the MatSlideToggle
   * @param {MatSlideToggleChange} toggle
   */
  filterToggle(toggle: MatSlideToggleChange) {
    this._matToggleValue.next(toggle.checked);
  }

  /**
   * Sets the filter operator value to the one chosen in the MatButtonToggleGroup of the operators
   * @param {MatButtonToggleChange} operator
   */
  changeOperator(operator: MatButtonToggleChange) {
    this.operatorValue.next(operator.value as Operator);
  }

  /**
   * Returns the right array of operators associated with the filter type
   * @param {AjfFieldType} type
   * @returns {Operator[]}
   */
  conditionOperatorByFieldType(type: AjfFieldType): Operator[] {
    switch (type) {
      case AjfFieldType.Number:
      case AjfFieldType.DateInput:
        return NUMBER_CONDITION_OPERATORS;
      case AjfFieldType.MultipleChoice:
        return CHOICES_CONDITION_OPERATORS;
      default:
        return [];
    }
  }

  /**
   * Checks and returns the widget slide toggle button disabled state
   * @param {any} obj
   * @param {MatSlideToggle} element
   * @param {boolean} forceToggle?
   * @returns {boolean}
   */
  checkToggleDisabled(obj: any, element: MatSlideToggle, forceToggle?: boolean): boolean {
    if (!this._widgetVisibility.value || !this._validation) {
      return true;
    }
    for (let key in obj) {
      if (obj[key] !== null && obj[key] !== '' && !forceToggle) {
        return false;
      }
    }
    if ((element && element.checked) || forceToggle) {
      element.toggle();
      this._matToggleValue.next(false);
      element.setDisabledState(true);
    }
    return true;
  }

  /**
   * Retrieves the widget ajfform value
   * @returns {any}
   */
  getWidgetFormValue(): any {
    return this.rendererService.getFormValue();
  }

  ngOnDestroy() {
    super.ngOnDestroy();
    this._changeFiltersSub.unsubscribe();
    this._toggleSub.unsubscribe();
    this._widgetVisibilitySub.unsubscribe();

    this.includeFilter.complete();
    this.excludeFilter.complete();
    this._matToggleValue.complete();
    this.operatorValue.complete();
    this._widgetVisibility.complete();
  }
}
