load(
    "//tools:defaults.bzl",
    "markdown_to_html",
    "ng_module",
)

package(default_visibility = ["//visibility:public"])

ng_module(
    name = "error-handler",
    srcs = glob(
        ["**/*.ts"],
        exclude = ["**/*.spec.ts"],
    ),
    assets = [],
    module_name = "@dewco/core/error-handler",
    deps = [
        "@npm//@angular/common",
        "@npm//@angular/core",
        "@npm//@angular/router",
    ],
)

markdown_to_html(
    name = "overview",
    srcs = ["error-handler.md"],
)

filegroup(
    name = "source-files",
    srcs = glob(["**/*.ts"]),
)
