INHERIT: ../../mkdocs.base.yml
site_name: Documentação Dinoapp
site_url: https://gnucoop.github.io/docs.dinoapp.io/pt/
docs_dir: ../../docs/pt
site_dir: ../../site/pt
theme:
  name: material
  language: pt
nav:
  - Início: index.md
  - Primeiros Passos:
    - Entrar: getting-started/login.md
    - Redefinir a Senha: getting-started/reset-password.md
  - Interface e Navegação: interface/index.md
  - Painel: dashboard/index.md
  - Formulários:
    - Visão Geral: forms/index.md
    - Editar Esquema de Formulário: forms/edit-form-schema.md
    - Editar um Formulário: forms/edit-form.md
    - Mapa de Formulários: forms/forms-map.md
    - Datachat: forms/datachat.md
  - Relatórios:
    - Visão Geral: reports/index.md
    - Editar Esquema de Relatório: reports/edit-report-schema.md
    - Editar Relatório: reports/edit-report.md
  - Métricas:
    - Visão Geral: metrics/index.md
    - Áreas Temáticas: metrics/areas.md
    - Cases: metrics/cases.md
    - Locations: metrics/locations.md
    - Organizations: metrics/organizations.md
    - Projects: metrics/projects.md
  - Agregação: aggregation/index.md
  - Notificações: notifications/index.md
  - Formulários Públicos: public-forms/index.md
  - Administração:
    - Gerir Utilizadores e Grupos: administration/users.md
    - Gerir Idiomas: administration/languages.md
    - Lista de Utilizadores: administration/users-list.md
    - Lista de Grupos: administration/groups-list.md
