INHERIT: ../../mkdocs.base.yml
site_name: Documentazione Dinoapp
site_url: https://gnucoop.github.io/docs.dinoapp.io/it/
docs_dir: ../../docs/it
site_dir: ../../site/it
theme:
  name: material
  language: it
nav:
  - Home: index.md
  - Per Iniziare:
    - Accesso: getting-started/login.md
    - Reimpostare la Password: getting-started/reset-password.md
  - Interfaccia e Navigazione: interface/index.md
  - Dashboard: dashboard/index.md
  - Moduli:
    - Panoramica: forms/index.md
    - Edit Form Schema: forms/edit-form-schema.md
    - Edit Form: forms/edit-form.md
    - Forms Map: forms/forms-map.md
    - Datachat: forms/datachat.md
  - Report:
    - Panoramica: reports/index.md
    - Edit Report Schema: reports/edit-report-schema.md
    - Edit Report: reports/edit-report.md
  - Metriche:
    - Panoramica: metrics/index.md
    - Areas: metrics/areas.md
  - Aggregazione: aggregation/index.md
  - Notifiche: notifications/index.md
  - Moduli Pubblici: public-forms/index.md
  - Amministrazione:
    - Gestire Utenti e Gruppi: administration/users.md
    - Gestire le Lingue: administration/languages.md
    - Elenco Utenti: administration/users-list.md
    - Groups List: administration/groups-list.md
  - Checkout: checkout/index.md
