INHERIT: ../../mkdocs.base.yml
site_name: Documentazione Dinoapp
site_url: https://gnucoop.github.io/dino/it/
docs_dir: ../../docs/it
site_dir: ../../site/it
theme:
  name: material
  language: it
nav:
  - Home: index.md
  - Per Iniziare:
    - Accesso: getting-started/login.md
    - Reimpostare la Password: getting-started/reset-password.md
  - Interfaccia e Navigazione: interface/index.md
  - Pannello di Controllo: dashboard/index.md
  - Form:
    - Panoramica: forms/index.md
    - Modifica Form Schema: forms/edit-form-schema.md
    - Modifica Form: forms/edit-form.md
    - Mappa dei Form: forms/forms-map.md
    - Datachat: forms/datachat.md
  - Report:
    - Panoramica: reports/index.md
    - Modifica Report Schema: reports/edit-report-schema.md
    - Modifica Report: reports/edit-report.md
  - Metriche:
    - Panoramica: metrics/index.md
    - Aree Tematiche: metrics/areas.md
    - Casi: metrics/cases.md
    - Posizioni: metrics/locations.md
    - Organizzazioni: metrics/organizations.md
    - Progetti: metrics/projects.md
  - Aggregazione: aggregation/index.md
  - Notifiche: notifications/index.md
  - Moduli Pubblici: public-forms/index.md
  - Amministrazione:
    - Gestire Utenti e Gruppi: administration/users.md
    - Gestire le Lingue: administration/languages.md
    - Elenco Utenti: administration/users-list.md
    - Elenco Gruppi: administration/groups-list.md
