load("//src/e2e-app:test_suite.bzl", "e2e_test_suite")
load(
    "//tools:defaults.bzl",
    "markdown_to_html",
    "ng_e2e_test_library",
    "ng_module",
    "ng_test_library",
    "ng_web_test_suite",
    "sass_binary",
    "sass_library",
)

package(default_visibility = ["//visibility:public"])

ng_module(
    name = "search-filters-widget",
    srcs = glob(
        ["**/*.ts"],
        exclude = ["**/*.spec.ts"],
    ),
    assets = [":search-filters-widget.css"] + glob(["**/*.html"]),
    module_name = "@dewco/material/search-filters-widget",
    deps = [
        "//src/core/list",
        "@npm//@ajf/core",
        "@npm//@ajf/material",
        "@npm//@angular/common",
        "@npm//@angular/forms",
        "@npm//@angular/material",
        "@npm//@angular/router",
    ],
)

sass_library(
    name = "search_filters_widget_scss_lib",
    srcs = glob(["**/_*.scss"]),
)

sass_binary(
    name = "search_filters_widget_scss",
    src = "search-filters-widget.scss",
    deps = [],
)

ng_test_library(
    name = "unit_test_sources",
    srcs = glob(
        ["**/*.spec.ts"],
        exclude = ["**/*.e2e.spec.ts"],
    ),
    deps = [
        ":search-filters-widget",
        "//src/core/list",
        "@npm//@ajf/core",
        "@npm//@ajf/material",
        "@npm//@angular/common",
        "@npm//@angular/material",
        "@npm//@angular/router",
    ],
)

ng_e2e_test_library(
    name = "e2e_test_sources",
    srcs = glob(["**/*.e2e.spec.ts"]),
)

ng_web_test_suite(
    name = "unit_tests",
    deps = [":unit_test_sources"],
)

e2e_test_suite(
    name = "e2e_tests",
    deps = [
        ":e2e_test_sources",
    ],
)

markdown_to_html(
    name = "overview",
    srcs = ["search-filters-widget.md"],
)

filegroup(
    name = "source-files",
    srcs = glob(["**/*.ts"]),
)
