/**
 * @license
 * Copyright (C) Gnucoop soc. coop.
 *
 * This file is part of the Dino (dino).
 *
 * Dino (dino) is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Dino (dino) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero
 * General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Dino (dino).
 * If not, see http://www.gnu.org/licenses/.
 *
 */

import {
  AjfChoicesOrigin,
  AjfFieldType,
  AjfForm,
  AjfFormRenderer as AjfCoreFormRenderer,
  AjfFormRendererService,
  AjfFormSerializer,
  AjfNode,
  AjfNodeType,
  AjfSlide,
} from '@ajf/core/forms';
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  EventEmitter,
  Input,
  OnDestroy,
  OnInit,
  Output,
  ViewChild,
  ViewEncapsulation,
} from '@angular/core';
import {MatButtonToggleChange} from '@angular/material/button-toggle';
import {MatSlideToggle, MatSlideToggleChange} from '@angular/material/slide-toggle';
import {
  CHOICES_CONDITION_OPERATORS,
  DEFAULT_OPERATORS,
  FilterItem,
  FiltersService,
  NUMBER_CONDITION_OPERATORS,
  Operator,
  WidgetData,
} from '@dino/core/list';
import {
  BehaviorSubject,
  combineLatest,
  Observable,
  of as obsOf,
  Subscription,
  throwError,
} from 'rxjs';
import {catchError, debounceTime, switchMap} from 'rxjs/operators';

/**
 * Widget component containing a single filter, generated by a _WidgetData object.
 * Renders an AjfForm with a field and updates the filters list with the field value
 * via FiltersService.
 *
 * It can be displayed or hidden, depending on the state of its visibility conditions.
 * (eg. It could be hidden if another widget's field value doesn't match its visibility conditions)
 */
@Component({
  selector: 'dino-search-filters-widget',
  templateUrl: 'search-filters-widget.html',
  styleUrls: ['search-filters-widget.scss'],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [AjfFormRendererService],
})
export class SearchFiltersWidget
  extends AjfCoreFormRenderer
  implements AfterViewInit, OnInit, OnDestroy
{
  /**
   * The filterItem used to generate the AjfForm, and the widgetData
   */
  @Input() filterItemData: FilterItem;

  /**
   * Event emitted when the widget's toggle is checked
   */
  @Output() readonly includeFilter: EventEmitter<FilterItem> = new EventEmitter<FilterItem>();

  /**
   * Event emitted when the widget's toggle is unchecked
   */
  @Output() readonly excludeFilter: EventEmitter<FilterItem> = new EventEmitter<FilterItem>();

  /**
   * Slide toggle to include/exclude filter
   */
  @ViewChild('toggleFilter') toggleButton: MatSlideToggle;

  /**
   * A _widgetData object containing all data relative to the widget.
   */
  private _widgetData: WidgetData;

  get widgetData(): WidgetData {
    return this._widgetData;
  }

  /**
   * The value changes of the widget's AjfForm
   */
  private _formValueChanges: Observable<{[key: string]: any}>;

  /**
   * State of the matSlideToggle
   */
  private _matToggleValue: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);

  /**
   * Subscribes to the _formValueChanges to update the state of the slide toggle accordingly
   */
  private _toggleSub: Subscription = Subscription.EMPTY;

  /**
   * Subscribes to the widget's value, toggle and operator changes
   * to include or exclude the filter, after validating it via
   * the FiltersService.
   */
  private _changeFiltersSub: Subscription = Subscription.EMPTY;

  /**
   * State of the Widget visibility
   */
  private _widgetVisibility: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(true);
  get widgetVisibility(): BehaviorSubject<boolean> {
    return this._widgetVisibility;
  }

  /**
   * Subscribes to the temporary filters list and
   * determines the state of the widget's visibility
   */
  private _widgetVisibilitySub: Subscription = Subscription.EMPTY;

  /**
   * State of the filter validation
   */
  private _validation: boolean;

  /**
   * Widget Name identifier
   */
  private _widgetName: string;
  get widgetName(): string {
    return this._widgetName;
  }

  /**
   * Label displayed on the Widget
   */
  private _widgetLabel: string;
  get widgetLabel(): string {
    return this._widgetLabel;
  }

  /**
   * Operator value of the widget
   */
  private _operatorValue: BehaviorSubject<Operator> = new BehaviorSubject<Operator>({
    label: 'Like',
    value: '$regex',
  });
  get operatorValue(): BehaviorSubject<Operator> {
    return this._operatorValue;
  }

  constructor(
    public rendererService: AjfFormRendererService,
    changeDetectorRef: ChangeDetectorRef,
    private _fs: FiltersService,
  ) {
    super(rendererService, changeDetectorRef);
  }

  ngOnInit() {
    this._widgetData = this._setupWidget(this.filterItemData);

    this._operatorValue.next(this._widgetData.operator);
    this._matToggleValue.next(this._widgetData.active);

    // Here we check if the visibility conditions of the widget are met
    if (
      this._widgetData.visibilityConditions != null &&
      this._widgetData.visibilityConditions.condition != 'true'
    ) {
      this._widgetVisibilitySub = this._fs.temporaryFilters.subscribe(_ => {
        const conditionVerified = this._fs.checkCondition(this._widgetData.visibilityConditions);
        if (conditionVerified !== this._widgetVisibility.value) {
          this._widgetVisibility.next(conditionVerified);
        }
      });
    }

    this._formValueChanges = this.formGroup.pipe(
      switchMap(fg => (fg ? fg.valueChanges : obsOf(null))),
    );

    this._changeFiltersSub = combineLatest([
      this._formValueChanges,
      this._matToggleValue,
      this.operatorValue,
      this._widgetVisibility,
    ])
      .pipe(
        debounceTime(300),
        catchError(
          err =>
            throwError(() => err) as Observable<[{[key: string]: any}, boolean, Operator, boolean]>,
        ),
      )
      .subscribe(([formValue, toggleValue, operatorValue, visibility]) => {
        if (!formValue) {
          return;
        }
        delete formValue.$value;
        Object.keys(formValue).forEach(key => {
          this.filterItemData.value = formValue[key];
          this.filterItemData.operator = operatorValue;
          this._validation = this._fs.checkValidation(
            this.filterItemData,
            this._widgetData.validationConditions,
          );
          this.filterItemData.isValid = this._validation;
        });
        if (toggleValue && this.filterItemData.value != null && visibility) {
          this._widgetData.active = true;
          this.includeFilter.emit(this.filterItemData);
        } else if ((!toggleValue || !visibility) && this._widgetData.active) {
          this._widgetData.active = false;
          this.excludeFilter.emit(this.filterItemData);
        }
      });
  }

  override ngAfterViewInit() {
    super.ngAfterViewInit();
    this._toggleSub = this._formValueChanges
      .pipe(catchError(err => throwError(() => err) as Observable<{[key: string]: any}>))
      .subscribe(formValue => {
        if (this.toggleButton && formValue != null && !this.toggleButton.checked) {
          this.toggleButton.toggle();
          this._matToggleValue.next(true);
        }
      });
  }

  /**
   * Transforms a FilterItem into a WidgetData object.
   * It creates an AjfForm from the passed FilterItem, then
   * assigns it to the _WidgetData object.
   * @param filterItem The filter item to transform
   * @returns The _WidgetData object
   */
  private _setupWidget(filterItem: FilterItem): WidgetData {
    const activeFilter = this._fs.temporaryFilters.value.find(f => f.name === filterItem.name);
    const fieldValue = activeFilter ? activeFilter.value : null;
    const fieldChoices: AjfChoicesOrigin<any>[] = filterItem.choicesOrigin
      ? [filterItem.choicesOrigin]
      : [];
    filterItem.value = fieldValue;
    filterItem.operator =
      activeFilter?.operator ?? DEFAULT_OPERATORS[filterItem.fieldType ?? AjfFieldType.String];
    const formSchema: Partial<AjfForm> = {
      choicesOrigins: fieldChoices,
      nodes: [
        {
          parent: 0,
          parentNode: 0,
          id: 1,
          name: filterItem.name,
          label: filterItem.label,
          nodeType: AjfNodeType.AjfSlide,
          nodes: [filterItem as Partial<AjfNode>],
        } as AjfSlide,
      ],
    };
    const ctx = Object.create({});
    ctx[filterItem.name] = fieldValue;
    const filterVisibility = filterItem.visibility;
    const form = AjfFormSerializer.fromJson(formSchema, ctx);
    form.nodes[0].visibility = filterVisibility;

    this.form = form;
    this._widgetName = filterItem.name;
    this._widgetLabel = filterItem.label ?? '';

    return {
      form: form,
      operator: filterItem.operator,
      active: fieldValue != null,
      validationConditions: filterItem.validation,
      visibilityConditions: filterVisibility ?? {condition: 'true'},
    };
  }

  /**
   * Sets the checked state of the MatSlideToggle
   * @param toggle The MatSlideToggle to set
   */
  filterToggle(toggle: MatSlideToggleChange) {
    this._matToggleValue.next(toggle.checked);
  }

  /**
   * Sets the filter operator value to the one chosen in the MatButtonToggleGroup of the operators
   * @param operator The filter operator value
   */
  changeOperator(operator: MatButtonToggleChange) {
    this.operatorValue.next(operator.value as Operator);
  }

  /**
   * Returns the right array of operators associated with the filter type
   * @param type The type of the AjfField
   * @returns The operators
   */
  conditionOperatorByFieldType(type: AjfFieldType): Operator[] {
    switch (type) {
      case AjfFieldType.Number:
      case AjfFieldType.Date:
      case AjfFieldType.DateInput:
        return NUMBER_CONDITION_OPERATORS;
      case AjfFieldType.MultipleChoice:
        return CHOICES_CONDITION_OPERATORS;
      default:
        return [];
    }
  }

  /**
   * Checks and returns the widget slide toggle button disabled state
   * @param obj The widget form value
   * @param element The slide toggle
   * @returns The new slide toggle state
   */
  checkToggleDisabled(): boolean {
    if (!this._widgetVisibility.value || !this._validation) {
      return true;
    }
    const formValue = this.getWidgetFormValue();
    for (let key in formValue) {
      if (formValue[key] !== null && formValue[key] !== '') {
        return false;
      }
    }
    if (this.toggleButton && this.toggleButton.checked) {
      this.toggleButton.toggle();
      this._matToggleValue.next(false);
      this.toggleButton.setDisabledState(true);
    }
    return true;
  }

  /**
   * Retrieves the widget ajfform value
   * @returns The widget form value
   */
  getWidgetFormValue(): {[key: string]: unknown} {
    return this.rendererService.getFormValue();
  }

  override ngOnDestroy() {
    super.ngOnDestroy();
    this._changeFiltersSub.unsubscribe();
    this._toggleSub.unsubscribe();
    this._widgetVisibilitySub.unsubscribe();

    this.includeFilter.complete();
    this.excludeFilter.complete();
    this._matToggleValue.complete();
    this._operatorValue.complete();
    this._widgetVisibility.complete();
  }
}
