load("//tools:defaults.bzl", "ng_module", "sass_binary")

package(default_visibility = ["//visibility:public"])

ng_module(
    name = "theme",
    srcs = glob(["**/*.ts"]),
    assets = [
        "theme-demo.html",
        ":theme_demo_scss",
    ],
    deps = [
        "//src/material/core",
        "@npm//@angular/cdk",
        "@npm//@angular/core",
        "@npm//@angular/material",
        "@npm//@angular/router",
        "@npm//angular-material-css-vars",
        "@npm//ngx-color-picker",
        "@npm//rxjs",
    ],
)

sass_binary(
    name = "theme_demo_scss",
    src = "theme-demo.scss",
)
