load("//src/e2e-app:test_suite.bzl", "e2e_test_suite")
load(
    "//tools:defaults.bzl",
    "markdown_to_html",
    "ng_e2e_test_library",
    "ng_module",
    "ng_test_library",
    "ng_web_test_suite",
    "sass_binary",
    "sass_library",
)

package(default_visibility = ["//visibility:public"])

ng_module(
    name = "collect",
    srcs = glob(
        ["**/*.ts"],
        exclude = ["**/*.spec.ts"],
    ),
    assets = [":collect.css"] + glob(["**/*.html"]),
    deps = [
        "//src/core/auth",
        "//src/core/forms",
        "//src/core/reports",
        "//src/material/breakpoint-observer",
        "//src/material/floating-button",
        "@npm//@angular/cdk",
        "@npm//@angular/common",
        "@npm//@angular/forms",
        "@npm//@angular/material",
    ],
)

sass_library(
    name = "collect_scss_lib",
    srcs = glob(["**/_*.scss"]),
)

sass_binary(
    name = "collect_scss",
    src = "collect.scss",
    deps = [],
)

ng_test_library(
    name = "unit_test_sources",
    srcs = glob(
        ["**/*.spec.ts"],
        exclude = ["**/*.e2e.spec.ts"],
    ),
    deps = [
        ":collect",
        "//src/core/auth",
        "//src/core/data",
        "//src/core/forms",
        "//src/core/reports",
        "//src/core/translations",
        "//src/core/users",
        "@npm//@angular/common",
        "@npm//@angular/forms",
        "@npm//@angular/router",
        "@npm//@types/pouchdb-adapter-memory",
        "@npm//rxdb",
        "@npm//rxjs",
    ],
)

ng_e2e_test_library(
    name = "e2e_test_sources",
    srcs = glob(["**/*.e2e.spec.ts"]),
)

ng_web_test_suite(
    name = "unit_tests",
    deps = [":unit_test_sources"],
)

e2e_test_suite(
    name = "e2e_tests",
    deps = [
        ":e2e_test_sources",
    ],
)

markdown_to_html(
    name = "overview",
    srcs = ["collect.md"],
)

filegroup(
    name = "source-files",
    srcs = glob(["**/*.ts"]),
)
