load("@npm//@bazel/concatjs:index.bzl", "concatjs_devserver")
load("//:packages.bzl", "getAngularUmdTargets")
load("//tools:defaults.bzl", "ng_module", "sass_binary")
load("//tools/third-party-libs:index.bzl", "get_amd_bundles")

package(default_visibility = ["//visibility:public"])

# List of dependencies that are referenced in the `index.html` file.
devserverIndexHtmlDependencies = [
    "@npm//zone.js",
    "@npm//core-js-bundle",
    ":index.html",
    ":e2e_main_theme",
    ":e2e_alt_theme",
]

exports_files([
    "protractor.conf.js",
    "start-devserver.js",
    "devserver-configure.js",
])

ng_module(
    name = "e2e-app",
    testonly = True,
    srcs = glob(
        ["**/*.ts"],
        exclude = ["test-util/**"],
    ),
    assets = glob(
        [
            "**/*.html",
            "**/*.css",
        ],
        exclude = ["index.html"],
    ),
    deps = [
        "//src/core/areas",
        "//src/core/auth",
        "//src/core/config",
        "//src/core/data",
        "//src/core/forms",
        "//src/core/reports",
        "//src/core/locations",
        "//src/core/organizations",
        "//src/core/projects",
        "//src/core/translations",
        "//src/core/users",
        "//src/dewco-examples/private",
        "//src/material/breakpoint-observer",
        "//src/material/collect",
        "//src/material/create-form",
        "//src/material/edit-form",
        "//src/material/floating-button",
        "//src/material/list",
        "//src/material/login",
        "//src/material/main-nav",
        "//src/material/metric-editor",
        "//src/material/metric-section",
        "//src/material/mixed-editor",
        "//src/material/search-filters-bar",
        "//src/material/user-editor",
        "@npm//@ajf/core",
        "@npm//@angular/cdk",
        "@npm//@angular/common",
        "@npm//@angular/core",
        "@npm//@angular/material",
        "@npm//@angular/platform-browser",
        "@npm//@angular/router",
        "@npm//@types/pouchdb-adapter-memory",
        "@npm//rxdb",
        "@npm//rxjs",
    ],
)

sass_binary(
    name = "e2e_main_theme",
    src = "e2e_main_theme.scss",
    deps = [
        "//src/material/core:theming_scss_lib",
    ],
)

sass_binary(
    name = "e2e_alt_theme",
    src = "e2e_alt_theme.scss",
    deps = [
        "//src/material/core:theming_scss_lib",
    ],
)

concatjs_devserver(
    name = "devserver",
    testonly = True,
    additional_root_paths = [
        "npm/node_modules",
    ],
    entry_module = "gc_dewco/src/e2e-app/main",
    port = 4200,
    # Scripts which will be included in the serving_path bundle after RequireJS has been loaded.
    scripts = [
        ":devserver-configure.js",
        "//tools/rxjs:rxjs_umd_modules",
        "@npm//:node_modules/tslib/tslib.js",
    ] + getAngularUmdTargets() + get_amd_bundles(),
    # Name of the generated `concatjs` bundle that is built based on the labels in `deps` and `scripts`.
    serving_path = "/bundle.js",
    static_files = devserverIndexHtmlDependencies,
    tags = ["manual"],
    deps = [":e2e-app"],
)
