load("@npm//@bazel/concatjs:index.bzl", "concatjs_devserver")
load("//:packages.bzl", "getAngularUmdTargets")
load("//tools:defaults.bzl", "ng_module", "sass_binary")

package(default_visibility = ["//visibility:public"])

exports_files([
    "protractor.conf.js",
    "start-devserver.js",
    "devserver-configure.js",
])

ng_module(
    name = "e2e-app",
    testonly = True,
    srcs = glob(
        ["**/*.ts"],
        exclude = ["test-util/**"],
    ),
    assets = glob(
        [
            "**/*.html",
            "**/*.css",
        ],
        exclude = ["index.html"],
    ),
    deps = [
        "//src/core/data",
        "//src/core/forms",
        "//src/core/locations",
        "//src/core/projects",
        "//src/dewco-examples/private",
        "//src/material/list",
        "//src/material/login",
        "//src/material/search-filters-bar",
        "@npm//@angular/material",
        "@npm//@angular/router",
    ],
)

sass_binary(
    name = "e2e_main_theme",
    src = "e2e_main_theme.scss",
    deps = [
        "//src/material/core:theming_scss_lib",
    ],
)

sass_binary(
    name = "e2e_alt_theme",
    src = "e2e_alt_theme.scss",
    deps = [
        "//src/material/core:theming_scss_lib",
    ],
)

concatjs_devserver(
    name = "devserver",
    testonly = True,
    additional_root_paths = [
        "npm/node_modules",
    ],
    # Name of the AMD module that should be required on page load.
    entry_module = "gc_dewco/src/e2e-app/main",
    port = 4200,
    # Scripts which will be included in the serving_path bundle after
    # RequireJS has been loaded.
    scripts = [
        ":devserver-configure.js",
        "//tools/rxjs:rxjs_umd_modules",
        "@npm//:node_modules/tslib/tslib.js",
    ] + getAngularUmdTargets(),
    # Serving path of the bundle that serves all files specified in "deps" and "scripts".
    serving_path = "/bundle.js",
    # Files which should be provided by Bazel when running the devserver. These are not
    # automatically served, but can be loaded manually through HTTP requests.
    static_files = [
        "@npm//zone.js",
        "@npm//core-js-bundle",
        ":index.html",
        ":e2e_main_theme.css",
        ":e2e_alt_theme.css",
    ],
    tags = ["manual"],
    deps = [":e2e-app"],
)
