load("//tools/dev-server:index.bzl", "dev_server")
load("//tools:defaults.bzl", "ng_module", "sass_binary")
load("//tools/esbuild:index.bzl", "esbuild", "esbuild_config")
load("//src/dino-examples:config.bzl", "ALL_EXAMPLES")
load("//tools/angular:index.bzl", "LINKER_PROCESSED_FW_PACKAGES")

package(default_visibility = ["//visibility:public"])

# List of dependencies that are referenced in the `index.html` file.
devserverIndexHtmlDependencies = [
    "@npm//zone.js",
    "@npm//core-js-bundle",
    ":index.html",
    ":e2e_main_theme",
    ":e2e_alt_theme",
]

exports_files([
    "protractor.conf.js",
    "start-devserver.js",
    "devserver-configure.js",
])

ng_module(
    name = "e2e-app",
    testonly = True,
    srcs = glob(
        ["**/*.ts"],
        exclude = ["test-util/**"],
    ),
    assets = glob(
        [
            "**/*.html",
            "**/*.css",
        ],
        exclude = ["index.html"],
    ),
    deps = [
        "//src/core/areas",
        "//src/core/auth",
        "//src/core/cases",
        "//src/core/config",
        "//src/core/data",
        "//src/core/forms",
        "//src/core/locations",
        "//src/core/organizations",
        "//src/core/projects",
        "//src/core/reports",
        "//src/core/sync",
        "//src/core/translations",
        "//src/core/users",
        "//src/dino-examples/private",
        "//src/material/breadcrumbs",
        "//src/material/breakpoint-observer",
        "//src/material/collect",
        "//src/material/core",
        "//src/material/create-form",
        "//src/material/create-report",
        "//src/material/edit-form",
        "//src/material/edit-form-schema",
        "//src/material/edit-report",
        "//src/material/edit-report-schema",
        "//src/material/floating-button",
        "//src/material/langs",
        "//src/material/list",
        "//src/material/login",
        "//src/material/main-nav",
        "//src/material/metric-editor",
        "//src/material/metric-section",
        "//src/material/mixed-editor",
        "//src/material/search-filters-bar",
        "//src/material/user-editor",
        "@npm//@ajf/core",
        "@npm//@ajf/material",
        "@npm//@angular/cdk",
        "@npm//@angular/common",
        "@npm//@angular/core",
        "@npm//@angular/material",
        "@npm//@angular/platform-browser",
        "@npm//@angular/router",
        "@npm//@types/pouchdb-adapter-memory",
        "@npm//events",
        "@npm//pouchdb",
        "@npm//pouchdb-adapter-idb",
        "@npm//rxdb",
        "@npm//rxjs",
    ],
)

sass_binary(
    name = "e2e_main_theme",
    src = "e2e_main_theme.scss",
    deps = [
        "//src/material/core:theming_scss_lib",
    ],
)

sass_binary(
    name = "e2e_alt_theme",
    src = "e2e_alt_theme.scss",
    deps = [
        "//src/material/core:theming_scss_lib",
    ],
)

esbuild_config(
    name = "esbuild_config",
    testonly = True,
    config_file = "esbuild.config.mjs",
    deps = [
        "//tools/esbuild:custom_resolve_esbuild_plugin",
    ],
)

esbuild(
    name = "bundles",
    testonly = True,
    config = ":esbuild_config",
    entry_points = [":main.ts"] + ["%s:index.ts" % e for e in ALL_EXAMPLES],
    platform = "browser",
    splitting = True,
    # We cannot use `ES2017` or higher as that would result in `async/await` not being downleveled.
    # ZoneJS needs to be able to intercept these as otherwise change detection would not work properly.
    target = "es2016",
    # Note: We add all linker-processed FW packages as dependencies here so that ESBuild will
    # map all framework packages to their linker-processed bundles from `tools/angular`.
    deps = LINKER_PROCESSED_FW_PACKAGES + [
        ":e2e-app",
    ],
)

dev_server(
    name = "devserver",
    testonly = True,
    srcs = devserverIndexHtmlDependencies + ["//src:source-files"],
    additional_root_paths = [
        "npm/node_modules",
        "gc_dino",
    ],
    tags = ["manual"],
    deps = [
        ":bundles",
    ],
)
