import {AjfChoicesOriginType} from '@ajf/core/forms';
import {FormSchema} from '@dewco/core/forms';
/**
 * The test schema is taken from WWGVC "hr".
 *
 * schema url: https://bitbucket.org/gnucoop/wwgvc-schema/src/9e5b700c9097/form/hr.json?at=master
 */
export const ajfSchema = {
  'nodes': [
    {
      'id': 1,
      'name': 'personal',
      'label': 'Personal information',
      'nodes': [
        {
          'id': 1000,
          'HTML':
              'Please use this form only for local staff.',
          'name': '',
          'size': 'normal',
          'label': '',
          'parent': 1,
          'editable': false,
          'nodeType': 0,
          'fieldType': 7,
          'parentNode': 0,
          'visibility': {'condition': 'true'},
          'conditionalBranches': []
        },
        {
          'id': 1001,
          'hint': 'The country where the person is employed',
          'name': 'country',
          'size': 'normal',
          'label': 'Country',
          'parent': 1000,
          'choices': [],
          'warning': {'conditions': []},
          'editable': true,
          'nodeType': 0,
          'fieldType': 4,
          'parentNode': 0,
          'validation': {
            'notEmpty': {
              'condition': 'notEmpty($value)',
              'errorMessage': 'Value must not be empty',
              'clientValidation': false
            },
            'conditions': []
          },
          'visibility': {'condition': 'true'},
          'description': null,
          'forceNarrow': false,
          'defaultValue': null,
          'choicesOrigin': {
            'name': 'countries',
            'type': 'fixed' as AjfChoicesOriginType,
            'label': '',
            'choices': [
              {'label': 'Afghanistan', 'value': 'AFG'},
              {'label': 'Albania', 'value': 'ALB'},
              {'label': 'Algeria', 'value': 'DZA'},
              {'label': 'American Samoa', 'value': 'ASM'},
              {'label': 'Andorra', 'value': 'AND'},
              {'label': 'Angola', 'value': 'AGO'},
              {'label': 'Anguilla', 'value': 'AIA'},
              {'label': 'Antarctica', 'value': 'ATA'},
              {'label': 'Antigua and Barbuda', 'value': 'ATG'},
              {'label': 'Argentina', 'value': 'ARG'},
              {'label': 'Armenia', 'value': 'ARM'},
              {'label': 'Aruba', 'value': 'ABW'},
              {'label': 'Australia', 'value': 'AUS'},
              {'label': 'Austria', 'value': 'AUT'},
              {'label': 'Azerbaijan', 'value': 'AZE'},
              {'label': 'Bahamas (the)', 'value': 'BHS'},
              {'label': 'Bahrain', 'value': 'BHR'},
              {'label': 'Bangladesh', 'value': 'BGD'},
              {'label': 'Barbados', 'value': 'BRB'},
              {'label': 'Belarus', 'value': 'BLR'},
              {'label': 'Belgium', 'value': 'BEL'},
              {'label': 'Belize', 'value': 'BLZ'},
              {'label': 'Benin', 'value': 'BEN'},
              {'label': 'Bermuda', 'value': 'BMU'},
              {'label': 'Bhutan', 'value': 'BTN'},
              {'label': 'Bolivia (Plurinational State of)', 'value': 'BOL'},
              {'label': 'Bonaire, Sint Eustatius and Saba', 'value': 'BES'},
              {'label': 'Bosnia and Herzegovina', 'value': 'BIH'},
              {'label': 'Botswana', 'value': 'BWA'},
              {'label': 'Bouvet Island', 'value': 'BVT'},
              {'label': 'Brazil', 'value': 'BRA'},
              {'label': 'British Indian Ocean Territory (the)', 'value': 'IOT'},
              {'label': 'Brunei Darussalam', 'value': 'BRN'},
              {'label': 'Bulgaria', 'value': 'BGR'},
              {'label': 'Burkina Faso', 'value': 'BFA'},
              {'label': 'Burundi', 'value': 'BDI'},
              {'label': 'Cabo Verde', 'value': 'CPV'},
              {'label': 'Cambodia', 'value': 'KHM'},
              {'label': 'Cameroon', 'value': 'CMR'},
              {'label': 'Canada', 'value': 'CAN'},
              {'label': 'Cayman Islands (the)', 'value': 'CYM'},
              {'label': 'Central African Republic (the)', 'value': 'CAF'},
              {'label': 'Chad', 'value': 'TCD'},
              {'label': 'Chile', 'value': 'CHL'},
              {'label': 'China', 'value': 'CHN'},
              {'label': 'Christmas Island', 'value': 'CXR'},
              {'label': 'Cocos (Keeling) Islands (the)', 'value': 'CCK'},
              {'label': 'Colombia', 'value': 'COL'},
              {'label': 'Comoros (the)', 'value': 'COM'},
              {'label': 'Congo (the Democratic Republic of the)', 'value': 'COD'},
              {'label': 'Congo (the)', 'value': 'COG'},
              {'label': 'Cook Islands (the)', 'value': 'COK'},
              {'label': 'Costa Rica', 'value': 'CRI'},
              {'label': 'Croatia', 'value': 'HRV'},
              {'label': 'Cuba', 'value': 'CUB'},
              {'label': 'Cura\u00e7ao', 'value': 'CUW'},
              {'label': 'Cyprus', 'value': 'CYP'},
              {'label': 'Czechia', 'value': 'CZE'},
              {'label': 'C\u00f4te d\'Ivoire', 'value': 'CIV'},
              {'label': 'Denmark', 'value': 'DNK'},
              {'label': 'Djibouti', 'value': 'DJI'},
              {'label': 'Dominica', 'value': 'DMA'},
              {'label': 'Dominican Republic (the)', 'value': 'DOM'},
              {'label': 'Ecuador', 'value': 'ECU'},
              {'label': 'Egypt', 'value': 'EGY'},
              {'label': 'El Salvador', 'value': 'SLV'},
              {'label': 'Equatorial Guinea', 'value': 'GNQ'},
              {'label': 'Eritrea', 'value': 'ERI'},
              {'label': 'Estonia', 'value': 'EST'},
              {'label': 'Eswatini', 'value': 'SWZ'},
              {'label': 'Ethiopia', 'value': 'ETH'},
              {'label': 'Falkland Islands (the) [Malvinas]', 'value': 'FLK'},
              {'label': 'Faroe Islands (the)', 'value': 'FRO'},
              {'label': 'Fiji', 'value': 'FJI'},
              {'label': 'Finland', 'value': 'FIN'},
              {'label': 'France', 'value': 'FRA'},
              {'label': 'French Guiana', 'value': 'GUF'},
              {'label': 'French Polynesia', 'value': 'PYF'},
              {'label': 'French Southern Territories (the)', 'value': 'ATF'},
              {'label': 'Gabon', 'value': 'GAB'},
              {'label': 'Gambia (the)', 'value': 'GMB'},
              {'label': 'Georgia', 'value': 'GEO'},
              {'label': 'Germany', 'value': 'DEU'},
              {'label': 'Ghana', 'value': 'GHA'},
              {'label': 'Gibraltar', 'value': 'GIB'},
              {'label': 'Greece', 'value': 'GRC'},
              {'label': 'Greenland', 'value': 'GRL'},
              {'label': 'Grenada', 'value': 'GRD'},
              {'label': 'Guadeloupe', 'value': 'GLP'},
              {'label': 'Guam', 'value': 'GUM'},
              {'label': 'Guatemala', 'value': 'GTM'},
              {'label': 'Guernsey', 'value': 'GGY'},
              {'label': 'Guinea', 'value': 'GIN'},
              {'label': 'Guinea-Bissau', 'value': 'GNB'},
              {'label': 'Guyana', 'value': 'GUY'},
              {'label': 'Haiti', 'value': 'HTI'},
              {'label': 'Heard Island and McDonald Islands', 'value': 'HMD'},
              {'label': 'Holy See (the)', 'value': 'VAT'},
              {'label': 'Honduras', 'value': 'HND'},
              {'label': 'Hong Kong', 'value': 'HKG'},
              {'label': 'Hungary', 'value': 'HUN'},
              {'label': 'Iceland', 'value': 'ISL'},
              {'label': 'India', 'value': 'IND'},
              {'label': 'Indonesia', 'value': 'IDN'},
              {'label': 'Iran (Islamic Republic of)', 'value': 'IRN'},
              {'label': 'Iraq', 'value': 'IRQ'},
              {'label': 'Ireland', 'value': 'IRL'},
              {'label': 'Isle of Man', 'value': 'IMN'},
              {'label': 'Israel', 'value': 'ISR'},
              {'label': 'Italy', 'value': 'ITA'},
              {'label': 'Jamaica', 'value': 'JAM'},
              {'label': 'Japan', 'value': 'JPN'},
              {'label': 'Jersey', 'value': 'JEY'},
              {'label': 'Jordan', 'value': 'JOR'},
              {'label': 'Kazakhstan', 'value': 'KAZ'},
              {'label': 'Kenya', 'value': 'KEN'},
              {'label': 'Kiribati', 'value': 'KIR'},
              {'label': 'Korea (the Democratic People\'s Republic of)', 'value': 'PRK'},
              {'label': 'Korea (the Republic of)', 'value': 'KOR'},
              {'label': 'Kuwait', 'value': 'KWT'},
              {'label': 'Kyrgyzstan', 'value': 'KGZ'},
              {'label': 'Lao People\'s Democratic Republic (the)', 'value': 'LAO'},
              {'label': 'Latvia', 'value': 'LVA'},
              {'label': 'Lebanon', 'value': 'LBN'},
              {'label': 'Lesotho', 'value': 'LSO'},
              {'label': 'Liberia', 'value': 'LBR'},
              {'label': 'Libya', 'value': 'LBY'},
              {'label': 'Liechtenstein', 'value': 'LIE'},
              {'label': 'Lithuania', 'value': 'LTU'},
              {'label': 'Luxembourg', 'value': 'LUX'},
              {'label': 'Macao', 'value': 'MAC'},
              {'label': 'Madagascar', 'value': 'MDG'},
              {'label': 'Malawi', 'value': 'MWI'},
              {'label': 'Malaysia', 'value': 'MYS'},
              {'label': 'Maldives', 'value': 'MDV'},
              {'label': 'Mali', 'value': 'MLI'},
              {'label': 'Malta', 'value': 'MLT'},
              {'label': 'Marshall Islands (the)', 'value': 'MHL'},
              {'label': 'Martinique', 'value': 'MTQ'},
              {'label': 'Mauritania', 'value': 'MRT'},
              {'label': 'Mauritius', 'value': 'MUS'},
              {'label': 'Mayotte', 'value': 'MYT'},
              {'label': 'Mexico', 'value': 'MEX'},
              {'label': 'Micronesia (Federated States of)', 'value': 'FSM'},
              {'label': 'Moldova (the Republic of)', 'value': 'MDA'},
              {'label': 'Monaco', 'value': 'MCO'},
              {'label': 'Mongolia', 'value': 'MNG'},
              {'label': 'Montenegro', 'value': 'MNE'},
              {'label': 'Montserrat', 'value': 'MSR'},
              {'label': 'Morocco', 'value': 'MAR'},
              {'label': 'Mozambique', 'value': 'MOZ'},
              {'label': 'Myanmar', 'value': 'MMR'},
              {'label': 'Namibia', 'value': 'NAM'},
              {'label': 'Nauru', 'value': 'NRU'},
              {'label': 'Nepal', 'value': 'NPL'},
              {'label': 'Netherlands (the)', 'value': 'NLD'},
              {'label': 'New Caledonia', 'value': 'NCL'},
              {'label': 'New Zealand', 'value': 'NZL'},
              {'label': 'Nicaragua', 'value': 'NIC'},
              {'label': 'Niger (the)', 'value': 'NER'},
              {'label': 'Nigeria', 'value': 'NGA'},
              {'label': 'Niue', 'value': 'NIU'},
              {'label': 'Norfolk Island', 'value': 'NFK'},
              {'label': 'Northern Mariana Islands (the)', 'value': 'MNP'},
              {'label': 'Norway', 'value': 'NOR'},
              {'label': 'Oman', 'value': 'OMN'},
              {'label': 'Pakistan', 'value': 'PAK'},
              {'label': 'Palau', 'value': 'PLW'},
              {'label': 'Palestine, State of', 'value': 'PSE'},
              {'label': 'Panama', 'value': 'PAN'},
              {'label': 'Papua New Guinea', 'value': 'PNG'},
              {'label': 'Paraguay', 'value': 'PRY'},
              {'label': 'Peru', 'value': 'PER'},
              {'label': 'Philippines (the)', 'value': 'PHL'},
              {'label': 'Pitcairn', 'value': 'PCN'},
              {'label': 'Poland', 'value': 'POL'},
              {'label': 'Portugal', 'value': 'PRT'},
              {'label': 'Puerto Rico', 'value': 'PRI'},
              {'label': 'Qatar', 'value': 'QAT'},
              {'label': 'Republic of North Macedonia', 'value': 'MKD'},
              {'label': 'Romania', 'value': 'ROU'},
              {'label': 'Russian Federation (the)', 'value': 'RUS'},
              {'label': 'Rwanda', 'value': 'RWA'},
              {'label': 'R\u00e9union', 'value': 'REU'},
              {'label': 'Saint Barth\u00e9lemy', 'value': 'BLM'},
              {'label': 'Saint Helena, Ascension and Tristan da Cunha', 'value': 'SHN'},
              {'label': 'Saint Kitts and Nevis', 'value': 'KNA'},
              {'label': 'Saint Lucia', 'value': 'LCA'},
              {'label': 'Saint Martin (French part)', 'value': 'MAF'},
              {'label': 'Saint Pierre and Miquelon', 'value': 'SPM'},
              {'label': 'Saint Vincent and the Grenadines', 'value': 'VCT'},
              {'label': 'Samoa', 'value': 'WSM'},
              {'label': 'San Marino', 'value': 'SMR'},
              {'label': 'Sao Tome and Principe', 'value': 'STP'},
              {'label': 'Saudi Arabia', 'value': 'SAU'},
              {'label': 'Senegal', 'value': 'SEN'},
              {'label': 'Serbia', 'value': 'SRB'},
              {'label': 'Seychelles', 'value': 'SYC'},
              {'label': 'Sierra Leone', 'value': 'SLE'},
              {'label': 'Singapore', 'value': 'SGP'},
              {'label': 'Sint Maarten (Dutch part)', 'value': 'SXM'},
              {'label': 'Slovakia', 'value': 'SVK'},
              {'label': 'Slovenia', 'value': 'SVN'},
              {'label': 'Solomon Islands', 'value': 'SLB'},
              {'label': 'Somalia', 'value': 'SOM'},
              {'label': 'South Africa', 'value': 'ZAF'},
              {'label': 'South Georgia and the South Sandwich Islands', 'value': 'SGS'},
              {'label': 'South Sudan', 'value': 'SSD'},
              {'label': 'Spain', 'value': 'ESP'},
              {'label': 'Sri Lanka', 'value': 'LKA'},
              {'label': 'Sudan (the)', 'value': 'SDN'},
              {'label': 'Suriname', 'value': 'SUR'},
              {'label': 'Svalbard and Jan Mayen', 'value': 'SJM'},
              {'label': 'Sweden', 'value': 'SWE'},
              {'label': 'Switzerland', 'value': 'CHE'},
              {'label': 'Syrian Arab Republic', 'value': 'SYR'},
              {'label': 'Taiwan (Province of China)', 'value': 'TWN'},
              {'label': 'Tajikistan', 'value': 'TJK'},
              {'label': 'Tanzania, United Republic of', 'value': 'TZA'},
              {'label': 'Thailand', 'value': 'THA'},
              {'label': 'Timor-Leste', 'value': 'TLS'},
              {'label': 'Togo', 'value': 'TGO'},
              {'label': 'Tokelau', 'value': 'TKL'},
              {'label': 'Tonga', 'value': 'TON'},
              {'label': 'Trinidad and Tobago', 'value': 'TTO'},
              {'label': 'Tunisia', 'value': 'TUN'},
              {'label': 'Turkey', 'value': 'TUR'},
              {'label': 'Turkmenistan', 'value': 'TKM'},
              {'label': 'Turks and Caicos Islands (the)', 'value': 'TCA'},
              {'label': 'Tuvalu', 'value': 'TUV'},
              {'label': 'Uganda', 'value': 'UGA'},
              {'label': 'Ukraine', 'value': 'UKR'},
              {'label': 'United Arab Emirates (the)', 'value': 'ARE'},
              {
                'label': 'United Kingdom of Great Britain and Northern Ireland (the)',
                'value': 'GBR'
              },
              {'label': 'United States Minor Outlying Islands (the)', 'value': 'UMI'},
              {'label': 'United States of America (the)', 'value': 'USA'},
              {'label': 'Uruguay', 'value': 'URY'},
              {'label': 'Uzbekistan', 'value': 'UZB'},
              {'label': 'Vanuatu', 'value': 'VUT'},
              {'label': 'Venezuela (Bolivarian Republic of)', 'value': 'VEN'},
              {'label': 'Viet Nam', 'value': 'VNM'},
              {'label': 'Virgin Islands (British)', 'value': 'VGB'},
              {'label': 'Virgin Islands (U.S.)', 'value': 'VIR'},
              {'label': 'Wallis and Futuna', 'value': 'WLF'},
              {'label': 'Western Sahara', 'value': 'ESH'},
              {'label': 'Yemen', 'value': 'YEM'},
              {'label': 'Zambia', 'value': 'ZMB'},
              {'label': 'Zimbabwe', 'value': 'ZWE'},
              {'label': '\u00c5land Islands', 'value': 'ALA'}
            ],
            'choicesType': 'string'
          },
          'forceExpanded': false,
          'choicesOriginRef': 'countries',
          'triggerConditions': [],
          'conditionalBranches': []
        },
        {
          'id': 1002,
          'hint': 'Person\'s last name',
          'name': 'name',
          'size': 'normal',
          'label': 'Last name',
          'parent': 1001,
          'warning': {'conditions': []},
          'editable': true,
          'nodeType': 0,
          'fieldType': 0,
          'parentNode': 0,
          'validation': {'conditions': [], 'notEmpty': true},
          'visibility': {'condition': 'true'},
          'description': null,
          'defaultValue': null,
          'conditionalBranches': []
        },
        {
          'id': 1003,
          'hint': 'Person\'s first name',
          'name': 'firstname',
          'size': 'normal',
          'label': 'First Name',
          'parent': 1002,
          'editable': true,
          'nodeType': 0,
          'fieldType': 0,
          'parentNode': 0,
          'visibility': {'condition': 'true'},
          'defaultValue': null,
          'conditionalBranches': [],
          'validation': {'notEmpty': true}
        },
        {
          'id': 1004,
          'hint':
              'Date of birth.',
          'name': 'dob',
          'size': 'normal',
          'label': 'Date of birth',
          'parent': 1003,
          'editable': true,
          'nodeType': 0,
          'fieldType': 9,
          'parentNode': 0,
          'visibility': {'condition': 'true'},
          'defaultValue': null,
          'conditionalBranches': [],
          'validation': {'notEmpty': true}
        },
        {
          'id': 1005,
          'hint': 'Select one',
          'name': 'sex',
          'size': 'normal',
          'label': 'Sex',
          'parent': 1004,
          'choices': [],
          'editable': true,
          'nodeType': 0,
          'fieldType': 4,
          'parentNode': 0,
          'visibility': {'condition': 'true'},
          'forceNarrow': false,
          'defaultValue': null,
          'choicesOrigin': {
            'name': 'mf',
            'type': 'fixed' as AjfChoicesOriginType,
            'label': '',
            'choices': [
              {'label': 'Male', 'value': 'M'}, {'label': 'Female', 'value': 'F'},
              {'label': 'Other/not specified', 'value': 'O'}
            ],
            'choicesType': 'string'
          },
          'forceExpanded': false,
          'choicesOriginRef': 'mf',
          'conditionalBranches': [],
          'validation': {'notEmpty': true}
        },
        {
          'id': 1006,
          'hint': 'Select all that applies. Please refer only to current citizenships',
          'name': 'citizenship',
          'size': 'normal',
          'label': 'Cityzenship',
          'parent': 1005,
          'choices': [],
          'editable': true,
          'nodeType': 0,
          'fieldType': 5,
          'parentNode': 0,
          'visibility': {'condition': 'true'},
          'forceNarrow': false,
          'defaultValue': null,
          'choicesOrigin': {
            'name': 'countries_nat',
            'type': 'fixed' as AjfChoicesOriginType,
            'label': '',
            'choices': [
              {'label': 'Afghanistan', 'value': 'AFG'},
              {'label': 'Albania', 'value': 'ALB'},
              {'label': 'Algeria', 'value': 'DZA'},
              {'label': 'American Samoa', 'value': 'ASM'},
              {'label': 'Andorra', 'value': 'AND'},
              {'label': 'Angola', 'value': 'AGO'},
              {'label': 'Anguilla', 'value': 'AIA'},
              {'label': 'Antarctica', 'value': 'ATA'},
              {'label': 'Antigua and Barbuda', 'value': 'ATG'},
              {'label': 'Argentina', 'value': 'ARG'},
              {'label': 'Armenia', 'value': 'ARM'},
              {'label': 'Aruba', 'value': 'ABW'},
              {'label': 'Australia', 'value': 'AUS'},
              {'label': 'Austria', 'value': 'AUT'},
              {'label': 'Azerbaijan', 'value': 'AZE'},
              {'label': 'Bahamas (the)', 'value': 'BHS'},
              {'label': 'Bahrain', 'value': 'BHR'},
              {'label': 'Bangladesh', 'value': 'BGD'},
              {'label': 'Barbados', 'value': 'BRB'},
              {'label': 'Belarus', 'value': 'BLR'},
              {'label': 'Belgium', 'value': 'BEL'},
              {'label': 'Belize', 'value': 'BLZ'},
              {'label': 'Benin', 'value': 'BEN'},
              {'label': 'Bermuda', 'value': 'BMU'},
              {'label': 'Bhutan', 'value': 'BTN'},
              {'label': 'Bolivia (Plurinational State of)', 'value': 'BOL'},
              {'label': 'Bonaire, Sint Eustatius and Saba', 'value': 'BES'},
              {'label': 'Bosnia and Herzegovina', 'value': 'BIH'},
              {'label': 'Botswana', 'value': 'BWA'},
              {'label': 'Bouvet Island', 'value': 'BVT'},
              {'label': 'Brazil', 'value': 'BRA'},
              {'label': 'British Indian Ocean Territory (the)', 'value': 'IOT'},
              {'label': 'Brunei Darussalam', 'value': 'BRN'},
              {'label': 'Bulgaria', 'value': 'BGR'},
              {'label': 'Burkina Faso', 'value': 'BFA'},
              {'label': 'Burundi', 'value': 'BDI'},
              {'label': 'Cabo Verde', 'value': 'CPV'},
              {'label': 'Cambodia', 'value': 'KHM'},
              {'label': 'Cameroon', 'value': 'CMR'},
              {'label': 'Canada', 'value': 'CAN'},
              {'label': 'Cayman Islands (the)', 'value': 'CYM'},
              {'label': 'Central African Republic (the)', 'value': 'CAF'},
              {'label': 'Chad', 'value': 'TCD'},
              {'label': 'Chile', 'value': 'CHL'},
              {'label': 'China', 'value': 'CHN'},
              {'label': 'Christmas Island', 'value': 'CXR'},
              {'label': 'Cocos (Keeling) Islands (the)', 'value': 'CCK'},
              {'label': 'Colombia', 'value': 'COL'},
              {'label': 'Comoros (the)', 'value': 'COM'},
              {'label': 'Congo (the Democratic Republic of the)', 'value': 'COD'},
              {'label': 'Congo (the)', 'value': 'COG'},
              {'label': 'Cook Islands (the)', 'value': 'COK'},
              {'label': 'Costa Rica', 'value': 'CRI'},
              {'label': 'Croatia', 'value': 'HRV'},
              {'label': 'Cuba', 'value': 'CUB'},
              {'label': 'Cura\u00e7ao', 'value': 'CUW'},
              {'label': 'Cyprus', 'value': 'CYP'},
              {'label': 'Czechia', 'value': 'CZE'},
              {'label': 'C\u00f4te d\'Ivoire', 'value': 'CIV'},
              {'label': 'Denmark', 'value': 'DNK'},
              {'label': 'Djibouti', 'value': 'DJI'},
              {'label': 'Dominica', 'value': 'DMA'},
              {'label': 'Dominican Republic (the)', 'value': 'DOM'},
              {'label': 'Ecuador', 'value': 'ECU'},
              {'label': 'Egypt', 'value': 'EGY'},
              {'label': 'El Salvador', 'value': 'SLV'},
              {'label': 'Equatorial Guinea', 'value': 'GNQ'},
              {'label': 'Eritrea', 'value': 'ERI'},
              {'label': 'Estonia', 'value': 'EST'},
              {'label': 'Eswatini', 'value': 'SWZ'},
              {'label': 'Ethiopia', 'value': 'ETH'},
              {'label': 'Falkland Islands (the) [Malvinas]', 'value': 'FLK'},
              {'label': 'Faroe Islands (the)', 'value': 'FRO'},
              {'label': 'Fiji', 'value': 'FJI'},
              {'label': 'Finland', 'value': 'FIN'},
              {'label': 'France', 'value': 'FRA'},
              {'label': 'French Guiana', 'value': 'GUF'},
              {'label': 'French Polynesia', 'value': 'PYF'},
              {'label': 'French Southern Territories (the)', 'value': 'ATF'},
              {'label': 'Gabon', 'value': 'GAB'},
              {'label': 'Gambia (the)', 'value': 'GMB'},
              {'label': 'Georgia', 'value': 'GEO'},
              {'label': 'Germany', 'value': 'DEU'},
              {'label': 'Ghana', 'value': 'GHA'},
              {'label': 'Gibraltar', 'value': 'GIB'},
              {'label': 'Greece', 'value': 'GRC'},
              {'label': 'Greenland', 'value': 'GRL'},
              {'label': 'Grenada', 'value': 'GRD'},
              {'label': 'Guadeloupe', 'value': 'GLP'},
              {'label': 'Guam', 'value': 'GUM'},
              {'label': 'Guatemala', 'value': 'GTM'},
              {'label': 'Guernsey', 'value': 'GGY'},
              {'label': 'Guinea', 'value': 'GIN'},
              {'label': 'Guinea-Bissau', 'value': 'GNB'},
              {'label': 'Guyana', 'value': 'GUY'},
              {'label': 'Haiti', 'value': 'HTI'},
              {'label': 'Heard Island and McDonald Islands', 'value': 'HMD'},
              {'label': 'Holy See (the)', 'value': 'VAT'},
              {'label': 'Honduras', 'value': 'HND'},
              {'label': 'Hong Kong', 'value': 'HKG'},
              {'label': 'Hungary', 'value': 'HUN'},
              {'label': 'Iceland', 'value': 'ISL'},
              {'label': 'India', 'value': 'IND'},
              {'label': 'Indonesia', 'value': 'IDN'},
              {'label': 'Iran (Islamic Republic of)', 'value': 'IRN'},
              {'label': 'Iraq', 'value': 'IRQ'},
              {'label': 'Ireland', 'value': 'IRL'},
              {'label': 'Isle of Man', 'value': 'IMN'},
              {'label': 'Israel', 'value': 'ISR'},
              {'label': 'Italy', 'value': 'ITA'},
              {'label': 'Jamaica', 'value': 'JAM'},
              {'label': 'Japan', 'value': 'JPN'},
              {'label': 'Jersey', 'value': 'JEY'},
              {'label': 'Jordan', 'value': 'JOR'},
              {'label': 'Kazakhstan', 'value': 'KAZ'},
              {'label': 'Kenya', 'value': 'KEN'},
              {'label': 'Kiribati', 'value': 'KIR'},
              {'label': 'Korea (the Democratic People\'s Republic of)', 'value': 'PRK'},
              {'label': 'Korea (the Republic of)', 'value': 'KOR'},
              {'label': 'Kuwait', 'value': 'KWT'},
              {'label': 'Kyrgyzstan', 'value': 'KGZ'},
              {'label': 'Lao People\'s Democratic Republic (the)', 'value': 'LAO'},
              {'label': 'Latvia', 'value': 'LVA'},
              {'label': 'Lebanon', 'value': 'LBN'},
              {'label': 'Lesotho', 'value': 'LSO'},
              {'label': 'Liberia', 'value': 'LBR'},
              {'label': 'Libya', 'value': 'LBY'},
              {'label': 'Liechtenstein', 'value': 'LIE'},
              {'label': 'Lithuania', 'value': 'LTU'},
              {'label': 'Luxembourg', 'value': 'LUX'},
              {'label': 'Macao', 'value': 'MAC'},
              {'label': 'Madagascar', 'value': 'MDG'},
              {'label': 'Malawi', 'value': 'MWI'},
              {'label': 'Malaysia', 'value': 'MYS'},
              {'label': 'Maldives', 'value': 'MDV'},
              {'label': 'Mali', 'value': 'MLI'},
              {'label': 'Malta', 'value': 'MLT'},
              {'label': 'Marshall Islands (the)', 'value': 'MHL'},
              {'label': 'Martinique', 'value': 'MTQ'},
              {'label': 'Mauritania', 'value': 'MRT'},
              {'label': 'Mauritius', 'value': 'MUS'},
              {'label': 'Mayotte', 'value': 'MYT'},
              {'label': 'Mexico', 'value': 'MEX'},
              {'label': 'Micronesia (Federated States of)', 'value': 'FSM'},
              {'label': 'Moldova (the Republic of)', 'value': 'MDA'},
              {'label': 'Monaco', 'value': 'MCO'},
              {'label': 'Mongolia', 'value': 'MNG'},
              {'label': 'Montenegro', 'value': 'MNE'},
              {'label': 'Montserrat', 'value': 'MSR'},
              {'label': 'Morocco', 'value': 'MAR'},
              {'label': 'Mozambique', 'value': 'MOZ'},
              {'label': 'Myanmar', 'value': 'MMR'},
              {'label': 'Namibia', 'value': 'NAM'},
              {'label': 'Nauru', 'value': 'NRU'},
              {'label': 'Nepal', 'value': 'NPL'},
              {'label': 'Netherlands (the)', 'value': 'NLD'},
              {'label': 'New Caledonia', 'value': 'NCL'},
              {'label': 'New Zealand', 'value': 'NZL'},
              {'label': 'Nicaragua', 'value': 'NIC'},
              {'label': 'Niger (the)', 'value': 'NER'},
              {'label': 'Nigeria', 'value': 'NGA'},
              {'label': 'Niue', 'value': 'NIU'},
              {'label': 'Norfolk Island', 'value': 'NFK'},
              {'label': 'Northern Mariana Islands (the)', 'value': 'MNP'},
              {'label': 'Norway', 'value': 'NOR'},
              {'label': 'Oman', 'value': 'OMN'},
              {'label': 'Pakistan', 'value': 'PAK'},
              {'label': 'Palau', 'value': 'PLW'},
              {'label': 'Palestine, State of', 'value': 'PSE'},
              {'label': 'Panama', 'value': 'PAN'},
              {'label': 'Papua New Guinea', 'value': 'PNG'},
              {'label': 'Paraguay', 'value': 'PRY'},
              {'label': 'Peru', 'value': 'PER'},
              {'label': 'Philippines (the)', 'value': 'PHL'},
              {'label': 'Pitcairn', 'value': 'PCN'},
              {'label': 'Poland', 'value': 'POL'},
              {'label': 'Portugal', 'value': 'PRT'},
              {'label': 'Puerto Rico', 'value': 'PRI'},
              {'label': 'Qatar', 'value': 'QAT'},
              {'label': 'Republic of North Macedonia', 'value': 'MKD'},
              {'label': 'Romania', 'value': 'ROU'},
              {'label': 'Russian Federation (the)', 'value': 'RUS'},
              {'label': 'Rwanda', 'value': 'RWA'},
              {'label': 'R\u00e9union', 'value': 'REU'},
              {'label': 'Saint Barth\u00e9lemy', 'value': 'BLM'},
              {'label': 'Saint Helena, Ascension and Tristan da Cunha', 'value': 'SHN'},
              {'label': 'Saint Kitts and Nevis', 'value': 'KNA'},
              {'label': 'Saint Lucia', 'value': 'LCA'},
              {'label': 'Saint Martin (French part)', 'value': 'MAF'},
              {'label': 'Saint Pierre and Miquelon', 'value': 'SPM'},
              {'label': 'Saint Vincent and the Grenadines', 'value': 'VCT'},
              {'label': 'Samoa', 'value': 'WSM'},
              {'label': 'San Marino', 'value': 'SMR'},
              {'label': 'Sao Tome and Principe', 'value': 'STP'},
              {'label': 'Saudi Arabia', 'value': 'SAU'},
              {'label': 'Senegal', 'value': 'SEN'},
              {'label': 'Serbia', 'value': 'SRB'},
              {'label': 'Seychelles', 'value': 'SYC'},
              {'label': 'Sierra Leone', 'value': 'SLE'},
              {'label': 'Singapore', 'value': 'SGP'},
              {'label': 'Sint Maarten (Dutch part)', 'value': 'SXM'},
              {'label': 'Slovakia', 'value': 'SVK'},
              {'label': 'Slovenia', 'value': 'SVN'},
              {'label': 'Solomon Islands', 'value': 'SLB'},
              {'label': 'Somalia', 'value': 'SOM'},
              {'label': 'South Africa', 'value': 'ZAF'},
              {'label': 'South Georgia and the South Sandwich Islands', 'value': 'SGS'},
              {'label': 'South Sudan', 'value': 'SSD'},
              {'label': 'Spain', 'value': 'ESP'},
              {'label': 'Sri Lanka', 'value': 'LKA'},
              {'label': 'Sudan (the)', 'value': 'SDN'},
              {'label': 'Suriname', 'value': 'SUR'},
              {'label': 'Svalbard and Jan Mayen', 'value': 'SJM'},
              {'label': 'Sweden', 'value': 'SWE'},
              {'label': 'Switzerland', 'value': 'CHE'},
              {'label': 'Syrian Arab Republic', 'value': 'SYR'},
              {'label': 'Taiwan (Province of China)', 'value': 'TWN'},
              {'label': 'Tajikistan', 'value': 'TJK'},
              {'label': 'Tanzania, United Republic of', 'value': 'TZA'},
              {'label': 'Thailand', 'value': 'THA'},
              {'label': 'Timor-Leste', 'value': 'TLS'},
              {'label': 'Togo', 'value': 'TGO'},
              {'label': 'Tokelau', 'value': 'TKL'},
              {'label': 'Tonga', 'value': 'TON'},
              {'label': 'Trinidad and Tobago', 'value': 'TTO'},
              {'label': 'Tunisia', 'value': 'TUN'},
              {'label': 'Turkey', 'value': 'TUR'},
              {'label': 'Turkmenistan', 'value': 'TKM'},
              {'label': 'Turks and Caicos Islands (the)', 'value': 'TCA'},
              {'label': 'Tuvalu', 'value': 'TUV'},
              {'label': 'Uganda', 'value': 'UGA'},
              {'label': 'Ukraine', 'value': 'UKR'},
              {'label': 'United Arab Emirates (the)', 'value': 'ARE'},
              {
                'label': 'United Kingdom of Great Britain and Northern Ireland (the)',
                'value': 'GBR'
              },
              {'label': 'United States Minor Outlying Islands (the)', 'value': 'UMI'},
              {'label': 'United States of America (the)', 'value': 'USA'},
              {'label': 'Uruguay', 'value': 'URY'},
              {'label': 'Uzbekistan', 'value': 'UZB'},
              {'label': 'Vanuatu', 'value': 'VUT'},
              {'label': 'Venezuela (Bolivarian Republic of)', 'value': 'VEN'},
              {'label': 'Viet Nam', 'value': 'VNM'},
              {'label': 'Virgin Islands (British)', 'value': 'VGB'},
              {'label': 'Virgin Islands (U.S.)', 'value': 'VIR'},
              {'label': 'Wallis and Futuna', 'value': 'WLF'},
              {'label': 'Western Sahara', 'value': 'ESH'},
              {'label': 'Yemen', 'value': 'YEM'},
              {'label': 'Zambia', 'value': 'ZMB'},
              {'label': 'Zimbabwe', 'value': 'ZWE'},
              {'label': '\u00c5land Islands', 'value': 'ALA'}
            ],
            'choicesType': 'string'
          },
          'forceExpanded': false,
          'choicesOriginRef': 'countries_nat',
          'conditionalBranches': [],
          'validation': {'notEmpty': true}
        },
        {
          'id': 1007,
          'hint': 'Select one',
          'name': 'civstat',
          'size': 'normal',
          'label': 'Civil Status',
          'parent': 1006,
          'choices': [],
          'editable': true,
          'nodeType': 0,
          'fieldType': 4,
          'parentNode': 0,
          'visibility': {'condition': 'true'},
          'forceNarrow': false,
          'defaultValue': null,
          'choicesOrigin': {
            'name': 'civstats',
            'type': 'fixed' as AjfChoicesOriginType,
            'label': '',
            'choices': [
              {'label': 'Not married', 'value': 'single'}, {'label': 'Married', 'value': 'married'},
              {'label': 'Divorced', 'value': 'divorced'}, {'label': 'Widow', 'value': 'widow'},
              {'label': 'Other/not specified', 'value': 'other'}
            ],
            'choicesType': 'string'
          },
          'forceExpanded': false,
          'choicesOriginRef': 'civstats',
          'conditionalBranches': [],
          'validation': {'notEmpty': true}
        },
        {
          'id': 1008,
          'hint':
              'Select one.',
          'name': 'edulevel',
          'size': 'normal',
          'label': 'Education level',
          'parent': 1007,
          'choices': [],
          'editable': true,
          'nodeType': 0,
          'fieldType': 4,
          'parentNode': 0,
          'visibility': {'condition': 'true'},
          'forceNarrow': false,
          'defaultValue': null,
          'choicesOrigin': {
            'name': 'edulevels',
            'type': 'fixed' as AjfChoicesOriginType,
            'label': '',
            'choices': [
              {'label': 'None', 'value': 'none'}, {'label': 'Primary school', 'value': 'prim'},
              {'label': 'Secondary', 'value': 'sec'},
              {'label': 'High School Diploma', 'value': 'high'},
              {'label': 'University degree', 'value': 'univ'},
              {'label': 'Master / Phd', 'value': 'phd'}
            ],
            'choicesType': 'string'
          },
          'forceExpanded': false,
          'choicesOriginRef': 'edulevels',
          'conditionalBranches': [],
          'validation': {'notEmpty': true}
        },
        {
          'id': 1009,
          'hint': 'Please refer to the country main identification system',
          'name': 'natid',
          'size': 'normal',
          'label': 'Fiscal Code / Unique national ID',
          'parent': 1008,
          'editable': true,
          'nodeType': 0,
          'fieldType': 0,
          'parentNode': 0,
          'visibility': {'condition': 'true'},
          'defaultValue': null,
          'conditionalBranches': [],
          'validation': {'notEmpty': true}
        },
        {
          'id': 1010,
          'hint': 'Internal WWGVC registration number, if assigned',
          'name': 'matr',
          'size': 'normal',
          'label': 'Registration number',
          'parent': 1009,
          'editable': true,
          'nodeType': 0,
          'fieldType': 0,
          'parentNode': 0,
          'visibility': {'condition': 'true'},
          'defaultValue': null,
          'conditionalBranches': [],
          'validation': {'notEmpty': true}
        }
      ],
      'parent': 0,
      'nodeType': 3,
      'parentNode': 0,
      'visibility': {'condition': 'true'},
      'conditionalBranches': [{'condition': 'true'}]
    },
    {
      'id': 2,
      'name': 'contract',
      'label': 'Contract',
      'nodes': [
        {
          'id': 2000,
          'name': '',
          'size': 'normal',
          'label': '',
          'parent': 2,
          'editable': false,
          'nodeType': 0,
          'fieldType': 7,
          'parentNode': 0,
          'visibility': {'condition': 'true'},
          'conditionalBranches': []
        },
        {
          'id': 2001,
          'hint': 'Select one',
          'name': 'area',
          'size': 'normal',
          'label': 'Functional Area',
          'parent': 2000,
          'choices': [],
          'editable': true,
          'nodeType': 0,
          'fieldType': 4,
          'parentNode': 0,
          'visibility': {'condition': 'true'},
          'forceNarrow': false,
          'defaultValue': null,
          'choicesOrigin': {
            'name': 'areas',
            'type': 'fixed' as AjfChoicesOriginType,
            'label': '',
            'choices': [
              {'label': 'Project management', 'value': 'projdev'},
              {'label': 'Administration and Human resources', 'value': 'adminhr'},
              {'label': 'Logistics and support', 'value': 'support'},
              {'label': 'Sponsorship', 'value': 'sad'},
              {'label': 'Communication and Advocacy', 'value': 'comm'}
            ],
            'choicesType': 'string'
          },
          'forceExpanded': false,
          'choicesOriginRef': 'areas',
          'conditionalBranches': [],
          'validation': {'notEmpty': true}
        },
        {
          'id': 2002,
          'hint': 'Select one',
          'name': 'position',
          'size': 'normal',
          'label': 'Type of work',
          'parent': 2001,
          'choices': [],
          'editable': true,
          'nodeType': 0,
          'fieldType': 4,
          'parentNode': 0,
          'visibility': {'condition': 'true'},
          'forceNarrow': false,
          'defaultValue': null,
          'choicesOrigin': {
            'name': 'positions',
            'type': 'fixed' as AjfChoicesOriginType,
            'label': '',
            'choices': [
              {'label': 'Manager - Responsible of areas or projects', 'value': 'manager'}, {
                'label': 'Specialist - Specialized technicians (not managers)',
                'value': 'specialist'
              },
              {'label': 'Officer - Clerks/executives', 'value': 'officer'},
              {'label': 'Support - Eg. logisticians, drivers', 'value': 'support'},
              {'label': 'Other (please specify)', 'value': 'other'}
            ],
            'choicesType': 'string'
          },
          'forceExpanded': false,
          'choicesOriginRef': 'positions',
          'conditionalBranches': [],
          'validation': {'notEmpty': true}
        },
        {
          'id': 2003,
          'name': 'other',
          'size': 'normal',
          'label': 'Please, specify',
          'parent': 2002,
          'editable': true,
          'nodeType': 0,
          'fieldType': 0,
          'parentNode': 0,
          'visibility': {'condition': 'position === \'other\''},
          'defaultValue': null,
          'conditionalBranches': [],
          'validation': {'notEmpty': true}
        },
        {
          'id': 2004,
          'hint': 'The city or field office where the person has her/his main activities',
          'name': 'city',
          'size': 'normal',
          'label': 'Place of work',
          'parent': 2003,
          'editable': true,
          'nodeType': 0,
          'fieldType': 0,
          'parentNode': 0,
          'visibility': {'condition': 'true'},
          'defaultValue': null,
          'conditionalBranches': [],
          'validation': {'notEmpty': true}
        },
        {
          'id': 2005,
          'hint': 'Select one',
          'name': 'contract_type',
          'size': 'normal',
          'label': 'Type of contract',
          'parent': 2004,
          'choices': [],
          'editable': true,
          'nodeType': 0,
          'fieldType': 4,
          'parentNode': 0,
          'visibility': {'condition': 'true'},
          'forceNarrow': false,
          'defaultValue': null,
          'choicesOrigin': {
            'name': 'contracts',
            'type': 'fixed' as AjfChoicesOriginType,
            'label': '',
            'choices': [
              {'label': 'Staff - Permanent', 'value': 'staff_permanent'},
              {'label': 'Staff - Fixed term', 'value': 'staff_fixed'},
              {'label': 'Collaborator', 'value': 'collab'},
              {'label': 'Consultant', 'value': 'consultant'},
              {'label': 'Volunteer', 'value': 'volunteer'}, {'label': 'Intern', 'value': 'intern'}
            ],
            'choicesType': 'string'
          },
          'forceExpanded': false,
          'choicesOriginRef': 'contracts',
          'conditionalBranches': [],
          'validation': {'notEmpty': true}
        },
        {
          'id': 2006,
          'hint': 'If the person has a reduced time contract',
          'name': 'parttime',
          'size': 'normal',
          'label': 'Part-time contract',
          'parent': 2005,
          'editable': true,
          'nodeType': 0,
          'fieldType': 3,
          'parentNode': 0,
          'visibility': {'condition': 'true'},
          'defaultValue': false,
          'conditionalBranches': [],
          'validation': {'notEmpty': true}
        },
        {
          'id': 2007,
          'hint':
              'The percentage of employment.',
          'name': 'parttime_perc',
          'size': 'normal',
          'label': 'Part-time %',
          'parent': 2006,
          'editable': true,
          'nodeType': 0,
          'fieldType': 2,
          'parentNode': 0,
          'validation': {
            'conditions': [{
              'condition': '!notEmpty(parttime_perc) || isInt(parttime_perc)',
              'errorMessage': 'The field value must be an integer.',
              'clientValidation': true
            }],
            'notEmpty': true
          },
          'visibility': {'condition': 'parttime === true'},
          'defaultValue': null,
          'conditionalBranches': []
        },
        {
          'id': 2008,
          'hint': 'Date when the contract started',
          'name': 'date_start',
          'size': 'normal',
          'label': 'Date contract started',
          'parent': 2007,
          'editable': true,
          'nodeType': 0,
          'fieldType': 9,
          'parentNode': 0,
          'visibility': {'condition': 'true'},
          'defaultValue': null,
          'conditionalBranches': [],
          'validation': {'notEmpty': true}
        },
        {
          'id': 2009,
          'hint': 'Date when the contract ended',
          'name': 'date_end',
          'size': 'normal',
          'label': 'Date contract ended',
          'parent': 2008,
          'editable': true,
          'nodeType': 0,
          'fieldType': 9,
          'parentNode': 0,
          'visibility': {'condition': 'true'},
          'defaultValue': null,
          'conditionalBranches': []
        },
        {
          'id': 2010,
          'name': 'reason',
          'size': 'normal',
          'label': 'Reason form termination',
          'parent': 2009,
          'choices': [],
          'editable': true,
          'nodeType': 0,
          'fieldType': 4,
          'parentNode': 0,
          'visibility': {'condition': 'true'},
          'forceNarrow': false,
          'defaultValue': null,
          'choicesOrigin': {
            'name': 'reasons',
            'type': 'fixed' as AjfChoicesOriginType,
            'label': '',
            'choices': [
              {'label': 'Natural contract termination', 'value': 'natural'},
              {'label': 'Decision taken by WWGVC', 'value': 'byorg'},
              {'label': 'Decision taken by employee', 'value': 'bystaff'}
            ],
            'choicesType': 'string'
          },
          'forceExpanded': false,
          'choicesOriginRef': 'reasons',
          'conditionalBranches': []
        }
      ],
      'parent': 1,
      'maxReps': 0,
      'minReps': 1,
      'nodeType': 4,
      'parentNode': 0,
      'visibility': {'condition': 'true'},
      'conditionalBranches': [{'condition': 'true'}]
    },
    {
      'id': 3,
      'name': 'training',
      'label': 'Training',
      'nodes': [
        {
          'id': 3000,
          'name': '',
          'size': 'normal',
          'label': '',
          'parent': 3,
          'editable': false,
          'nodeType': 0,
          'fieldType': 7,
          'parentNode': 0,
          'visibility': {'condition': 'true'},
          'conditionalBranches': []
        },
        {
          'id': 3001,
          'hint': 'The number of different trainings attended, regardless their duration',
          'name': 'ntrainings',
          'size': 'normal',
          'label': 'Number of different trainings attended during this year',
          'parent': 3000,
          'editable': true,
          'nodeType': 0,
          'fieldType': 2,
          'parentNode': 0,
          'validation': {
            'conditions': [{
              'condition': '!notEmpty(ntrainings) || isInt(ntrainings)',
              'errorMessage': 'The field value must be an integer.',
              'clientValidation': true
            }],
            'notEmpty': true
          },
          'visibility': {'condition': 'true'},
          'defaultValue': null,
          'conditionalBranches': []
        },
        {
          'id': 3002,
          'hint': 'Covering all different trainings combined together',
          'name': 'nhourstraining',
          'size': 'normal',
          'label': 'Total number of days of training during this year',
          'parent': 3001,
          'warning': {'conditions': []},
          'editable': true,
          'nodeType': 0,
          'fieldType': 2,
          'parentNode': 0,
          'validation': {
            'conditions': [
              {
                'condition': '!notEmpty(nhourstraining) || isInt(nhourstraining)',
                'errorMessage': 'The field value must be an integer.',
                'clientValidation': false
              },
              {
                'condition': '(nhourstraining >= ntrainings)',
                'errorMessage':
                    'Number of days should be greater or equal to the number of trainings',
                'clientValidation': false
              }
            ],
            'notEmpty': true
          },
          'visibility': {'condition': 'true'},
          'description': null,
          'defaultValue': null,
          'conditionalBranches': []
        }
      ],
      'parent': 2,
      'nodeType': 3,
      'parentNode': 0,
      'visibility': {'condition': 'true'},
      'conditionalBranches': [{'condition': 'true'}]
    }
  ],
  'initContext': {},
  'choicesOrigins': [
    {
      'name': 'areas',
      'type': 'fixed' as AjfChoicesOriginType,
      'label': '',
      'choices': [
        {'label': 'Project management', 'value': 'projdev'},
        {'label': 'Administration and Human resources', 'value': 'adminhr'},
        {'label': 'Logistics and support', 'value': 'support'},
        {'label': 'Sponsorship', 'value': 'sad'},
        {'label': 'Communication and Advocacy', 'value': 'comm'}
      ],
      'choicesType': 'string'
    },
    {
      'name': 'civstats',
      'type': 'fixed' as AjfChoicesOriginType,
      'label': '',
      'choices': [
        {'label': 'Not married', 'value': 'single'}, {'label': 'Married', 'value': 'married'},
        {'label': 'Divorced', 'value': 'divorced'}, {'label': 'Widow', 'value': 'widow'},
        {'label': 'Other/not specified', 'value': 'other'}
      ],
      'choicesType': 'string'
    },
    {
      'name': 'contracts',
      'type': 'fixed' as AjfChoicesOriginType,
      'label': '',
      'choices': [
        {'label': 'Staff - Permanent', 'value': 'staff_permanent'},
        {'label': 'Staff - Fixed term', 'value': 'staff_fixed'},
        {'label': 'Collaborator', 'value': 'collab'},
        {'label': 'Consultant', 'value': 'consultant'},
        {'label': 'Volunteer', 'value': 'volunteer'}, {'label': 'Intern', 'value': 'intern'}
      ],
      'choicesType': 'string'
    },
    {
      'name': 'countries',
      'type': 'fixed' as AjfChoicesOriginType,
      'label': '',
      'choices': [
        {'label': 'Afghanistan', 'value': 'AFG'},
        {'label': 'Albania', 'value': 'ALB'},
        {'label': 'Algeria', 'value': 'DZA'},
        {'label': 'American Samoa', 'value': 'ASM'},
        {'label': 'Andorra', 'value': 'AND'},
        {'label': 'Angola', 'value': 'AGO'},
        {'label': 'Anguilla', 'value': 'AIA'},
        {'label': 'Antarctica', 'value': 'ATA'},
        {'label': 'Antigua and Barbuda', 'value': 'ATG'},
        {'label': 'Argentina', 'value': 'ARG'},
        {'label': 'Armenia', 'value': 'ARM'},
        {'label': 'Aruba', 'value': 'ABW'},
        {'label': 'Australia', 'value': 'AUS'},
        {'label': 'Austria', 'value': 'AUT'},
        {'label': 'Azerbaijan', 'value': 'AZE'},
        {'label': 'Bahamas (the)', 'value': 'BHS'},
        {'label': 'Bahrain', 'value': 'BHR'},
        {'label': 'Bangladesh', 'value': 'BGD'},
        {'label': 'Barbados', 'value': 'BRB'},
        {'label': 'Belarus', 'value': 'BLR'},
        {'label': 'Belgium', 'value': 'BEL'},
        {'label': 'Belize', 'value': 'BLZ'},
        {'label': 'Benin', 'value': 'BEN'},
        {'label': 'Bermuda', 'value': 'BMU'},
        {'label': 'Bhutan', 'value': 'BTN'},
        {'label': 'Bolivia (Plurinational State of)', 'value': 'BOL'},
        {'label': 'Bonaire, Sint Eustatius and Saba', 'value': 'BES'},
        {'label': 'Bosnia and Herzegovina', 'value': 'BIH'},
        {'label': 'Botswana', 'value': 'BWA'},
        {'label': 'Bouvet Island', 'value': 'BVT'},
        {'label': 'Brazil', 'value': 'BRA'},
        {'label': 'British Indian Ocean Territory (the)', 'value': 'IOT'},
        {'label': 'Brunei Darussalam', 'value': 'BRN'},
        {'label': 'Bulgaria', 'value': 'BGR'},
        {'label': 'Burkina Faso', 'value': 'BFA'},
        {'label': 'Burundi', 'value': 'BDI'},
        {'label': 'Cabo Verde', 'value': 'CPV'},
        {'label': 'Cambodia', 'value': 'KHM'},
        {'label': 'Cameroon', 'value': 'CMR'},
        {'label': 'Canada', 'value': 'CAN'},
        {'label': 'Cayman Islands (the)', 'value': 'CYM'},
        {'label': 'Central African Republic (the)', 'value': 'CAF'},
        {'label': 'Chad', 'value': 'TCD'},
        {'label': 'Chile', 'value': 'CHL'},
        {'label': 'China', 'value': 'CHN'},
        {'label': 'Christmas Island', 'value': 'CXR'},
        {'label': 'Cocos (Keeling) Islands (the)', 'value': 'CCK'},
        {'label': 'Colombia', 'value': 'COL'},
        {'label': 'Comoros (the)', 'value': 'COM'},
        {'label': 'Congo (the Democratic Republic of the)', 'value': 'COD'},
        {'label': 'Congo (the)', 'value': 'COG'},
        {'label': 'Cook Islands (the)', 'value': 'COK'},
        {'label': 'Costa Rica', 'value': 'CRI'},
        {'label': 'Croatia', 'value': 'HRV'},
        {'label': 'Cuba', 'value': 'CUB'},
        {'label': 'Cura\u00e7ao', 'value': 'CUW'},
        {'label': 'Cyprus', 'value': 'CYP'},
        {'label': 'Czechia', 'value': 'CZE'},
        {'label': 'C\u00f4te d\'Ivoire', 'value': 'CIV'},
        {'label': 'Denmark', 'value': 'DNK'},
        {'label': 'Djibouti', 'value': 'DJI'},
        {'label': 'Dominica', 'value': 'DMA'},
        {'label': 'Dominican Republic (the)', 'value': 'DOM'},
        {'label': 'Ecuador', 'value': 'ECU'},
        {'label': 'Egypt', 'value': 'EGY'},
        {'label': 'El Salvador', 'value': 'SLV'},
        {'label': 'Equatorial Guinea', 'value': 'GNQ'},
        {'label': 'Eritrea', 'value': 'ERI'},
        {'label': 'Estonia', 'value': 'EST'},
        {'label': 'Eswatini', 'value': 'SWZ'},
        {'label': 'Ethiopia', 'value': 'ETH'},
        {'label': 'Falkland Islands (the) [Malvinas]', 'value': 'FLK'},
        {'label': 'Faroe Islands (the)', 'value': 'FRO'},
        {'label': 'Fiji', 'value': 'FJI'},
        {'label': 'Finland', 'value': 'FIN'},
        {'label': 'France', 'value': 'FRA'},
        {'label': 'French Guiana', 'value': 'GUF'},
        {'label': 'French Polynesia', 'value': 'PYF'},
        {'label': 'French Southern Territories (the)', 'value': 'ATF'},
        {'label': 'Gabon', 'value': 'GAB'},
        {'label': 'Gambia (the)', 'value': 'GMB'},
        {'label': 'Georgia', 'value': 'GEO'},
        {'label': 'Germany', 'value': 'DEU'},
        {'label': 'Ghana', 'value': 'GHA'},
        {'label': 'Gibraltar', 'value': 'GIB'},
        {'label': 'Greece', 'value': 'GRC'},
        {'label': 'Greenland', 'value': 'GRL'},
        {'label': 'Grenada', 'value': 'GRD'},
        {'label': 'Guadeloupe', 'value': 'GLP'},
        {'label': 'Guam', 'value': 'GUM'},
        {'label': 'Guatemala', 'value': 'GTM'},
        {'label': 'Guernsey', 'value': 'GGY'},
        {'label': 'Guinea', 'value': 'GIN'},
        {'label': 'Guinea-Bissau', 'value': 'GNB'},
        {'label': 'Guyana', 'value': 'GUY'},
        {'label': 'Haiti', 'value': 'HTI'},
        {'label': 'Heard Island and McDonald Islands', 'value': 'HMD'},
        {'label': 'Holy See (the)', 'value': 'VAT'},
        {'label': 'Honduras', 'value': 'HND'},
        {'label': 'Hong Kong', 'value': 'HKG'},
        {'label': 'Hungary', 'value': 'HUN'},
        {'label': 'Iceland', 'value': 'ISL'},
        {'label': 'India', 'value': 'IND'},
        {'label': 'Indonesia', 'value': 'IDN'},
        {'label': 'Iran (Islamic Republic of)', 'value': 'IRN'},
        {'label': 'Iraq', 'value': 'IRQ'},
        {'label': 'Ireland', 'value': 'IRL'},
        {'label': 'Isle of Man', 'value': 'IMN'},
        {'label': 'Israel', 'value': 'ISR'},
        {'label': 'Italy', 'value': 'ITA'},
        {'label': 'Jamaica', 'value': 'JAM'},
        {'label': 'Japan', 'value': 'JPN'},
        {'label': 'Jersey', 'value': 'JEY'},
        {'label': 'Jordan', 'value': 'JOR'},
        {'label': 'Kazakhstan', 'value': 'KAZ'},
        {'label': 'Kenya', 'value': 'KEN'},
        {'label': 'Kiribati', 'value': 'KIR'},
        {'label': 'Korea (the Democratic People\'s Republic of)', 'value': 'PRK'},
        {'label': 'Korea (the Republic of)', 'value': 'KOR'},
        {'label': 'Kuwait', 'value': 'KWT'},
        {'label': 'Kyrgyzstan', 'value': 'KGZ'},
        {'label': 'Lao People\'s Democratic Republic (the)', 'value': 'LAO'},
        {'label': 'Latvia', 'value': 'LVA'},
        {'label': 'Lebanon', 'value': 'LBN'},
        {'label': 'Lesotho', 'value': 'LSO'},
        {'label': 'Liberia', 'value': 'LBR'},
        {'label': 'Libya', 'value': 'LBY'},
        {'label': 'Liechtenstein', 'value': 'LIE'},
        {'label': 'Lithuania', 'value': 'LTU'},
        {'label': 'Luxembourg', 'value': 'LUX'},
        {'label': 'Macao', 'value': 'MAC'},
        {'label': 'Madagascar', 'value': 'MDG'},
        {'label': 'Malawi', 'value': 'MWI'},
        {'label': 'Malaysia', 'value': 'MYS'},
        {'label': 'Maldives', 'value': 'MDV'},
        {'label': 'Mali', 'value': 'MLI'},
        {'label': 'Malta', 'value': 'MLT'},
        {'label': 'Marshall Islands (the)', 'value': 'MHL'},
        {'label': 'Martinique', 'value': 'MTQ'},
        {'label': 'Mauritania', 'value': 'MRT'},
        {'label': 'Mauritius', 'value': 'MUS'},
        {'label': 'Mayotte', 'value': 'MYT'},
        {'label': 'Mexico', 'value': 'MEX'},
        {'label': 'Micronesia (Federated States of)', 'value': 'FSM'},
        {'label': 'Moldova (the Republic of)', 'value': 'MDA'},
        {'label': 'Monaco', 'value': 'MCO'},
        {'label': 'Mongolia', 'value': 'MNG'},
        {'label': 'Montenegro', 'value': 'MNE'},
        {'label': 'Montserrat', 'value': 'MSR'},
        {'label': 'Morocco', 'value': 'MAR'},
        {'label': 'Mozambique', 'value': 'MOZ'},
        {'label': 'Myanmar', 'value': 'MMR'},
        {'label': 'Namibia', 'value': 'NAM'},
        {'label': 'Nauru', 'value': 'NRU'},
        {'label': 'Nepal', 'value': 'NPL'},
        {'label': 'Netherlands (the)', 'value': 'NLD'},
        {'label': 'New Caledonia', 'value': 'NCL'},
        {'label': 'New Zealand', 'value': 'NZL'},
        {'label': 'Nicaragua', 'value': 'NIC'},
        {'label': 'Niger (the)', 'value': 'NER'},
        {'label': 'Nigeria', 'value': 'NGA'},
        {'label': 'Niue', 'value': 'NIU'},
        {'label': 'Norfolk Island', 'value': 'NFK'},
        {'label': 'Northern Mariana Islands (the)', 'value': 'MNP'},
        {'label': 'Norway', 'value': 'NOR'},
        {'label': 'Oman', 'value': 'OMN'},
        {'label': 'Pakistan', 'value': 'PAK'},
        {'label': 'Palau', 'value': 'PLW'},
        {'label': 'Palestine, State of', 'value': 'PSE'},
        {'label': 'Panama', 'value': 'PAN'},
        {'label': 'Papua New Guinea', 'value': 'PNG'},
        {'label': 'Paraguay', 'value': 'PRY'},
        {'label': 'Peru', 'value': 'PER'},
        {'label': 'Philippines (the)', 'value': 'PHL'},
        {'label': 'Pitcairn', 'value': 'PCN'},
        {'label': 'Poland', 'value': 'POL'},
        {'label': 'Portugal', 'value': 'PRT'},
        {'label': 'Puerto Rico', 'value': 'PRI'},
        {'label': 'Qatar', 'value': 'QAT'},
        {'label': 'Republic of North Macedonia', 'value': 'MKD'},
        {'label': 'Romania', 'value': 'ROU'},
        {'label': 'Russian Federation (the)', 'value': 'RUS'},
        {'label': 'Rwanda', 'value': 'RWA'},
        {'label': 'R\u00e9union', 'value': 'REU'},
        {'label': 'Saint Barth\u00e9lemy', 'value': 'BLM'},
        {'label': 'Saint Helena, Ascension and Tristan da Cunha', 'value': 'SHN'},
        {'label': 'Saint Kitts and Nevis', 'value': 'KNA'},
        {'label': 'Saint Lucia', 'value': 'LCA'},
        {'label': 'Saint Martin (French part)', 'value': 'MAF'},
        {'label': 'Saint Pierre and Miquelon', 'value': 'SPM'},
        {'label': 'Saint Vincent and the Grenadines', 'value': 'VCT'},
        {'label': 'Samoa', 'value': 'WSM'},
        {'label': 'San Marino', 'value': 'SMR'},
        {'label': 'Sao Tome and Principe', 'value': 'STP'},
        {'label': 'Saudi Arabia', 'value': 'SAU'},
        {'label': 'Senegal', 'value': 'SEN'},
        {'label': 'Serbia', 'value': 'SRB'},
        {'label': 'Seychelles', 'value': 'SYC'},
        {'label': 'Sierra Leone', 'value': 'SLE'},
        {'label': 'Singapore', 'value': 'SGP'},
        {'label': 'Sint Maarten (Dutch part)', 'value': 'SXM'},
        {'label': 'Slovakia', 'value': 'SVK'},
        {'label': 'Slovenia', 'value': 'SVN'},
        {'label': 'Solomon Islands', 'value': 'SLB'},
        {'label': 'Somalia', 'value': 'SOM'},
        {'label': 'South Africa', 'value': 'ZAF'},
        {'label': 'South Georgia and the South Sandwich Islands', 'value': 'SGS'},
        {'label': 'South Sudan', 'value': 'SSD'},
        {'label': 'Spain', 'value': 'ESP'},
        {'label': 'Sri Lanka', 'value': 'LKA'},
        {'label': 'Sudan (the)', 'value': 'SDN'},
        {'label': 'Suriname', 'value': 'SUR'},
        {'label': 'Svalbard and Jan Mayen', 'value': 'SJM'},
        {'label': 'Sweden', 'value': 'SWE'},
        {'label': 'Switzerland', 'value': 'CHE'},
        {'label': 'Syrian Arab Republic', 'value': 'SYR'},
        {'label': 'Taiwan (Province of China)', 'value': 'TWN'},
        {'label': 'Tajikistan', 'value': 'TJK'},
        {'label': 'Tanzania, United Republic of', 'value': 'TZA'},
        {'label': 'Thailand', 'value': 'THA'},
        {'label': 'Timor-Leste', 'value': 'TLS'},
        {'label': 'Togo', 'value': 'TGO'},
        {'label': 'Tokelau', 'value': 'TKL'},
        {'label': 'Tonga', 'value': 'TON'},
        {'label': 'Trinidad and Tobago', 'value': 'TTO'},
        {'label': 'Tunisia', 'value': 'TUN'},
        {'label': 'Turkey', 'value': 'TUR'},
        {'label': 'Turkmenistan', 'value': 'TKM'},
        {'label': 'Turks and Caicos Islands (the)', 'value': 'TCA'},
        {'label': 'Tuvalu', 'value': 'TUV'},
        {'label': 'Uganda', 'value': 'UGA'},
        {'label': 'Ukraine', 'value': 'UKR'},
        {'label': 'United Arab Emirates (the)', 'value': 'ARE'},
        {'label': 'United Kingdom of Great Britain and Northern Ireland (the)', 'value': 'GBR'},
        {'label': 'United States Minor Outlying Islands (the)', 'value': 'UMI'},
        {'label': 'United States of America (the)', 'value': 'USA'},
        {'label': 'Uruguay', 'value': 'URY'},
        {'label': 'Uzbekistan', 'value': 'UZB'},
        {'label': 'Vanuatu', 'value': 'VUT'},
        {'label': 'Venezuela (Bolivarian Republic of)', 'value': 'VEN'},
        {'label': 'Viet Nam', 'value': 'VNM'},
        {'label': 'Virgin Islands (British)', 'value': 'VGB'},
        {'label': 'Virgin Islands (U.S.)', 'value': 'VIR'},
        {'label': 'Wallis and Futuna', 'value': 'WLF'},
        {'label': 'Western Sahara', 'value': 'ESH'},
        {'label': 'Yemen', 'value': 'YEM'},
        {'label': 'Zambia', 'value': 'ZMB'},
        {'label': 'Zimbabwe', 'value': 'ZWE'},
        {'label': '\u00c5land Islands', 'value': 'ALA'}
      ],
      'choicesType': 'string'
    },
    {
      'name': 'countries_nat',
      'type': 'fixed' as AjfChoicesOriginType,
      'label': '',
      'choices': [
        {'label': 'Afghanistan', 'value': 'AFG'},
        {'label': 'Albania', 'value': 'ALB'},
        {'label': 'Algeria', 'value': 'DZA'},
        {'label': 'American Samoa', 'value': 'ASM'},
        {'label': 'Andorra', 'value': 'AND'},
        {'label': 'Angola', 'value': 'AGO'},
        {'label': 'Anguilla', 'value': 'AIA'},
        {'label': 'Antarctica', 'value': 'ATA'},
        {'label': 'Antigua and Barbuda', 'value': 'ATG'},
        {'label': 'Argentina', 'value': 'ARG'},
        {'label': 'Armenia', 'value': 'ARM'},
        {'label': 'Aruba', 'value': 'ABW'},
        {'label': 'Australia', 'value': 'AUS'},
        {'label': 'Austria', 'value': 'AUT'},
        {'label': 'Azerbaijan', 'value': 'AZE'},
        {'label': 'Bahamas (the)', 'value': 'BHS'},
        {'label': 'Bahrain', 'value': 'BHR'},
        {'label': 'Bangladesh', 'value': 'BGD'},
        {'label': 'Barbados', 'value': 'BRB'},
        {'label': 'Belarus', 'value': 'BLR'},
        {'label': 'Belgium', 'value': 'BEL'},
        {'label': 'Belize', 'value': 'BLZ'},
        {'label': 'Benin', 'value': 'BEN'},
        {'label': 'Bermuda', 'value': 'BMU'},
        {'label': 'Bhutan', 'value': 'BTN'},
        {'label': 'Bolivia (Plurinational State of)', 'value': 'BOL'},
        {'label': 'Bonaire, Sint Eustatius and Saba', 'value': 'BES'},
        {'label': 'Bosnia and Herzegovina', 'value': 'BIH'},
        {'label': 'Botswana', 'value': 'BWA'},
        {'label': 'Bouvet Island', 'value': 'BVT'},
        {'label': 'Brazil', 'value': 'BRA'},
        {'label': 'British Indian Ocean Territory (the)', 'value': 'IOT'},
        {'label': 'Brunei Darussalam', 'value': 'BRN'},
        {'label': 'Bulgaria', 'value': 'BGR'},
        {'label': 'Burkina Faso', 'value': 'BFA'},
        {'label': 'Burundi', 'value': 'BDI'},
        {'label': 'Cabo Verde', 'value': 'CPV'},
        {'label': 'Cambodia', 'value': 'KHM'},
        {'label': 'Cameroon', 'value': 'CMR'},
        {'label': 'Canada', 'value': 'CAN'},
        {'label': 'Cayman Islands (the)', 'value': 'CYM'},
        {'label': 'Central African Republic (the)', 'value': 'CAF'},
        {'label': 'Chad', 'value': 'TCD'},
        {'label': 'Chile', 'value': 'CHL'},
        {'label': 'China', 'value': 'CHN'},
        {'label': 'Christmas Island', 'value': 'CXR'},
        {'label': 'Cocos (Keeling) Islands (the)', 'value': 'CCK'},
        {'label': 'Colombia', 'value': 'COL'},
        {'label': 'Comoros (the)', 'value': 'COM'},
        {'label': 'Congo (the Democratic Republic of the)', 'value': 'COD'},
        {'label': 'Congo (the)', 'value': 'COG'},
        {'label': 'Cook Islands (the)', 'value': 'COK'},
        {'label': 'Costa Rica', 'value': 'CRI'},
        {'label': 'Croatia', 'value': 'HRV'},
        {'label': 'Cuba', 'value': 'CUB'},
        {'label': 'Cura\u00e7ao', 'value': 'CUW'},
        {'label': 'Cyprus', 'value': 'CYP'},
        {'label': 'Czechia', 'value': 'CZE'},
        {'label': 'C\u00f4te d\'Ivoire', 'value': 'CIV'},
        {'label': 'Denmark', 'value': 'DNK'},
        {'label': 'Djibouti', 'value': 'DJI'},
        {'label': 'Dominica', 'value': 'DMA'},
        {'label': 'Dominican Republic (the)', 'value': 'DOM'},
        {'label': 'Ecuador', 'value': 'ECU'},
        {'label': 'Egypt', 'value': 'EGY'},
        {'label': 'El Salvador', 'value': 'SLV'},
        {'label': 'Equatorial Guinea', 'value': 'GNQ'},
        {'label': 'Eritrea', 'value': 'ERI'},
        {'label': 'Estonia', 'value': 'EST'},
        {'label': 'Eswatini', 'value': 'SWZ'},
        {'label': 'Ethiopia', 'value': 'ETH'},
        {'label': 'Falkland Islands (the) [Malvinas]', 'value': 'FLK'},
        {'label': 'Faroe Islands (the)', 'value': 'FRO'},
        {'label': 'Fiji', 'value': 'FJI'},
        {'label': 'Finland', 'value': 'FIN'},
        {'label': 'France', 'value': 'FRA'},
        {'label': 'French Guiana', 'value': 'GUF'},
        {'label': 'French Polynesia', 'value': 'PYF'},
        {'label': 'French Southern Territories (the)', 'value': 'ATF'},
        {'label': 'Gabon', 'value': 'GAB'},
        {'label': 'Gambia (the)', 'value': 'GMB'},
        {'label': 'Georgia', 'value': 'GEO'},
        {'label': 'Germany', 'value': 'DEU'},
        {'label': 'Ghana', 'value': 'GHA'},
        {'label': 'Gibraltar', 'value': 'GIB'},
        {'label': 'Greece', 'value': 'GRC'},
        {'label': 'Greenland', 'value': 'GRL'},
        {'label': 'Grenada', 'value': 'GRD'},
        {'label': 'Guadeloupe', 'value': 'GLP'},
        {'label': 'Guam', 'value': 'GUM'},
        {'label': 'Guatemala', 'value': 'GTM'},
        {'label': 'Guernsey', 'value': 'GGY'},
        {'label': 'Guinea', 'value': 'GIN'},
        {'label': 'Guinea-Bissau', 'value': 'GNB'},
        {'label': 'Guyana', 'value': 'GUY'},
        {'label': 'Haiti', 'value': 'HTI'},
        {'label': 'Heard Island and McDonald Islands', 'value': 'HMD'},
        {'label': 'Holy See (the)', 'value': 'VAT'},
        {'label': 'Honduras', 'value': 'HND'},
        {'label': 'Hong Kong', 'value': 'HKG'},
        {'label': 'Hungary', 'value': 'HUN'},
        {'label': 'Iceland', 'value': 'ISL'},
        {'label': 'India', 'value': 'IND'},
        {'label': 'Indonesia', 'value': 'IDN'},
        {'label': 'Iran (Islamic Republic of)', 'value': 'IRN'},
        {'label': 'Iraq', 'value': 'IRQ'},
        {'label': 'Ireland', 'value': 'IRL'},
        {'label': 'Isle of Man', 'value': 'IMN'},
        {'label': 'Israel', 'value': 'ISR'},
        {'label': 'Italy', 'value': 'ITA'},
        {'label': 'Jamaica', 'value': 'JAM'},
        {'label': 'Japan', 'value': 'JPN'},
        {'label': 'Jersey', 'value': 'JEY'},
        {'label': 'Jordan', 'value': 'JOR'},
        {'label': 'Kazakhstan', 'value': 'KAZ'},
        {'label': 'Kenya', 'value': 'KEN'},
        {'label': 'Kiribati', 'value': 'KIR'},
        {'label': 'Korea (the Democratic People\'s Republic of)', 'value': 'PRK'},
        {'label': 'Korea (the Republic of)', 'value': 'KOR'},
        {'label': 'Kuwait', 'value': 'KWT'},
        {'label': 'Kyrgyzstan', 'value': 'KGZ'},
        {'label': 'Lao People\'s Democratic Republic (the)', 'value': 'LAO'},
        {'label': 'Latvia', 'value': 'LVA'},
        {'label': 'Lebanon', 'value': 'LBN'},
        {'label': 'Lesotho', 'value': 'LSO'},
        {'label': 'Liberia', 'value': 'LBR'},
        {'label': 'Libya', 'value': 'LBY'},
        {'label': 'Liechtenstein', 'value': 'LIE'},
        {'label': 'Lithuania', 'value': 'LTU'},
        {'label': 'Luxembourg', 'value': 'LUX'},
        {'label': 'Macao', 'value': 'MAC'},
        {'label': 'Madagascar', 'value': 'MDG'},
        {'label': 'Malawi', 'value': 'MWI'},
        {'label': 'Malaysia', 'value': 'MYS'},
        {'label': 'Maldives', 'value': 'MDV'},
        {'label': 'Mali', 'value': 'MLI'},
        {'label': 'Malta', 'value': 'MLT'},
        {'label': 'Marshall Islands (the)', 'value': 'MHL'},
        {'label': 'Martinique', 'value': 'MTQ'},
        {'label': 'Mauritania', 'value': 'MRT'},
        {'label': 'Mauritius', 'value': 'MUS'},
        {'label': 'Mayotte', 'value': 'MYT'},
        {'label': 'Mexico', 'value': 'MEX'},
        {'label': 'Micronesia (Federated States of)', 'value': 'FSM'},
        {'label': 'Moldova (the Republic of)', 'value': 'MDA'},
        {'label': 'Monaco', 'value': 'MCO'},
        {'label': 'Mongolia', 'value': 'MNG'},
        {'label': 'Montenegro', 'value': 'MNE'},
        {'label': 'Montserrat', 'value': 'MSR'},
        {'label': 'Morocco', 'value': 'MAR'},
        {'label': 'Mozambique', 'value': 'MOZ'},
        {'label': 'Myanmar', 'value': 'MMR'},
        {'label': 'Namibia', 'value': 'NAM'},
        {'label': 'Nauru', 'value': 'NRU'},
        {'label': 'Nepal', 'value': 'NPL'},
        {'label': 'Netherlands (the)', 'value': 'NLD'},
        {'label': 'New Caledonia', 'value': 'NCL'},
        {'label': 'New Zealand', 'value': 'NZL'},
        {'label': 'Nicaragua', 'value': 'NIC'},
        {'label': 'Niger (the)', 'value': 'NER'},
        {'label': 'Nigeria', 'value': 'NGA'},
        {'label': 'Niue', 'value': 'NIU'},
        {'label': 'Norfolk Island', 'value': 'NFK'},
        {'label': 'Northern Mariana Islands (the)', 'value': 'MNP'},
        {'label': 'Norway', 'value': 'NOR'},
        {'label': 'Oman', 'value': 'OMN'},
        {'label': 'Pakistan', 'value': 'PAK'},
        {'label': 'Palau', 'value': 'PLW'},
        {'label': 'Palestine, State of', 'value': 'PSE'},
        {'label': 'Panama', 'value': 'PAN'},
        {'label': 'Papua New Guinea', 'value': 'PNG'},
        {'label': 'Paraguay', 'value': 'PRY'},
        {'label': 'Peru', 'value': 'PER'},
        {'label': 'Philippines (the)', 'value': 'PHL'},
        {'label': 'Pitcairn', 'value': 'PCN'},
        {'label': 'Poland', 'value': 'POL'},
        {'label': 'Portugal', 'value': 'PRT'},
        {'label': 'Puerto Rico', 'value': 'PRI'},
        {'label': 'Qatar', 'value': 'QAT'},
        {'label': 'Republic of North Macedonia', 'value': 'MKD'},
        {'label': 'Romania', 'value': 'ROU'},
        {'label': 'Russian Federation (the)', 'value': 'RUS'},
        {'label': 'Rwanda', 'value': 'RWA'},
        {'label': 'R\u00e9union', 'value': 'REU'},
        {'label': 'Saint Barth\u00e9lemy', 'value': 'BLM'},
        {'label': 'Saint Helena, Ascension and Tristan da Cunha', 'value': 'SHN'},
        {'label': 'Saint Kitts and Nevis', 'value': 'KNA'},
        {'label': 'Saint Lucia', 'value': 'LCA'},
        {'label': 'Saint Martin (French part)', 'value': 'MAF'},
        {'label': 'Saint Pierre and Miquelon', 'value': 'SPM'},
        {'label': 'Saint Vincent and the Grenadines', 'value': 'VCT'},
        {'label': 'Samoa', 'value': 'WSM'},
        {'label': 'San Marino', 'value': 'SMR'},
        {'label': 'Sao Tome and Principe', 'value': 'STP'},
        {'label': 'Saudi Arabia', 'value': 'SAU'},
        {'label': 'Senegal', 'value': 'SEN'},
        {'label': 'Serbia', 'value': 'SRB'},
        {'label': 'Seychelles', 'value': 'SYC'},
        {'label': 'Sierra Leone', 'value': 'SLE'},
        {'label': 'Singapore', 'value': 'SGP'},
        {'label': 'Sint Maarten (Dutch part)', 'value': 'SXM'},
        {'label': 'Slovakia', 'value': 'SVK'},
        {'label': 'Slovenia', 'value': 'SVN'},
        {'label': 'Solomon Islands', 'value': 'SLB'},
        {'label': 'Somalia', 'value': 'SOM'},
        {'label': 'South Africa', 'value': 'ZAF'},
        {'label': 'South Georgia and the South Sandwich Islands', 'value': 'SGS'},
        {'label': 'South Sudan', 'value': 'SSD'},
        {'label': 'Spain', 'value': 'ESP'},
        {'label': 'Sri Lanka', 'value': 'LKA'},
        {'label': 'Sudan (the)', 'value': 'SDN'},
        {'label': 'Suriname', 'value': 'SUR'},
        {'label': 'Svalbard and Jan Mayen', 'value': 'SJM'},
        {'label': 'Sweden', 'value': 'SWE'},
        {'label': 'Switzerland', 'value': 'CHE'},
        {'label': 'Syrian Arab Republic', 'value': 'SYR'},
        {'label': 'Taiwan (Province of China)', 'value': 'TWN'},
        {'label': 'Tajikistan', 'value': 'TJK'},
        {'label': 'Tanzania, United Republic of', 'value': 'TZA'},
        {'label': 'Thailand', 'value': 'THA'},
        {'label': 'Timor-Leste', 'value': 'TLS'},
        {'label': 'Togo', 'value': 'TGO'},
        {'label': 'Tokelau', 'value': 'TKL'},
        {'label': 'Tonga', 'value': 'TON'},
        {'label': 'Trinidad and Tobago', 'value': 'TTO'},
        {'label': 'Tunisia', 'value': 'TUN'},
        {'label': 'Turkey', 'value': 'TUR'},
        {'label': 'Turkmenistan', 'value': 'TKM'},
        {'label': 'Turks and Caicos Islands (the)', 'value': 'TCA'},
        {'label': 'Tuvalu', 'value': 'TUV'},
        {'label': 'Uganda', 'value': 'UGA'},
        {'label': 'Ukraine', 'value': 'UKR'},
        {'label': 'United Arab Emirates (the)', 'value': 'ARE'},
        {'label': 'United Kingdom of Great Britain and Northern Ireland (the)', 'value': 'GBR'},
        {'label': 'United States Minor Outlying Islands (the)', 'value': 'UMI'},
        {'label': 'United States of America (the)', 'value': 'USA'},
        {'label': 'Uruguay', 'value': 'URY'},
        {'label': 'Uzbekistan', 'value': 'UZB'},
        {'label': 'Vanuatu', 'value': 'VUT'},
        {'label': 'Venezuela (Bolivarian Republic of)', 'value': 'VEN'},
        {'label': 'Viet Nam', 'value': 'VNM'},
        {'label': 'Virgin Islands (British)', 'value': 'VGB'},
        {'label': 'Virgin Islands (U.S.)', 'value': 'VIR'},
        {'label': 'Wallis and Futuna', 'value': 'WLF'},
        {'label': 'Western Sahara', 'value': 'ESH'},
        {'label': 'Yemen', 'value': 'YEM'},
        {'label': 'Zambia', 'value': 'ZMB'},
        {'label': 'Zimbabwe', 'value': 'ZWE'},
        {'label': '\u00c5land Islands', 'value': 'ALA'}
      ],
      'choicesType': 'string'
    },
    {
      'name': 'edulevels',
      'type': 'fixed' as AjfChoicesOriginType,
      'label': '',
      'choices': [
        {'label': 'None', 'value': 'none'}, {'label': 'Primary school', 'value': 'prim'},
        {'label': 'Secondary', 'value': 'sec'}, {'label': 'High School Diploma', 'value': 'high'},
        {'label': 'University degree', 'value': 'univ'}, {'label': 'Master / Phd', 'value': 'phd'}
      ],
      'choicesType': 'string'
    },
    {
      'name': 'mf',
      'type': 'fixed' as AjfChoicesOriginType,
      'label': '',
      'choices': [
        {'label': 'Male', 'value': 'M'}, {'label': 'Female', 'value': 'F'},
        {'label': 'Other/not specified', 'value': 'O'}
      ],
      'choicesType': 'string'
    },
    {
      'name': 'positions',
      'type': 'fixed' as AjfChoicesOriginType,
      'label': '',
      'choices': [
        {'label': 'Manager - Responsible of areas or projects', 'value': 'manager'},
        {'label': 'Specialist - Specialized technicians (not managers)', 'value': 'specialist'},
        {'label': 'Officer - Clerks/executives', 'value': 'officer'},
        {'label': 'Support - Eg. logisticians, drivers', 'value': 'support'},
        {'label': 'Other (please specify)', 'value': 'other'}
      ],
      'choicesType': 'string'
    },
    {
      'name': 'reasons',
      'type': 'fixed' as AjfChoicesOriginType,
      'label': '',
      'choices': [
        {'label': 'Natural contract termination', 'value': 'natural'},
        {'label': 'Decision taken by WWGVC', 'value': 'byorg'},
        {'label': 'Decision taken by employee', 'value': 'bystaff'}
      ],
      'choicesType': 'string'
    }
  ],
  'stringIdentifier': [{'label': '', 'value': ['firstname']},
  {'label': '', 'value': ['name']}],
  'attachmentsOrigins': []
};

export const formSchemas: FormSchema[] = [{
  id: '',
  name: 'prova',
  label: 'Human Resources',
  icon: 'groups',
  schema: ajfSchema,
  created_at: '',
  updated_at: '',
}];
