// import '@dewco/core/locations/form-data';
// import '@dewco/core/projects/form-data';

import {FormData} from '@dewco/core/forms/form-data';
// import {Location} from '@dewco/core/locations';
// import {Project} from '@dewco/core/projects';

const ajfFormDatas = [
  {
    'dob': '1989-06-13',
    'sex': 'M',
    'matr': 'N/A',
    'name': 'Mehdi Ghazai',
    'natid': 7422495.0,
    'area__0': 'comm',
    'area__1': '',
    'city__0': 'Tunis',
    'city__1': '',
    'civstat': 'single',
    'country': 'TUN',
    'contract': 1.0,
    'edulevel': 'univ',
    'other__0': null,
    'other__1': '',
    'firstname': 'Mehdi Ghazai',
    'reason__0': 'natural',
    'reason__1': '',
    'ntrainings': 0.0,
    'citizenship': 'TUN',
    'date_end__0': '2021-08-31',
    'date_end__1': '',
    'parttime__0': false,
    'parttime__1': '',
    'position__0': 'specialist',
    'position__1': '',
    'date_start__0': '2021-01-04',
    'date_start__1': '',
    'nhourstraining': 0.0,
    'contract_type__0': 'consultant',
    'contract_type__1': ''
  },
  {
    'dob': '1993-04-14',
    'sex': 'F',
    'matr': 'N/A',
    'name': 'Najwa Brahmi',
    'natid': 11605709.0,
    'area__0': 'support',
    'area__1': '',
    'city__0': 'Sidi Bouzid',
    'city__1': '',
    'civstat': 'married',
    'country': 'TUN',
    'contract': 1.0,
    'edulevel': 'prim',
    'other__0': null,
    'other__1': '',
    'firstname': 'Najwa Brahmi',
    'reason__0': 'natural',
    'reason__1': '',
    'ntrainings': 0.0,
    'citizenship': 'TUN',
    'date_end__0': '2021-06-30',
    'date_end__1': '',
    'parttime__0': false,
    'parttime__1': '',
    'position__0': 'support',
    'position__1': '',
    'date_start__0': '2018-01-11',
    'date_start__1': '',
    'nhourstraining': 0.0,
    'contract_type__0': 'staff_fixed',
    'contract_type__1': ''
  },
  {
    'dob': '1977-10-13',
    'sex': 'F',
    'matr': 'N/A',
    'name': 'Sana Meftah',
    'natid': 8306036.0,
    'area__0': 'support',
    'area__1': '',
    'city__0': 'Tunis',
    'city__1': '',
    'civstat': 'married',
    'country': 'TUN',
    'contract': 1.0,
    'edulevel': 'prim',
    'other__0': null,
    'other__1': '',
    'firstname': 'Sana Meftah',
    'reason__0': 'natural',
    'reason__1': '',
    'ntrainings': 0.0,
    'citizenship': 'TUN',
    'date_end__0': '2021-06-30',
    'date_end__1': '',
    'parttime__0': false,
    'parttime__1': '',
    'position__0': 'support',
    'position__1': '',
    'date_start__0': '2018-01-11',
    'date_start__1': '',
    'nhourstraining': 0.0,
    'contract_type__0': 'staff_fixed',
    'contract_type__1': ''
  },
  {
    'dob': '1989-04-24',
    'sex': 'F',
    'matr': 'N/A',
    'name': 'Hejer Dhahbi',
    'natid': 4814706.0,
    'area__0': 'projdev',
    'area__1': '',
    'city__0': 'Tunis',
    'city__1': '',
    'civstat': 'single',
    'country': 'TUN',
    'contract': 1.0,
    'edulevel': 'univ',
    'other__0': null,
    'other__1': '',
    'firstname': 'Hejer Dhahbi',
    'reason__0': 'natural',
    'reason__1': '',
    'ntrainings': 0.0,
    'citizenship': 'TUN',
    'date_end__0': '2021-08-31',
    'date_end__1': '',
    'parttime__0': false,
    'parttime__1': '',
    'position__0': 'manager',
    'position__1': '',
    'date_start__0': '2020-11-05',
    'date_start__1': '',
    'nhourstraining': 0.0,
    'contract_type__0': 'staff_fixed',
    'contract_type__1': ''
  },
  {
    'dob': '1992-07-13',
    'sex': 'F',
    'matr': 'N/A',
    'name': 'Maissa Bradai',
    'natid': 11354373.0,
    'area__0': 'projdev',
    'area__1': '',
    'city__0': 'Tunis',
    'city__1': '',
    'civstat': 'single',
    'country': 'TUN',
    'contract': 1.0,
    'edulevel': 'univ',
    'other__0': null,
    'other__1': '',
    'firstname': 'Maissa Bradai',
    'reason__0': 'natural',
    'reason__1': '',
    'ntrainings': 0.0,
    'citizenship': 'TUN',
    'date_end__0': '2021-05-16',
    'date_end__1': '',
    'parttime__0': false,
    'parttime__1': '',
    'position__0': 'officer',
    'position__1': '',
    'date_start__0': '2021-03-17',
    'date_start__1': '',
    'nhourstraining': 0.0,
    'contract_type__0': 'staff_fixed',
    'contract_type__1': ''
  },
  {
    'dob': '1969-06-15',
    'sex': 'M',
    'matr': 'N/A',
    'name': 'Ramzi Medjoub',
    'natid': 1827135.0,
    'area__0': 'projdev',
    'area__1': '',
    'city__0': 'Kelibi',
    'city__1': '',
    'civstat': 'married',
    'country': 'TUN',
    'contract': 1.0,
    'edulevel': 'univ',
    'other__0': null,
    'other__1': '',
    'firstname': 'Ramzi',
    'reason__0': 'natural',
    'reason__1': '',
    'ntrainings': 0.0,
    'citizenship': 'TUN',
    'date_end__0': '2021-06-10',
    'date_end__1': '',
    'parttime__0': false,
    'parttime__1': '',
    'position__0': 'manager',
    'position__1': '',
    'date_start__0': '2021-03-11',
    'date_start__1': '',
    'nhourstraining': 0.0,
    'contract_type__0': 'staff_fixed',
    'contract_type__1': ''
  },
  {
    'dob': '1983-01-01',
    'sex': 'F',
    'matr': 'N/A',
    'name': 'Salwa Chenini',
    'natid': 6074812.0,
    'area__0': 'projdev',
    'area__1': '',
    'city__0': 'Sidi Bouzid',
    'city__1': '',
    'civstat': 'married',
    'country': 'TUN',
    'contract': 1.0,
    'edulevel': 'univ',
    'other__0': null,
    'other__1': '',
    'firstname': 'Salwa',
    'reason__0': 'natural',
    'reason__1': '',
    'ntrainings': 0.0,
    'citizenship': 'TUN',
    'date_end__0': '2021-12-31',
    'date_end__1': '',
    'parttime__0': false,
    'parttime__1': '',
    'position__0': 'manager',
    'position__1': '',
    'date_start__0': '2013-12-05',
    'date_start__1': '',
    'nhourstraining': 0.0,
    'contract_type__0': 'staff_fixed',
    'contract_type__1': ''
  },
];

// const locations: {[key: string]: Location} = {
//   'location_a': {
//     id: '',
//     created_at: '',
//     updated_at: '',
//     name: 'location_a',
//   },
//   'location_b': {
//     id: '',
//     created_at: '',
//     updated_at: '',
//     name: 'location_b',
//   },
//   'location_c': {
//     id: '',
//     created_at: '',
//     updated_at: '',
//     name: 'location_c',
//   },
// };

// const projects: {[key: string]: Project} = {
//   'project_a': {
//     id: '',
//     created_at: '',
//     updated_at: '',
//     name: 'project_a',
//   },
//   'project_b': {
//     id: '',
//     created_at: '',
//     updated_at: '',
//     name: 'project_b',
//   },
//   'project_c': {
//     id: '',
//     created_at: '',
//     updated_at: '',
//     name: 'project_c',
//   },
// };

export const formDatas: FormData[] = [
  {
    // location: locations.location_a,
    // project: projects.project_a,
    id: '',
    user_id: 'user_a',
    schema_id: 'prova',
    data: ajfFormDatas[0],
    created_at: '',
    updated_at: '',
  },
  {
    id: '',
    user_id: 'user_b',
    schema_id: 'prova',
    data: ajfFormDatas[1],
    created_at: '',
    updated_at: '',
  },
  {
    // location: locations.location_b,
    // project: projects.project_c,
    id: '',
    user_id: 'user_b',
    schema_id: 'prova',
    data: ajfFormDatas[2],
    created_at: '',
    updated_at: '',
  },
  {
    // location: locations.location_c,
    // project: projects.project_c,
    id: '',
    user_id: 'user_b',
    schema_id: 'prova',
    data: ajfFormDatas[3],
    created_at: '',
    updated_at: '',
  },
  {
    // project: projects.project_c,
    id: '',
    user_id: 'user_a',
    schema_id: 'prova',
    data: ajfFormDatas[4],
    created_at: '',
    updated_at: '',
  },
  {
    // location: locations.location_b,
    // project: projects.project_a,
    id: '',
    user_id: 'user_c',
    schema_id: 'prova',
    data: ajfFormDatas[5],
    created_at: '',
    updated_at: '',
  },
  {
    // location: locations.location_a,
    id: '',
    user_id: 'user_c',
    schema_id: 'prova',
    data: ajfFormDatas[6],
    created_at: '',
    updated_at: '',
  },
];
