import {ReportData} from '@dewco/core/reports';

export const ajfReportDatas = [
  {
    'number1': 277,
    'number2': 331,
    'string': 0,
    'bool': true,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option3',
    'multiplechoice': ['option5', 'option12'],
    'pet_type': 'dog',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 829,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 223,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 410,
    'number2': 134,
    'string': 0,
    'bool': true,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option1',
    'multiplechoice': ['option15', 'option14'],
    'pet_type': 'blackcat',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 651,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 225,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 147,
    'number2': 761,
    'string': 0,
    'bool': false,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option2',
    'multiplechoice': ['option11', 'option6'],
    'pet_type': 'cat',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 551,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 913,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 42,
    'number2': 560,
    'string': 0,
    'bool': false,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option2',
    'multiplechoice': ['option9', 'option3'],
    'pet_type': 'blackcat',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 727,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 371,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 322,
    'number2': 924,
    'string': 0,
    'bool': false,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option1',
    'multiplechoice': ['option14', 'option5'],
    'pet_type': 'cat',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 392,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 563,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 835,
    'number2': 731,
    'string': 0,
    'bool': false,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option3',
    'multiplechoice': ['option14', 'option9'],
    'pet_type': 'cat',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 145,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 579,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 505,
    'number2': 276,
    'string': 0,
    'bool': false,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option2',
    'multiplechoice': ['option1', 'option15'],
    'pet_type': 'blackcat',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 523,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 160,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 216,
    'number2': 952,
    'string': 0,
    'bool': true,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option2',
    'multiplechoice': ['option12', 'option10'],
    'pet_type': 'dog',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 564,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 429,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 761,
    'number2': 520,
    'string': 0,
    'bool': true,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option1',
    'multiplechoice': ['option4', 'option1'],
    'pet_type': 'blackcat',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 632,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 147,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 671,
    'number2': 988,
    'string': 0,
    'bool': false,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option1',
    'multiplechoice': ['option5', 'option14'],
    'pet_type': 'dog',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 947,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 730,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 165,
    'number2': 925,
    'string': 0,
    'bool': false,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option2',
    'multiplechoice': ['option7', 'option15'],
    'pet_type': 'dog',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 820,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 163,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 508,
    'number2': 662,
    'string': 0,
    'bool': false,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option2',
    'multiplechoice': ['option13', 'option8'],
    'pet_type': 'dog',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 546,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 964,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 869,
    'number2': 687,
    'string': 0,
    'bool': false,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option2',
    'multiplechoice': ['option5', 'option3'],
    'pet_type': 'cat',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 530,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 128,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 444,
    'number2': 616,
    'string': 0,
    'bool': true,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option2',
    'multiplechoice': ['option14', 'option15'],
    'pet_type': 'cat',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 422,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 868,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 617,
    'number2': 72,
    'string': 0,
    'bool': false,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option3',
    'multiplechoice': ['option13', 'option5'],
    'pet_type': 'dog',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 503,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 702,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 451,
    'number2': 434,
    'string': 0,
    'bool': false,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option1',
    'multiplechoice': ['option11', 'option1'],
    'pet_type': 'blackcat',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 817,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 165,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 259,
    'number2': 286,
    'string': 0,
    'bool': false,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option1',
    'multiplechoice': ['option4', 'option9'],
    'pet_type': 'cat',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 89,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 423,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 514,
    'number2': 766,
    'string': 0,
    'bool': true,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option2',
    'multiplechoice': ['option13', 'option3'],
    'pet_type': 'dog',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 45,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 353,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 3,
    'number2': 531,
    'string': 0,
    'bool': true,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option1',
    'multiplechoice': ['option14', 'option9'],
    'pet_type': 'blackcat',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 697,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 47,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 277,
    'number2': 276,
    'string': 0,
    'bool': true,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option2',
    'multiplechoice': ['option11', 'option4'],
    'pet_type': 'dog',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 726,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 44,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 627,
    'number2': 125,
    'string': 0,
    'bool': true,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option1',
    'multiplechoice': ['option5', 'option8'],
    'pet_type': 'cat',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 502,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 714,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  },
  {
    'number1': 319,
    'number2': 737,
    'string': 0,
    'bool': false,
    'empty': 0,
    'date input': 0,
    'time': 0,
    'barcode': 0,
    'singlechoice': 'option1',
    'multiplechoice': ['option9', 'option8'],
    'pet_type': 'cat',
    'cat_name': 0,
    'dog_name': 0,
    'amount': 262,
    'tip': 0,
    'total': 0,
    '': 0,
    'birthweight': 519,
    'name': 0,
    'customfield': 0,
    'row': 0,
    'file': 0,
    'image': 0,
    'video_url': 0
  }
];

export const reportDatas: ReportData[] = [
  {
    id: '',
    user_id: 'user_a',
    schema_id: 'generic_report',
    metadata: {},
    created_at: '',
    updated_at: '',
    area_id: null,
    location_id: null,
    organization_id: null,
    project_id: null,
  },
  {
    id: '',
    user_id: 'user_b',
    schema_id: 'generic_report',
    metadata: {},
    created_at: '',
    updated_at: '',
    area_id: null,
    location_id: null,
    organization_id: null,
    project_id: null,
  },
  {
    id: '',
    user_id: 'user_a',
    schema_id: 'generic_report',
    metadata: {},
    created_at: '',
    updated_at: '',
    area_id: null,
    location_id: null,
    organization_id: null,
    project_id: null,
  },
  {
    id: '',
    user_id: 'user_c',
    schema_id: 'generic_report',
    metadata: {},
    created_at: '',
    updated_at: '',
    area_id: null,
    location_id: null,
    organization_id: null,
    project_id: null,
  },
];