// import '@dewco/core/locations/form-data';
// import '@dewco/core/projects/form-data';
import '@dewco/core/areas/form-data';

import {FormData} from '@dewco/core/forms/form-data';

const ajfFormDatas = [
  {
    'dob': '1989-06-13',
    'sex': 'M',
    'matr': 'N/A',
    'name': 'Mehdi Ghazai',
    'natid': 7422495.0,
    'area__0': 'comm',
    'area__1': '',
    'city__0': 'Tunis',
    'city__1': '',
    'civstat': 'single',
    'country': 'TUN',
    'contract': 1.0,
    'edulevel': 'univ',
    'other__0': null,
    'other__1': '',
    'firstname': 'Mehdi Ghazai',
    'reason__0': 'natural',
    'reason__1': '',
    'ntrainings': 0.0,
    'citizenship': 'TUN',
    'date_end__0': '2021-08-31',
    'date_end__1': '',
    'parttime__0': false,
    'parttime__1': '',
    'position__0': 'specialist',
    'position__1': '',
    'date_start__0': '2021-01-04',
    'date_start__1': '',
    'nhourstraining': 0.0,
    'contract_type__0': 'consultant',
    'contract_type__1': ''
  },
  {
    'dob': '1993-04-14',
    'sex': 'F',
    'matr': 'N/A',
    'name': 'Najwa Brahmi',
    'natid': 11605709.0,
    'area__0': 'support',
    'area__1': '',
    'city__0': 'Sidi Bouzid',
    'city__1': '',
    'civstat': 'married',
    'country': 'TUN',
    'contract': 1.0,
    'edulevel': 'prim',
    'other__0': null,
    'other__1': '',
    'firstname': 'Najwa Brahmi',
    'reason__0': 'natural',
    'reason__1': '',
    'ntrainings': 0.0,
    'citizenship': 'TUN',
    'date_end__0': '2021-06-30',
    'date_end__1': '',
    'parttime__0': false,
    'parttime__1': '',
    'position__0': 'support',
    'position__1': '',
    'date_start__0': '2018-01-11',
    'date_start__1': '',
    'nhourstraining': 0.0,
    'contract_type__0': 'staff_fixed',
    'contract_type__1': ''
  },
  {
    'dob': '1977-10-13',
    'sex': 'F',
    'matr': 'N/A',
    'name': 'Sana Meftah',
    'natid': 8306036.0,
    'area__0': 'support',
    'area__1': '',
    'city__0': 'Tunis',
    'city__1': '',
    'civstat': 'married',
    'country': 'TUN',
    'contract': 1.0,
    'edulevel': 'prim',
    'other__0': null,
    'other__1': '',
    'firstname': 'Sana Meftah',
    'reason__0': 'natural',
    'reason__1': '',
    'ntrainings': 0.0,
    'citizenship': 'TUN',
    'date_end__0': '2021-06-30',
    'date_end__1': '',
    'parttime__0': false,
    'parttime__1': '',
    'position__0': 'support',
    'position__1': '',
    'date_start__0': '2018-01-11',
    'date_start__1': '',
    'nhourstraining': 0.0,
    'contract_type__0': 'staff_fixed',
    'contract_type__1': ''
  },
  {
    'dob': '1989-04-24',
    'sex': 'F',
    'matr': 'N/A',
    'name': 'Hejer Dhahbi',
    'natid': 4814706.0,
    'area__0': 'projdev',
    'area__1': '',
    'city__0': 'Tunis',
    'city__1': '',
    'civstat': 'single',
    'country': 'TUN',
    'contract': 1.0,
    'edulevel': 'univ',
    'other__0': null,
    'other__1': '',
    'firstname': 'Hejer Dhahbi',
    'reason__0': 'natural',
    'reason__1': '',
    'ntrainings': 0.0,
    'citizenship': 'TUN',
    'date_end__0': '2021-08-31',
    'date_end__1': '',
    'parttime__0': false,
    'parttime__1': '',
    'position__0': 'manager',
    'position__1': '',
    'date_start__0': '2020-11-05',
    'date_start__1': '',
    'nhourstraining': 0.0,
    'contract_type__0': 'staff_fixed',
    'contract_type__1': ''
  },
  {
    'dob': '1992-07-13',
    'sex': 'F',
    'matr': 'N/A',
    'name': 'Maissa Bradai',
    'natid': 11354373.0,
    'area__0': 'projdev',
    'area__1': '',
    'city__0': 'Tunis',
    'city__1': '',
    'civstat': 'single',
    'country': 'TUN',
    'contract': 1.0,
    'edulevel': 'univ',
    'other__0': null,
    'other__1': '',
    'firstname': 'Maissa Bradai',
    'reason__0': 'natural',
    'reason__1': '',
    'ntrainings': 0.0,
    'citizenship': 'TUN',
    'date_end__0': '2021-05-16',
    'date_end__1': '',
    'parttime__0': false,
    'parttime__1': '',
    'position__0': 'officer',
    'position__1': '',
    'date_start__0': '2021-03-17',
    'date_start__1': '',
    'nhourstraining': 0.0,
    'contract_type__0': 'staff_fixed',
    'contract_type__1': ''
  },
  {
    'dob': '1969-06-15',
    'sex': 'M',
    'matr': 'N/A',
    'name': 'Ramzi Medjoub',
    'natid': 1827135.0,
    'area__0': 'projdev',
    'area__1': '',
    'city__0': 'Kelibi',
    'city__1': '',
    'civstat': 'married',
    'country': 'TUN',
    'contract': 1.0,
    'edulevel': 'univ',
    'other__0': null,
    'other__1': '',
    'firstname': 'Ramzi',
    'reason__0': 'natural',
    'reason__1': '',
    'ntrainings': 0.0,
    'citizenship': 'TUN',
    'date_end__0': '2021-06-10',
    'date_end__1': '',
    'parttime__0': false,
    'parttime__1': '',
    'position__0': 'manager',
    'position__1': '',
    'date_start__0': '2021-03-11',
    'date_start__1': '',
    'nhourstraining': 0.0,
    'contract_type__0': 'staff_fixed',
    'contract_type__1': ''
  },
  {
    'dob': '1983-01-01',
    'sex': 'F',
    'matr': 'N/A',
    'name': 'Salwa Chenini',
    'natid': 6074812.0,
    'area__0': 'projdev',
    'area__1': '',
    'city__0': 'Sidi Bouzid',
    'city__1': '',
    'civstat': 'married',
    'country': 'TUN',
    'contract': 1.0,
    'edulevel': 'univ',
    'other__0': null,
    'other__1': '',
    'firstname': 'Salwa',
    'reason__0': 'natural',
    'reason__1': '',
    'ntrainings': 0.0,
    'citizenship': 'TUN',
    'date_end__0': '2021-12-31',
    'date_end__1': '',
    'parttime__0': false,
    'parttime__1': '',
    'position__0': 'manager',
    'position__1': '',
    'date_start__0': '2013-12-05',
    'date_start__1': '',
    'nhourstraining': 0.0,
    'contract_type__0': 'staff_fixed',
    'contract_type__1': ''
  },
];

const ajfSourceReportFormDatas = [
  {
    'age': 31,
    'poc': 'opd',
    'cf_od': null,
    'cf_os': null,
    'hm_od': null,
    'hm_os': null,
    'lp_od': null,
    'lp_os': null,
    'va_od': null,
    'va_os': '6_9',
    'gender': 'f',
    'iop_os': '21',
    'parish': 'aa',
    'lens_od': null,
    'lens_os': 'lens_clear',
    'district': 'arua',
    'pupil_od': null,
    'pupil_os': 'pupil_crrl',
    'cornea_od': null,
    'cornea_os': 'opaque',
    'fundus_od': null,
    'fundus_os': 'fundus_normal',
    'pregnancy': 'y',
    'eye_lid_od': null,
    'eye_lid_os': 'normal',
    'patient_id': '8989',
    'settlement': 'aa',
    'sub_county': 'vurra',
    'nationality': 'ugandans',
    'diagnosis_od': null,
    'diagnosis_os': ['ec03', 'ec08'],
    'disabilities': null,
    'eyes_checked': ['os'],
    'treatment_od': null,
    'treatment_os': ['spectacle'],
    'conjunctiva_od': null,
    'conjunctiva_os': 'normal',
    'chief_complaint': 'doc',
    'disability_status': 'n',
    'pupil_os_irregular': null,
    'anterior_chamber_od': null,
    'anterior_chamber_os': 'anterior_chamber_normal'
  },
  {
    'age': 56,
    'poc': 'pnc',
    'cf_od': null,
    'cf_os': null,
    'hm_od': null,
    'hm_os': null,
    'lp_od': null,
    'lp_os': null,
    'va_od': '6_24',
    'va_os': null,
    'gender': 'm',
    'iop_od': 14,
    'parish': 'A',
    'lens_od': 'lens_aphakic',
    'lens_os': null,
    'village': 'A',
    'district': 'lamwo',
    'pupil_od': 'pupil_crrl',
    'pupil_os': null,
    'cornea_od': 'clear',
    'cornea_os': null,
    'fundus_od': 'fundus_normal',
    'fundus_os': null,
    'pregnancy': null,
    'eye_lid_od': 'normal',
    'eye_lid_os': null,
    'patient_id': '6677',
    'settlement': 'A',
    'sub_county': 'padibe',
    'nationality': 'ugandans',
    'diagnosis_od': ['ec01'],
    'diagnosis_os': null,
    'disabilities': ['ds01'],
    'eyes_checked': ['od'],
    'treatment_od': ['other'],
    'treatment_os': null,
    'conjunctiva_od': 'inflamed',
    'conjunctiva_os': null,
    'chief_complaint': 'Doc',
    'disability_status': 'y',
    'treatment_other_od': 'antibiotics',
    'anterior_chamber_od': 'anterior_chamber_normal',
    'anterior_chamber_os': null
  },
  {
    'age': 56,
    'poc': null,
    'cf_od': null,
    'cf_os': null,
    'hm_od': null,
    'hm_os': null,
    'lp_od': null,
    'lp_os': null,
    'va_od': null,
    'va_os': null,
    'gender': 'm',
    'parish': 'Par',
    'lens_od': null,
    'lens_os': null,
    'district': 'agago',
    'pupil_od': null,
    'pupil_os': null,
    'cornea_od': null,
    'cornea_os': null,
    'fundus_od': null,
    'fundus_os': null,
    'pregnancy': null,
    'eye_lid_od': null,
    'eye_lid_os': null,
    'patient_id': '1234',
    'settlement': 'Sett',
    'sub_county': 'adilang',
    'nationality': 'ugandans',
    'diagnosis_od': null,
    'diagnosis_os': null,
    'disabilities': null,
    'eyes_checked': null,
    'treatment_od': null,
    'treatment_os': null,
    'conjunctiva_od': null,
    'conjunctiva_os': null,
    'disability_status': 'n',
    'anterior_chamber_od': null,
    'anterior_chamber_os': null
  },
  {
    'age': 19,
    'poc': 'pnc',
    'cf_od': null,
    'cf_os': null,
    'hm_od': null,
    'hm_os': null,
    'lp_od': null,
    'lp_os': null,
    'va_od': null,
    'va_os': null,
    'gender': 'f',
    'parish': 'Par',
    'lens_od': null,
    'lens_os': null,
    'village': 'Vil',
    'district': 'arua',
    'pupil_od': null,
    'pupil_os': null,
    'cornea_od': null,
    'cornea_os': null,
    'fundus_od': null,
    'fundus_os': null,
    'pregnancy': 'n',
    'eye_lid_od': null,
    'eye_lid_os': null,
    'patient_id': '3456',
    'settlement': 'Ar',
    'sub_county': 'omugo_hciv',
    'nationality': 'refugees',
    'diagnosis_od': null,
    'diagnosis_os': null,
    'disabilities': null,
    'eyes_checked': null,
    'treatment_od': null,
    'treatment_os': null,
    'conjunctiva_od': null,
    'conjunctiva_os': null,
    'disability_status': 'n',
    'anterior_chamber_od': null,
    'anterior_chamber_os': null
  },
];


export const formDatas: FormData[] = [
  {
    id: '',
    user_id: 'user_a',
    schema_id: 'prova',
    data: ajfFormDatas[0],
    created_at: '',
    updated_at: '',
    area_id: null,
    location_id: null,
    organization_id: null,
    project_id: null,
  },
  {
    id: '',
    user_id: 'user_b',
    schema_id: 'prova',
    data: ajfFormDatas[1],
    created_at: '',
    updated_at: '',
    area_id: null,
    location_id: null,
    organization_id: null,
    project_id: null,
  },
  {
    id: '',
    user_id: 'user_b',
    schema_id: 'prova',
    data: ajfFormDatas[2],
    created_at: '',
    updated_at: '',
    area_id: null,
    location_id: null,
    organization_id: null,
    project_id: null,
  },
  {
    id: '',
    user_id: 'user_b',
    schema_id: 'prova',
    data: ajfFormDatas[3],
    created_at: '',
    updated_at: '',
    area_id: null,
    location_id: null,
    organization_id: null,
    project_id: null,
  },
  {
    id: '',
    user_id: 'user_a',
    schema_id: 'prova',
    data: ajfFormDatas[4],
    created_at: '',
    updated_at: '',
    area_id: null,
    location_id: null,
    organization_id: null,
    project_id: null,
  },
  {
    id: '',
    user_id: 'user_c',
    schema_id: 'prova',
    data: ajfFormDatas[5],
    created_at: '',
    updated_at: '',
    area_id: null,
    location_id: null,
    organization_id: null,
    project_id: null,
  },
  {
    id: '',
    user_id: 'user_c',
    schema_id: 'prova',
    data: ajfFormDatas[6],
    created_at: '',
    updated_at: '',
    area_id: null,
    location_id: null,
    organization_id: null,
    project_id: null,
  },
];

export const sourceReportFormDatas: FormData[] = [
  {
    id: '',
    user_id: 'user_a',
    schema_id: 'prova',
    data: ajfSourceReportFormDatas[0],
    created_at: '',
    updated_at: '',
    area_id: null,
    location_id: null,
    organization_id: null,
    project_id: null,
  },
  {
    id: '',
    user_id: 'user_a',
    schema_id: 'prova',
    data: ajfSourceReportFormDatas[1],
    created_at: '',
    updated_at: '',
    area_id: null,
    location_id: null,
    organization_id: null,
    project_id: null,
  },
  {
    id: '',
    user_id: 'user_b',
    schema_id: 'prova',
    data: ajfSourceReportFormDatas[2],
    created_at: '',
    updated_at: '',
    area_id: null,
    location_id: null,
    organization_id: null,
    project_id: null,
  },
  {
    id: '',
    user_id: 'user_b',
    schema_id: 'prova',
    data: ajfSourceReportFormDatas[3],
    created_at: '',
    updated_at: '',
    area_id: null,
    location_id: null,
    organization_id: null,
    project_id: null,
  },
];
