import {UITourConfig} from '@dino/material/ui-tour-service';

export const tour: UITourConfig = {
  tourActive: true,
  tourSteps: [
    {
      stepId: 'start-tour',
      anchorId: 'start-tour',
      title: 'Benvenuti',
      content: 'Benvenuti in Dino BSAI!',
      route: '/dashboard',
      isAsync: true,
    },
    {
      stepId: 'edit-report',
      anchorId: 'edit-report',
      title: 'Controllo Completezza',
      content:
        'Controlla il report per controllare che i dati raccolti necessari siano stati compilati',
      route: '/dashboard',
      isOptional: true,
    },
    {
      stepId: 'forms-nav',
      anchorId: 'forms-nav',
      title: 'Raccogliere i dati',
      content: 'In questa sezione verranno raccolti tutti i dati per il Bilancio Sociale',
      route: '/dashboard',
    },
    {
      stepId: 'collect',
      anchorId: 'collect',
      title: 'Formulari per la raccolta dati',
      content: `Ciascuno di questi formulari permette di raccogliere i dati necessari alla realizzazione del tuo Bilancio Sociale.
          Selezionane uno e comincia la raccolta`,
      route: '/forms',
    },
    {
      stepId: '01 Metodologia',
      anchorId: '01 Metodologia',
      title: 'Form Metodologia',
      content: 'Questo è il formulario per la metodologia',
      route: '/forms',
    },
    {
      stepId: 'add-form-floating-button',
      anchorId: 'add-form-floating-button',
      title: 'Inizia l’inserimento dei dati',
      content: 'Stai aprendo un formulario vuoto e puoi cominciare ad inserire i tuoi dati',
      route: '/forms/bda3fe96-c140-46c2-a082-5464aaec89bb',
    },
    {
      stepId: 'metric-selector-creation-date',
      anchorId: 'metric-selector-creation-date',
      title: 'Data di creazione',
      content: `Assicurati che la data di creazione sia all'interno dell'anno di rendicontazione.
        Per comodità usa il 31/12 dell'anno in questione`,
      route: '/forms/bda3fe96-c140-46c2-a082-5464aaec89bb/create',
    },
    {
      stepId: 'go-to-form-data-button',
      anchorId: 'go-to-data-button',
      title: 'Compila form',
      content: `<b>Clicca</b><i class="material-icons">touch_app</i> il bottone Compila form per cominciare a inserire i tuoi dati e per proseguire il Tour!`,
      route: '/forms/bda3fe96-c140-46c2-a082-5464aaec89bb/create',
      popoverClass: 'dino-tour-step-popover dino-tour-step-active-popover',
      nextOnAnchorClick: true,
    },
    {
      stepId: 'create-form',
      anchorId: 'create-form',
      title: 'Compila tutte le sezioni',
      content: `Seleziona la modalità preferita e assicurati di compilare tutti i dati necessari evidenziati dal triangolino rosso`,
      route: '/forms/bda3fe96-c140-46c2-a082-5464aaec89bb/create',
      delayBeforeStepShow: 1000,
      prevStep: 'create-form',
    },
    {
      stepId: 'save-form-draft-floating-button',
      anchorId: 'save-draft-floating-button',
      title: 'Salva Bozza',
      content: `Se non termini la compilazione in una sessione unica, utilizza il tasto Salva Bozza per poi conitnuare in un secondo momento la compilazione`,
      route: '/forms/bda3fe96-c140-46c2-a082-5464aaec89bb/create',
    },
    {
      stepId: 'save-form-floating-button',
      anchorId: 'save-form-floating-button',
      title: 'Salva i dati',
      content: `Una volta terminata la compilazione, ricordati sempre di salvare i tuoi dati`,
      route: '/forms/bda3fe96-c140-46c2-a082-5464aaec89bb/create',
    },
    {
      stepId: 'edit-status-icon',
      anchorId: 'edit-status-icon',
      title: 'Approva il form',
      content: `Cliccando sull'edit status puoi confermare i dati inseriti`,
      route: 'forms/bda3fe96-c140-46c2-a082-5464aaec89bb',
    },
    {
      stepId: 'reports-nav',
      anchorId: 'reports-nav',
      title: 'Visualizza i report',
      content:
        'Una volta compilati tutti i dati necessari procedi alla generazione del tuo report del BS',
      route: 'forms/bda3fe96-c140-46c2-a082-5464aaec89bb',
    },
    {
      stepId: 'Report Bilancio Sociale - AI',
      anchorId: 'Report Bilancio Sociale - AI',
      title: 'Clicca sul Report BS - AI',
      content: 'Clicca sul Report BS - AI',
      route: '/reports',
    },
    {
      stepId: 'add-report-floating-button-credits',
      anchorId: 'add-report-floating-button-credits',
      title: 'Crediti necessari',
      content:
        'Assicurati di avere crediti a sufficienza per generare un report AI. Il costo di ogni report è di 20 crediti',
      route: '/reports/f4a538b0-faaf-4a35-bb30-c2cc6757e91f',
      backdropConfig: {
        offset: 6,
      },
    },
    {
      stepId: 'add-report-floating-button',
      anchorId: 'add-report-floating-button',
      title: 'Aggiungi nuovo report',
      content:
        '<b>Clicca sul bottone +</b><i class="material-icons">touch_app</i> per creare un nuovo report',
      popoverClass: 'dino-tour-step-popover dino-tour-step-active-popover',
      route: '/reports/f4a538b0-faaf-4a35-bb30-c2cc6757e91f',
      nextOnAnchorClick: true,
    },
    {
      stepId: 'metric-selector-status',
      anchorId: 'metric-selector-status',
      title: 'Seleziona lo stato dei form',
      content: 'Seleziona lo stato dei form utilizzati dal report',
      route: '/reports/f4a538b0-faaf-4a35-bb30-c2cc6757e91f/create',
    },
    {
      stepId: 'go-to-report-data-button',
      anchorId: 'go-to-data-button',
      title: 'Compila il Report',
      content: `<b>Clicca</b><i class="material-icons">touch_app</i> il bottone Compila Report per compilare i dati del report e per proseguire il Tour!`,
      route: '/reports/f4a538b0-faaf-4a35-bb30-c2cc6757e91f/create',
      popoverClass: 'dino-tour-step-popover dino-tour-step-active-popover',
      nextOnAnchorClick: true,
    },
    {
      stepId: 'create-report',
      anchorId: 'create-report',
      title: 'Assegna nome e date',
      content: `Assegna un nome e inserisci gli estremi dell'anno di rendicontazione`,
      route: '/reports/f4a538b0-faaf-4a35-bb30-c2cc6757e91f/create',
      delayBeforeStepShow: 1000,
      prevStep: 'create-report',
    },
    {
      stepId: 'save-report-floating-button',
      anchorId: 'save-report-floating-button',
      title: 'Salva il Report',
      content: `Una volta terminata la compilazione, ricordati sempre di salvare i dati del tuo Report`,
      route: '/reports/f4a538b0-faaf-4a35-bb30-c2cc6757e91f/create',
    },
  ],
  defaultStepOptions: {
    popoverClass: 'dino-tour-step-popover',
    prevBtnTitle: 'Indietro',
    nextBtnTitle: 'Avanti',
    endBtnTitle: 'Fine',
    duplicateAnchorHandling: 'registerLast',
    delayBeforeStepShow: 300,
    delayAfterNavigation: 1000,
    disablePageScrolling: true,
    disableScrollToAnchor: true,
  },
};
