load(
    "//tools:defaults.bzl",
    "markdown_to_html",
    "ng_module",
    "sass_binary",
    "sass_library",
)

package(default_visibility = ["//visibility:public"])

ng_module(
    name = "export-form",
    srcs = glob(
        ["**/*.ts"],
        exclude = ["**/*.spec.ts"],
    ),
    assets = [
        ":export-form.css",
        ":export-form-select-all-button.css",
    ] + glob(["**/*.html"]),
    deps = [
        "//src/core/areas",
        "//src/core/cases",
        "//src/core/data",
        "//src/core/forms",
        "//src/core/locations",
        "//src/core/organizations",
        "//src/core/projects",
        "@npm//@ajf/core",
        "@npm//@ajf/material",
        "@npm//@angular/common",
        "@npm//@angular/core",
        "@npm//@angular/forms",
        "@npm//@angular/material",
        "@npm//date-fns",
        "@npm//xlsx",
    ],
)

sass_library(
    name = "export_form_scss_lib",
    srcs = glob(["**/_*.scss"]),
)

sass_binary(
    name = "export_form_scss",
    src = "export-form.scss",
    deps = [],
)

sass_binary(
    name = "export_form_select_all_button_scss",
    src = "export-form-select-all-button.scss",
    deps = [],
)

markdown_to_html(
    name = "overview",
    srcs = ["export-form.md"],
)

filegroup(
    name = "source-files",
    srcs = glob(["**/*.ts"]),
)
