INHERIT: ../../mkdocs.base.yml
site_name: Документація Dinoapp
site_url: https://gnucoop.github.io/dino/uk/
docs_dir: ../../docs/uk
site_dir: ../../site/uk
theme:
  name: material
  language: uk
nav:
  - Головна: index.md
  - Початок Роботи:
    - Вхід: getting-started/login.md
    - Скидання Пароля: getting-started/reset-password.md
  - Інтерфейс та Навігація: interface/index.md
  - Панель: dashboard/index.md
  - Форми:
    - Огляд: forms/index.md
    - Редагування схеми форми: forms/edit-form-schema.md
    - Редагувати подання форми: forms/edit-form.md
    - Карта форм: forms/forms-map.md
    - Чат даних: forms/datachat.md
    - Import Data: forms/import.md
  - Звіти:
    - Огляд: reports/index.md
    - Редагувати схему звіту: reports/edit-report-schema.md
    - Редагувати звіт: reports/edit-report.md
  - Метрики:
    - Огляд: metrics/index.md
    - тематичні області: metrics/areas.md
    - Справи: metrics/cases.md
    - Місцезнаходження: metrics/locations.md
    - Організації: metrics/organizations.md
    - Проекти: metrics/projects.md
  - Агрегація: aggregation/index.md
  - Сповіщення: notifications/index.md
  - Публічні Форми: public-forms/index.md
  - Адміністрування:
    - Керування Користувачами та Групами: administration/users.md
    - Керування Мовами: administration/languages.md
    - Список Користувачів: administration/users-list.md
    - Список груп: administration/groups-list.md
