import {DinoEnvironment} from './environment-interface';

export const environment: DinoEnvironment = {
  'production': true,
  'installable': true,
  'authConfig': {
    //'host': 'http://localhost:9011',
    'host': '__AUTH_URL__',
    "nHostAuth": true,
    "userCredential": "email",
    'applicationId': null,
    'retryRefreshTime': 5000,
    'retryAttemptsMax': 1,
    'failedAuthRedirect': 'login',
    'signUp': false,
    'resetPassword': true,
  },
  'dataConfig': {
    //'syncGraphQLUrl': 'http://localhost:8080/v1/graphql',
    //'wsUrl': 'ws://localhost:8080/v1/graphql',
    'syncGraphQLUrl': '__SYNC_GRAPHQL_URL__',
    'wsUrl': '__WS_URL__',
    'instanceName': '__INSTANCE_NAME__',
    'authErrorMessage': 'Could not verify JWT: JWTExpired',
    'socketJwtExpiredCode': 4403,
    'formconv_post_url': 'https://formconv.herokuapp.com/result.json',
    //'instanceName': 'dino_local_dev',
    'live': true,
    // Max time (ms) the "Initializing data..." screen is shown before proceeding.
    // If omitted it is undefined and the screen never dismisses (infinite hang).
    //'initializationScreenMaxDuration': 20000,
    'backupRestore': true,
    'dynamicBackend': false,
    'dynamicBackendapiUrl': '',
    'backendless': false,
  },
  'usersConfig': {
    'adminRoles': ['admin'],
    'userSections': ['dashboard', 'forms', 'reports', 'aggregation', 'metrics'],
    'adminSections': ['users', 'languages', 'rag'],
    'enableEmail': false,
  },
  'formsConfig': {
    'statusType': 'default',
    'pipelines': [],
    'booleanQuickEdit': [],
    'saveDraft': false,
    'duplicateAction': true,
    'aggregationFormCreator': true,
    'formImport': true,
  },
  'metricsConfig': {
    'optionalFormMetrics': true,
    'optionalReportMetrics': true,
    'allowMetricCreationFor': ['all'],
    'secondaryMetricFieldsDisplayed': null,
  },
  'languageConfig': {
    'defaultLanguage': 'ENG',
    'availableLanguages': ['AR', 'ENG', 'ESP', 'FRA', 'ITA', 'PRT', 'UKR'],
  },
  'layoutConfig': {
    'dashboardType': 'report',
    'favorites': true,
    'centeredFieldsContent': false,
    'maxAjfFormColumns': 3,
    'initialExtendedSidenav': false,
    'bulkActions': true,
    'pageSize': 10,
    'pageSizeOptions': [5, 10, 25, 50, 100, 500],
    'helpTooltip': 'Dino Guidelines',
    'helpUrl': 'https://docs.google.com/document/d/1cYgPl48JmjCyT6Oxnqo4PJ6HTFQryOXbwh8rU0FQ1sk',
  },
  'optionalModulesConfig': {
    'areasModule': true,
    'caseModule': true,
    'projectsModule': true,
    'locationsModule': true,
    'organizationsModule': true,
    'gptModule': false,
    'logsModule': true,
    'stripePaymentModule': false,
  },
  pandinoConfig: {
    pandinoUrl: 'http://localhost:5000',
    pandinoGptNamespaces: ['Dino'],
  },
  'stripePaymentConfig': {
    'stripeKey': '',
    'gnuPayUrl': '',
    'pandinoTokenID': '',
  },
  'remoteTrackingConfig': {
    'analytics': false,
    'errors': false,
    'errorsOffline': false,
  },
  'themeConfig': {
    'primary': '#205475',
    'accent': '#43608B',
    'warning': '#9173AA',
    'isAutoContrast': true,
    'isDarkTheme': false,
  },
};
