load(
    "//tools:defaults.bzl",
    "markdown_to_html",
    "ng_module",
)

package(default_visibility = ["//visibility:public"])

ng_module(
    name = "langs",
    srcs = glob(
        ["**/*.ts"],
        exclude = ["**/*.spec.ts"],
    ),
    deps = [
        "//src/core/data",
        "//src/core/translations",
        "@npm//@ajf/core",
    ],
)

markdown_to_html(
    name = "overview",
    srcs = ["langs.md"],
)

filegroup(
    name = "source-files",
    srcs = glob(["**/*.ts"]),
)
